### ISSUE TITLE
Rename server extensions to addons

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1033]
In hindsight, using the name server extensions was not a good choice as it leads to confusion with VS Code extensions. There's no easy way to refer to them without saying "Ruby LSP server extensions".

Plugin may also lead to confusion given that, in editors other than VS Code, that's often the term used to describe their "extensions". Like Vim plugins.

Let's rename server extensions to addons. The name is descriptive enough and not overloaded with other meanings that could lead to confusion.

This will be a breaking change, but it's better we do this now than after there's a larger ecosystem of gems adding Ruby LSP functionality.

**Comment by andyw8** [comment]
`addon` or `add-on` 😁
