### ISSUE TITLE
Use Rubocop severity for non-correctable issues

### ISSUE THREAD

**Issue by nhumble-sa** [Shopify/ruby-lsp#1057]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

I have customized the severity of several Rubocop rules to lower their severity to `INFORMATION`, but they show up as warnings when run with ruby-lsp.

### Description

When running diagnostics, non-correctable Rubocop offenses have their severity explicitly set to `WARNING` instead of taking the configured severity from Rubocop.

### Implementation

Simply do no override the Rubocop severity. The code already gets the severity for auto-correctable offenses. The place where this is set is here:
https://github.com/Shopify/ruby-lsp/blob/db3e7129e199ca419f288b44351abb7f45a5edc3/lib/ruby_lsp/requests/support/rubocop_diagnostic.rb#L54

The other branch of that conditional just uses the severity from Rubocop:
https://github.com/Shopify/ruby-lsp/blob/db3e7129e199ca419f288b44351abb7f45a5edc3/lib/ruby_lsp/requests/support/rubocop_diagnostic.rb#L51

**Comment by andyw8** [comment]
Completed in https://github.com/Shopify/ruby-lsp/pull/1064
