### ISSUE TITLE
Investigate the possibility of adding GIFs to YARD documentation

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#108]
It's easier to see and understand documented features visually, rather than explain LSP requests in text.

Explore the possibility of adding GIFs to our requests documentation. E.g.:
- Are they displayed properly when generated from YARD?
- Where should GIFs be stored?

**Comment by st0012** [comment]
I've been using `yard server --reload` locally and it doesn't take the `--markup` for some reason and I didn't notice it:

```
[warn]: Unrecognized/invalid option: --markup
```

So I was always using the default markup (rdoc?) to render pages 🤦‍♂️ 

> Or maybe creating a wiki page for the gallery and just keep all gifs there. 

Wiki's editor acts like issue textarea and uploads images automatically. So I think this is more convenient than committing the images to the source. 

Another drawback of committing to source is we always need to consider the branch names in the urls. (e.g. works when reviewing on the branch but failed after merging into main).

**Comment by Morriar** [comment]
Regarding 1., do we know what is the file retention policy?

I wonder if a file may be deleted by Github after some time is no comment points to it?

I don't see anything related [in the docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).
