### ISSUE TITLE
Create a custom cop to check for event emitter discrepancies

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1080]
There are two steps involved in handling events from a listener: registering the event with the emitter and then defining the method to handle that event. It's easy to forget one or the other and end up in a weird state.

Let's add a custom cop to check if the registered events match the event methods. For example:

```ruby
class MyListener < Listener
  def initialize(emitter)
    emitter.register(
      self,
      :on_call,
      :on_def # ERROR: registered an event without a handler defined
    )
  end

  def on_call(node)
  end

  def on_class(node) # ERROR: created a handler without registering the associated event
  end
end
```

**Comment by snutij** [comment]
Hello @vinistock, I'm giving a try on it, if it's ok for you 👍 

Is it acceptable to rely on [Prism::Dispatcher](https://github.com/ruby/prism/blob/main/templates/lib/prism/dispatcher.rb.erb#L33) to have the list of all listeners? Probably more or less it as you did before [removing it](https://github.com/Shopify/ruby-lsp/blob/950716546a860ac8eec3cb615f2bbb1c57363280/lib/ruby_lsp/event_emitter.rb#L70).

Writing the list “by hand” will not be scalable 😄

**Comment by vinistock** [comment]
Hey! Of course, please go ahead.

I'm not sure I understand what you mean. Why do you need the list of listeners?

I think the way to go for this is:

- Find the invocation to `dispatcher.register` and get the list of registered events
- Collect each method definition on the class
- Report any discrepancies

**Comment by snutij** [comment]
On this way, this is simpler, we're aligned. 

But to warn handler without listener, how to do a difference between:

`def on_string_node_enter(node)`
`def do_something(node)`

First must trigger the cop if there is no listener, second one is an internal, valid method and without listener. 

I'll try to find a solution without the need of a “referential”, but any idea is welcome!
