### ISSUE TITLE
Some highlights coloured incorrectly (shorthand hash syntax)

### ISSUE THREAD

**Issue by wJoenn** [Shopify/ruby-lsp#1104]
### Ruby version

3.3.2

### Code snippet

```ruby
def some_method
  "do something"
end

some_hash = { some_method:, some_key: "dark blue" }

SOME_CONSTANT = some_hash
```

### Description

A constant is highlighted in green (like a class)
And when using a method as an implicit value inside an hash the key is highlighted in yellow (like a method)

![image](https://github.com/Shopify/ruby-lsp/assets/75388869/bcea3e97-9463-436e-a983-26d109dc7684)

### Expected output

I think the constant should be blue like variables and the key should be dark blue like a symbol

**Comment by vinistock** [comment]
Thank you for the report.

Note that the Ruby LSP does not control which colours are used to highlight the code. The Ruby LSP only provides semantic tokens and it's the theme's responsibility to decide how to highlight them.

The Ruby LSP semantic token information differentiates between variables and constants. If you want them to be the same colour, that would require adjusting your theme.

Concerning the short hand hash syntax, Ruby itself considers the key to be a method call, which is why it gets highlighted as one. Example:

```shell
pp Prism.parse("{ foo: }").value


@ ProgramNode (location: (1,0)-(1,8))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(1,8))
    └── body: (length: 1)
        └── @ HashNode (location: (1,0)-(1,8))
            ├── opening_loc: (1,0)-(1,1) = "{"
            ├── elements: (length: 1)
            │   └── @ AssocNode (location: (1,2)-(1,6))
            │       ├── key:
            │       │   @ SymbolNode (location: (1,2)-(1,6))
            │       │   ├── opening_loc: ∅
            │       │   ├── value_loc: (1,2)-(1,5) = "foo"
            │       │   ├── closing_loc: (1,5)-(1,6) = ":"
            │       │   └── unescaped: "foo"
            │       ├── value:
            │       │   @ ImplicitNode (location: (1,2)-(1,6))
            │       │   └── value:
            │       │       @ CallNode (location: (1,2)-(1,6))
            │       │       ├── receiver: ∅
            │       │       ├── call_operator_loc: ∅
            │       │       ├── message_loc: (1,2)-(1,5) = "foo"
            │       │       ├── opening_loc: ∅
            │       │       ├── arguments: ∅
            │       │       ├── closing_loc: ∅
            │       │       ├── block: ∅
            │       │       ├── flags: ∅
            │       │       └── name: "foo"
            │       └── operator_loc: ∅
            └── closing_loc: (1,7)-(1,8) = "}"
```

So these two behaviours are by design.

**Comment by wJoenn** [comment]
Ah alright.
Thanks for the fast answer

**Comment by andyw8** [comment]
Re-opening after some internal discussion:

The hash shorthand is about omitting the value, not the key. So in `{ foo:, bar: baz }`, `foo` is still the key but with the value omitted. So it should be highlighted as a key would be.

To make it clear what the implicit value is, we can add an inlay hint, indicating if the value is a variable, method call, etc.
