### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by vitaliiorlov** [Shopify/ruby-lsp#1115]
### Ruby version

3.2.2

### Description

When I updated the rubocop gem from 1.56.4 to the 1.57.1 version, the ruby-lsp stopped working.
If I downgrade the rubocop gem to the 1.56.4 version, the ruby-lsp starts working again after VScode relaunching.

attaching VScode output:
[ruby-lsp-report.txt](https://github.com/Shopify/ruby-lsp/files/12998106/ruby-lsp-report.txt)

### Expected output

ruby-lsp works with the latest version of rubocop gem.

**Comment by vitaliiorlov** [comment]
Update: now it stopped working with rubocop 1.56.4 version too.

**Comment by vitaliiorlov** [comment]
@andyw8 no, it doesn't.
![image](https://github.com/Shopify/ruby-lsp/assets/1788994/1be27cfd-8f19-4c0c-a591-97fdaf97cbda)

**Comment by andyw8** [comment]
Ok, could you please try save [this](https://gist.github.com/andyw8/630bb27450592f9b05ad591cfbf54d03) file into your repo, then run:

`bundle exec ruby index_check.rb`

It will print out the path last file indexed before the crash. It's likely from a gem.

**Comment by andyw8** [comment]
Sorry, `.ruby-lsp` (hyphen).

**Comment by andyw8** [comment]
Sorry, I was checking against `main` but that isn't yet released, please try this instead:

```
require "ruby-lsp"
require "ruby_lsp/internal"

module RubyIndexer
  index = Index.new

  RubyIndexer.configuration.indexables.each do |indexable|
    puts "indexing: #{indexable.full_path}"
    content = File.read(indexable.full_path)
    visitor = IndexVisitor.new(index, YARP.parse(content), indexable.full_path)
    visitor.run
  end
end
```

**Comment by st0012** [comment]
PR for the above: https://github.com/getsentry/sentry-ruby/pull/2146

**Comment by vitaliiorlov** [comment]
Cool!
Thanks, @andyw8 and @st0012 !
