### ISSUE TITLE
Look into using RuboCop's highlight range for diagnostics

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1119]
According to https://github.com/Shopify/ruby-lsp/issues/355#issuecomment-1769036623, RuboCop violations include a highlight range, which can be used by us to report diagnostics in a more editor friendly manner.

Let's investigate if this works as expected and switch to using that range.

**Comment by bartimez** [comment]
Any news on this front? Are y'all in development on this, or actively looking for PRs?

**Comment by vinistock** [comment]
We're not actively looking into this at the moment, but we do accept PRs. I believe Nathan is right about where we need to change, we just need to verify that it does indeed produce the result desired.

A few tests will likely need to be updated too.
