### ISSUE TITLE
"Extract Variable" refactor variable rename does not work

### ISSUE THREAD

**Issue by machty** [Shopify/ruby-lsp#1133]
### Ruby version

3.2.1

### Code snippet

```
send challenges.sample
```

### Description

When I select and extract "challenges.sample", it successfully extracts "new_variable" and selects it so that I can provide the variable name, but when I update the variable name, it only updates one variable name reference and not the other. Video demo:

https://github.com/Shopify/ruby-lsp/assets/81818/b27213c1-bdeb-4622-bf5f-70b0c24e2670

### Expected output

See description

**Comment by vinistock** [comment]
I think that would require returning a snippet from the refactor code action is which currently not supported by the LSP spec.

See https://github.com/microsoft/language-server-protocol/issues/592 and https://github.com/microsoft/language-server-protocol/issues/724.
