### ISSUE TITLE
Handle missing constant nodes in document symbol

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1154]
After the change to the Prism parser, we are no longer handling all possible constant cases in document symbol. We handle the standard ones (constant_write and constant_path_write), but we're missing

- constant_path_or_write_node
- constant_path_operator_write_node
- constant_path_and_write_node
- constant_or_write_node
- constant_operator_write_node
- constant_and_write_node

**Comment by jenenliu** [comment]
Hi @vinistock , I would like to fix this, but not so familiar with ruby-lsp, can you give me some hints ? Thanks.

**Comment by giovannism20** [comment]
When adding new event should name it with prefix `on_*` or it isn't a rule ?

**Comment by giovannism20** [comment]
Yes but my doubt is about the new events that should be added. Example: needs to add this event `constant_path_or_write_node` should use this name or should I put `on` at the prefix of name ?
