### ISSUE TITLE
Indexing fails due to stack level too deep error

### ISSUE THREAD

**Issue by awaken180-dev** [Shopify/ruby-lsp#1164]
### Operating System

macOS Monterey

### Ruby version

3.1.1p18

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Indexing fails at 18% on intitialization of ruby-lsp.  It reaches a StackLevelTooDeep error while indexing the Prism gem.  

```
#<Thread:0x0000000108307a38 /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.12.2/lib/ruby_lsp/executor.rb:213 run> terminated with exception (report_on_exception is true):
/Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `each': stack level too deep (SystemStackError)
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `visit_child_nodes'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/node.rb:14924:in `accept'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `block in visit_child_nodes'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `each'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `visit_child_nodes'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/node.rb:14924:in `accept'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `block in visit_child_nodes'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/prism-0.15.1/lib/prism/visitor.rb:23:in `each'
	 ... 528 levels...
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.12.2/lib/ruby_indexer/lib/ruby_indexer/index.rb:169:in `index_all'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11114/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.11114/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/user/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ruby-lsp-0.12.2/lib/ruby_lsp/executor.rb:215:in `block in perform_initial_indexing'
```

**Comment by vinistock** [comment]
To be able to understand what's going on, we'll need to figure out what code structure is causing the error. If the `ruby-lsp-doctor` executable is not reproducing it, but you can consistently reproduce it in the editor, then could you please try the following?

We'll edit the Ruby LSP code to print which file caused the issue

- `bundle open ruby-lsp`
- Above [this line](https://github.com/Shopify/ruby-lsp/blob/a6f5d134ac983215d2cf2755246c292a23e0ff9c/lib/ruby_indexer/lib/ruby_indexer/index.rb#L175), add
```ruby
# Note: it has to be `warn`. Do not print to STDOUT or the LSP will get into an infinite loop
warn(path.full_path)
```
- Check VS Code's `Ruby LSP` channel in the `Output` tab. What file is printed immediately before the error?

**Comment by ashaninBenjamin** [comment]
I am facing the same issue.
macos Sonoma
asdf
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [arm64-darwin22]
Bundler version 2.4.19 (2023-08-17 commit 86f98098e3)

`ruby-lsp-doctor` does not reproduce the issue.
Added the line from [the comment before](https://github.com/Shopify/ruby-lsp/issues/1164#issuecomment-1796428568).

The last lines of the output:
```
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/rubygems.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/securerandom.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/set/sorted_set.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/set.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/shellwords.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/singleton.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/socket.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/syslog/logger.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/tempfile.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/time.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/timeout.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/tmpdir.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/tracer.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/tsort.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/un.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/unicode_normalize/normalize.rb
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/3.0.0/unicode_normalize/tables.rb
#<Thread:0x0000000127527e70 /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/ruby-lsp-0.12.3/lib/ruby_lsp/executor.rb:213 run> terminated with exception (report_on_exception is true):
/Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `each': stack level too deep (SystemStackError)
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `visit_child_nodes'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/node.rb:15099:in `accept'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `block in visit_child_nodes'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `each'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `visit_child_nodes'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/node.rb:15099:in `accept'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `block in visit_child_nodes'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/prism-0.17.1/lib/prism/visitor.rb:27:in `each'
	 ... 532 levels...
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/ruby-lsp-0.12.3/lib/ruby_indexer/lib/ruby_indexer/index.rb:169:in `index_all'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.11116/lib/types/private/methods/_methods.rb:277:in `bind_call'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.11116/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /Users/benj/.asdf/installs/ruby/3.0.6/lib/ruby/gems/3.0.0/gems/ruby-lsp-0.12.3/lib/ruby_lsp/executor.rb:215:in `block in perform_initial_indexing'
```

**Comment by ashaninBenjamin** [comment]
Thank you @vinistock. Now it works

**Comment by datanoise** [comment]
The file is not a ruby file. It is called `tags` with no extension and it contains tags generated by [ctags](https://github.com/universal-ctags/ctags) utility. I was surprised why it is actually being indexed. 

Also since the ruby is installed by `rbenv` the full path to the file contains a directory name starting with the dot. If you look at this line

https://github.com/Shopify/ruby-lsp/blob/2cc633e272d3cc1b51d122e18c6593fe38c0f920/lib/ruby_indexer/lib/ruby_indexer/configuration.rb#L88

the search function doesn't include `File::FNM_DOTMATCH` option. I have tried to add it, but the patterns `**/tags` still does not exclude this file from indexing.

**Comment by vinistock** [comment]
The PR https://github.com/Shopify/ruby-lsp/pull/1221 should fix this. Concerning excluding paths, sorry I gave you incorrect information.

Everything inside `rubylibdir` (`.rbenv/versions/3.2.2/lib/ruby/3.2.0/`) is a default gem declaration. If you take a look inside that directory, you'll find the files for `pathname`, `bundler`, etc. It's an odd choice for ctags to place a random file in the middle of default gems.

Our indexer considers everything inside that directory to be a default gem and those can't be excluded by a glob pattern, which is why it's not working. You need to use the name of the default gem to exclude it.

In this case, the file isn't an actual gem, but we'd consider it's "name" to be the filename with no extensions (i.e.: tags). So you should be able to exclude it with this

```yaml
excluded_gems:
  - tags
```

That said, if you can share, I'm still curious to know the contents of the file. At least the structure. Because if trying to index that file results in a stack error, we want to understand if it's a possible scenario that we need to push a fix for.
