### ISSUE TITLE
Failed to activate custom environment: Command failed...

### ISSUE THREAD

**Issue by SaidRasinlic** [Shopify/ruby-lsp#1175]
### Ruby version

3.2.2

### Description

OS: Windows 10
Code editor: VSCode
Ruby version: 3.2.2
Ruby version manager: **custom** (I got  _none_, so I put it as a _custom_, like the documentation suggests.)
<hr />

**I wanted to ensure that the issues were not exclusive to my computer but were widespread. I contacted a buddy who also uses Windows 10 to configure Ruby LSP, and he confirmed (with screenshots 😄) that he receives the same issues.**

## First approach:

With these two lines of code in JSON configuration settings:
- "rubyLsp.rubyVersionManager": "custom",
- "rubyLsp.customRubyCommand": "cmd /C PATH=C:\\Ruby32-x64\\bin;%PATH%"

I receive the following error: 
  
![Syntax-Error](https://github.com/Shopify/ruby-lsp/assets/57558480/a716c8bb-7253-4eee-8a8d-0970bb728e93)

<hr/>

## Second approach:

Now, with these two lines of code:
 - "rubyLsp.rubyVersionManager": "custom",
 -  "rubyLsp.customRubyCommand": "PATH=C:\\Ruby32-x64\\bin;%PATH% && ruby -rjson -e \"STDERR.printf('%s', JSON.dump({ 'RUBY_ENV_ACTIVATE' => { 'env' => ENV.to_h, 'ruby_version' => RUBY_VERSION, 'yjit' => defined?(RubyVM::YJIT) } }))\"",

I get the following error (it seems like it successfully extracts the data of **_ruby/bin_** in JSON format but still doesn't start LSP):

![Ruby-LSP-Error](https://github.com/Shopify/ruby-lsp/assets/57558480/998c07aa-2acd-483c-b64b-9dcba7469b14)

### Expected output

I expect Ruby LSP to operate and start properly.

**Comment by SaidRasinlic** [comment]
> Thank you for the bug report! The second option is the right approach, just pushing something into the PATH.
> 
> It looks like the output was a bit too long for the VS Code dialogue box. I can't see what the actual error was, just parts of the JSON.
> 
> If you look at the `Ruby LSP` channel in VS Code's `Output` tab, is there any information about what error occurred? Did it fail to parse the JSON?

Not really, it only outputs this: 

2023-11-10 18:29:13.455 [info] Trying to activate Ruby environment with command: PATH=C:\Ruby32-x64\bin;%PATH% && ruby -rjson -e "STDERR.printf('%s', JSON.dump({ 'RUBY_ENV_ACTIVATE' => { 'env' => ENV.to_h, 'ruby_version' => RUBY_VERSION, 'yjit' => defined?(RubyVM::YJIT) } }))" && ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE},
      JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))" inside directory: c:\Users\Said\Documents\VSCodeProjects\student_registration_system


I also tried to reinstall Ruby LSP but it's not working still..

Interesting: If I manually run this command  `_ruby -rjson -e "STDERR.printf('%s', JSON.dump({ 'RUBY_ENV_ACTIVATE' => { 'env' => ENV.to_h, 'ruby_version' => RUBY_VERSION, 'yjit' => defined?(RubyVM::YJIT) } }))"_ ` inside of  **C:\Ruby32-x64\bin\ruby.exe** I get an error that closes the prompt so fast that I had to record it on my phone and then find out what it is, and it says this:
![Screenshot_20231110_184131_com huawei himovie overseas](https://github.com/Shopify/ruby-lsp/assets/57558480/32fbd604-d015-498e-8d0d-58a81e9bf8e3)

**Comment by W4RH4WK** [comment]
Currently encountering the same issue. Is there a workaround, or a way to provide more information on the issue?

**Comment by sandrosilveira** [comment]
Same error here, seems to be started after update VsCode from 1.83 to 1.84.

I tried to create a Custom batch file to configure the PATH to my customized ruby wrapper, but seems that ins't running it.

the output is:

Failed to activate custom environment: Command failed: s:\bat\CustomRubyPath.bat && ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE},
      JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"
-e:1: syntax error, unexpected end-of-input, expecting ')'
...V_ACTIVATE%sRUBY_ENV_ACTIVATE},
...                               ^
-e: compile error (SyntaxError)

**Comment by W4RH4WK** [comment]
Note: extension version `0.4.13` does not have this error.

**Comment by vinistock** [comment]
The changes in https://github.com/Shopify/vscode-ruby-lsp/pull/904 should fix this issue. Thank for reporting.

**Comment by vinistock** [comment]
Version [v0.4.18](https://github.com/Shopify/vscode-ruby-lsp/releases/tag/v0.4.18) should fix this. Please let us know if you find any other issues.

**Comment by sandrosilveira** [comment]
works fine!!!!

2023-11-20 13:28:02.521 [info] Trying to activate Ruby environment with command: s:\bat\CustomRubyPath.bat && ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))" inside directory: s:\BAT
2023-11-20 13:28:16.445 [info] Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
2023-11-20 13:28:18.105 [info] Resolving dependencies...
2023-11-20 13:28:18.322 [info] The Gemfile's dependencies are satisfied
2023-11-20 13:28:24.916 [info] Starting Ruby LSP v0.12.3...
2023-11-20 13:28:25.014 [info] Ruby LSP is ready

**Comment by SaidRasinlic** [comment]
> The changes in [Shopify/vscode-ruby-lsp#904](https://github.com/Shopify/vscode-ruby-lsp/pull/904) should fix this issue. Thank for reporting.

## Yay!!! It works 💯 🔥  

### A small note but important: If anyone receives error like **_`"Failed to activate custom environment: Unexpected non-whitespace character after JSON at position 4"`_** please make sure to fix your **_customRubyCommand_** in **_settings.json_** to this:
 ` 
"rubyLsp.rubyVersionManager": "custom",
"rubyLsp.customRubyCommand": "PATH=C:\\Ruby32-x64\\bin;%PATH%",
`

So **_customRubyCommand_** goes without **_STDERR.printf('%s', JSON.dump(...))_** error stream...

And if that doesn't work, use this approach and it should work fine: 
` "rubyLsp.customRubyCommand": "PATH=C:\\Ruby32-x64\\bin;%PATH% && ruby -rjson -e \"puts({ 'RUBY_ENV_ACTIVATE' => { 'env' => ENV.to_h, 'ruby_version' => RUBY_VERSION, 'yjit' => defined?(RubyVM::YJIT) } }.to_json)\"`

In this case we used **_puts({ ... }.to_json)_** approach instead of **_STDERR.printf('%s', JSON.dump(...))_**
`
