### ISSUE TITLE
Add stable releases

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#118]
Since bugs in the Ruby LSP can be disruptive of developer's workflows, we should have a stable release branch, which includes only changes that we are confident can be pushed forward.

Investigate and prototype a mechanism for doing regular stable releases from a stable branch. Tapioca has something similar and can serve as an example.

**Comment by paracycle** [comment]
First of all get rid of https://github.com/Shopify/ruby-lsp/blob/main/shipit.production.yml, since I found out that ShipIt works just fine without it and since the name needs to match the stack name now, it ends up causing problems with different ShipIt stacks.

**Comment by wildmaples** [comment]
What is the difference between semantic versioning and the `0-0-stable` style versioning?
