### ISSUE TITLE
Can't get auto-completion to work

### ISSUE THREAD

**Issue by W4RH4WK** [Shopify/ruby-lsp#1188]
### Ruby version

3.2.2

### Description

I am on a pretty clean install on Windows, and I am having a hard time getting this extension to work properly, specifically auto-completion.

I've encountered #1175 but downgrading the extension to 0.4.13 got rid of that error.

I am using Ruby to write some minor scripts / tools in a larger C++ code-base. I've set up a custom Gemfile just for this extension:
```
source "https://rubygems.org"

gem "rubocop"
gem "ruby-lsp"
```

With a `.ruby-version` next to it:
```
3.2.2
```

My VSCode config points to this:
```
"rubyLsp.bundleGemfile": "C:\\Users\\w4rh4wk\\git\\ank\\.vscode\\ruby-lsp\\Gemfile"
```

When I now create a new file `test.rb` the extension appears to load properly; LSP is started.
```
Ruby LSP> Checking if asdf is available on the path with command: asdf --version
Ruby LSP> Checking if chruby is available on the path with command: chruby --version
Ruby LSP> Checking if rbenv is available on the path with command: rbenv --version
Ruby LSP> Checking if rvm is available on the path with command: rvm --version
Ruby LSP> Discovered version manager none
Ruby LSP> Trying to activate Ruby environment with command: ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))" inside directory: C:\Users\w4rh4wk\git\ank\.vscode\ruby-lsp
Starting Ruby LSP v0.12.3...
Ruby LSP is ready
```

I also get Rubocop complaining about not using CRLF line-endings. But auto-completion does not work:

![image](https://github.com/Shopify/ruby-lsp/assets/328798/02ea61d7-89e4-48c6-814a-fdfcfcfcadb6)

Asking the LSP for a syntax-tree yields some result:

```
@ ProgramNode (location: (1,0)-(2,6))
├── locals: []
└── statements:
    @ StatementsNode (location: (1,0)-(2,6))
    └── body: (length: 2)
        ├── @ CallNode (location: (1,0)-(1,10))
        │   ├── receiver: ∅
        │   ├── call_operator_loc: ∅
        │   ├── message_loc: (1,0)-(1,4) = "puts"
        │   ├── opening_loc: ∅
        │   ├── arguments:
        │   │   @ ArgumentsNode (location: (1,5)-(1,10))
        │   │   ├── arguments: (length: 1)
        │   │   │   └── @ StringNode (location: (1,5)-(1,10))
        │   │   │       ├── flags: ∅
        │   │   │       ├── opening_loc: (1,5)-(1,6) = "'"
        │   │   │       ├── content_loc: (1,6)-(1,9) = "foo"
        │   │   │       ├── closing_loc: (1,9)-(1,10) = "'"
        │   │   │       └── unescaped: "foo"
        │   │   └── flags: ∅
        │   ├── closing_loc: ∅
        │   ├── block: ∅
        │   ├── flags: ∅
        │   └── name: :puts
        └── @ CallNode (location: (2,0)-(2,6))
            ├── receiver:
            │   @ StringNode (location: (2,0)-(2,5))
            │   ├── flags: ∅
            │   ├── opening_loc: (2,0)-(2,1) = "'"
            │   ├── content_loc: (2,1)-(2,4) = "bar"
            │   ├── closing_loc: (2,4)-(2,5) = "'"
            │   └── unescaped: "bar"
            ├── call_operator_loc: (2,5)-(2,6) = "."
            ├── message_loc: (2,6)-(2,6) = ""
            ├── opening_loc: ∅
            ├── arguments: ∅
            ├── closing_loc: ∅
            ├── block: ∅
            ├── flags: ∅
            └── name: :""
```

So what's going on here? 

### Expected output

Auto-completion to just work (similar to VSCode's popular Python extension).

**Comment by vinistock** [comment]
Thank you for the bug report!

> I also get Rubocop complaining about not using CRLF line-endings

I think this is RuboCop's default on Windows. You'll need to change RuboCop's configuration if you want to use `\n` instead of `\r\n` for line breaks.

Concerning completion, we are still implementing definition, hover and completion for methods, which is why it's not yet available. You can find details about the supported features in our [documentation](https://shopify.github.io/ruby-lsp/RubyLsp/Requests.html).

That said, these features should be working for classes, modules and constants, which we already do support. Please let us know if that's not the case.
