### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by kuator** [Shopify/ruby-lsp#1190]
### Ruby version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

### Code snippet

```ruby
def test(a1 = "Ruby", a2 = "Perl")
   puts "The programming language is #{a1}"
   puts "The programming language is #{a2}"
end

test("C", "C++")
```

### Description

Ruby-lsp says it's running, but neither autocompletion nor go to definition work. I tried running the latest 0.12.3 and a random past version, but no cigar.

![Screenshot from 2023-11-19 20-31-27](https://github.com/Shopify/ruby-lsp/assets/25168308/3a5378a8-9eca-4210-b753-307f47a84f6c)

### Expected output

It works

**Comment by vinistock** [comment]
Thank you for the report. Support for methods has not been finalized yet (#899), which is why the feature isn't available.

You can find supported features in our [documentation](https://shopify.github.io/ruby-lsp/RubyLsp/Requests.html).
