### ISSUE TITLE
Handle `alias` and `alias_method` in document symbol

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1209]
We are currently not handling method aliases in document symbol so they do not show up in the file outline. I think we should include those since they are method declarations.

We likely need to modify the [call event](https://github.com/Shopify/ruby-lsp/blob/6f942259374671b1adbf2e1914883af9d81c9eeb/lib/ruby_lsp/requests/document_symbol.rb#L126) to handle `alias_method`. For `alias`, there's probably a separate event given that it's a keyword. We need to start handling the alias event.

**Comment by namrata18s** [comment]
Can I work on this issue? will create PR soon. Thankyou!

**Comment by vinistock** [comment]
Of course! Assigning this to you.

**Comment by henriquebcustodio** [comment]
Hey guys 👋 

I saw that this issue was open for quite a while and decided to give it a try. I hope you don't mind!
