### ISSUE TITLE
Send notification to user if rubyLsp.formatter setting isn't in enum

### ISSUE THREAD

**Issue by jscharf** [Shopify/ruby-lsp#1213]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

If the user wants to add a formatting option that isn't in the existing enum (found on [package.json#L234](https://github.com/Shopify/vscode-ruby-lsp/blob/e2773b54aeb80a00cce78ecd9406dbca7d75c0e7/package.json#L234)), we should throw up a notification to the user.

### Description

This feature was mentioned as part of the discussion on https://github.com/Shopify/ruby-lsp/issues/1775

### Implementation

Quotes from @vinistock from the other issue

>We could display an information message from the server if it is initialized with a formatter and it cannot find it in the registry.
>
>The server can push dialogues for the editor to display through notifications. [Here](https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/executor.rb#L133-L139) we show an error is there's a problem with formatting.
>
>What we'd need to do is after loading addons is complete [here](https://github.com/Shopify/ruby-lsp/blob/6ca22bc2d9ce335ed22a234f49f8c1f9154ab3ed/lib/ruby_lsp/executor.rb#L58), we check if the [registry](https://github.com/Shopify/ruby-lsp/blob/6ca22bc2d9ce335ed22a234f49f8c1f9154ab3ed/lib/ruby_lsp/requests/formatting.rb#L95) includes the formatter saved in the store ([example](https://github.com/Shopify/ruby-lsp/blob/6ca22bc2d9ce335ed22a234f49f8c1f9154ab3ed/lib/ruby_lsp/executor.rb#L356)). If it does not, we push a window/showMessage notification warning the user. Probably as a warning and not an error dialogue though.

**Comment by andyw8** [comment]
Related: https://github.com/Shopify/ruby-lsp/pull/2092

**Comment by andyw8** [comment]
I was thinking that we could still do something similar: If the users selects a formatter that isn't available due to a lack of gem (e.g. `rubyfmt`), we can show a suitable notification.
