### ISSUE TITLE
VsCodium: Error code -32097 can't connect to the server 

### ISSUE THREAD

**Issue by Raxelgrande** [Shopify/ruby-lsp#1216]
### Ruby version

3.0.6-1

### Code snippet

The output by ruby-lsp. All i did was search for it and install it on my system 

Ruby LSP> Checking if asdf is available on the path with command: /bin/bash -ic 'asdf --version'
Ruby LSP> Checking if chruby is available on the path with command: /bin/bash -ic 'chruby --version'
Ruby LSP> Checking if rbenv is available on the path with command: /bin/bash -ic 'rbenv --version'
Ruby LSP> Checking if rvm is available on the path with command: /bin/bash -ic 'rvm --version'
Ruby LSP> Discovered version manager none
Ruby LSP> Trying to activate Ruby environment with command: /bin/bash -ic 'ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /home/lucas/Programas/Codium/Ruby
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 19:35:57] Server process exited with code 127.
[Error - 19:35:57] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 19:35:57] Connection to server got closed. Server will restart.
true
[Error - 19:35:57] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 19:35:57] Server process exited with code 127.
[Error - 19:35:57] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 19:35:57] Connection to server got closed. Server will restart.
true
[Error - 19:35:57] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error restarting the server: Pending response rejected since connection got disposed
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 19:35:57] Server process exited with code 127.
[Error - 19:35:57] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 19:35:57] Connection to server got closed. Server will restart.
true
[Error - 19:35:57] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:35:57] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 19:35:57] Server process exited with code 127.
[Error - 19:35:57] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 19:35:57] Connection to server got closed. Server will restart.
true
[Error - 19:35:57] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:35:57] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 19:35:57] Server process exited with code 127.
[Error - 19:35:57] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:35:57] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 19:35:57] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 19:35:57] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

### Description

Using vscodium 1.84.2.23319-1 in Arch Linux, provided via the AUR.
The only other extension installed is Dracula Official 

### Expected output

That everything works as intended.

**Comment by vinistock** [comment]
Thank you for the bug report. Based on this line

> /bin/sh: línea 1: ruby-lsp: orden no encontrada

It looks like this is the same issue as https://github.com/Shopify/vscode-ruby-lsp/issues/901. Can you try opening VS Code from the terminal with `code .` to see if the issue goes away?

If it does, then it's certainly related to that bug with VS Code not finding the correct default shell.

**Comment by Raxelgrande** [comment]
I tried to launch it from the terminal by typing vscodium. No difference, it gives the same error code and no kind of output, not even debug information in the terminal running vscodium 

Ruby LSP> Checking if asdf is available on the path with command: /bin/bash -ic 'asdf --version'
Ruby LSP> Checking if chruby is available on the path with command: /bin/bash -ic 'chruby --version'
Ruby LSP> Checking if rbenv is available on the path with command: /bin/bash -ic 'rbenv --version'
Ruby LSP> Checking if rvm is available on the path with command: /bin/bash -ic 'rvm --version'
Ruby LSP> Discovered version manager none
Ruby LSP> Trying to activate Ruby environment with command: /bin/bash -ic 'ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' inside directory: /home/lucas/Programas/Codium/Ruby
[Error - 10:03:42] Client Ruby LSP: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 10:03:42] Client Ruby LSP: connection to server is erroring.
write EPIPE
[Error - 10:03:42] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Hd.shutdown (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:41:8468)
	at Hd.stop (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:41:8047)
	at Hd.stop (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:44:38188)
	at Hd.handleConnectionError (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 10:03:42] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:03:42] Ruby LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
Error restarting the server: write EPIPE
[Info  - 10:03:42] Connection to server got closed. Server will restart.
true
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 10:03:42] Server process exited with code 127.
[Error - 10:03:42] Client Ruby LSP: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 10:03:42] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Hd.shutdown (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:41:8468)
	at Hd.stop (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:41:8047)
	at Hd.stop (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:44:38188)
	at Hd.handleConnectionError (/home/lucas/.vscode-oss/extensions/shopify.ruby-lsp-0.4.13-universal/out/extension.js:43:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 10:03:42] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:03:42] Ruby LSP client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 10:03:42] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 10:03:42] Connection to server got closed. Server will restart.
true
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 10:03:42] Server process exited with code 127.
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 10:03:42] Server process exited with code 127.
[Error - 10:03:42] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:03:42] Connection to server got closed. Server will restart.
true
[Error - 10:03:42] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 10:03:42] Server process exited with code 127.
[Error - 10:03:42] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:03:42] Connection to server got closed. Server will restart.
true
[Error - 10:03:42] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:03:42] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/bin/sh: línea 1: ruby-lsp: orden no encontrada
[Error - 10:03:42] Server process exited with code 127.
[Error - 10:03:42] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:03:42] The Ruby LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:03:42] Ruby LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:03:42] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by vinistock** [comment]
It does seem like something changed given that I no longer see the issue related to `/bin/sh`. The right shell is probably being selected now, but we need to understand why the server is failing to boot.

If you run `ruby-lsp` inside your project from the terminal (no bundle exec), do you get any errors?

**Comment by froyo-naux** [comment]
I can repeat issue,when remove gem bin from $PATH
![image](https://github.com/Shopify/ruby-lsp/assets/1060783/44336e90-ee69-4bb9-a895-43ba6a7536e6)

**Comment by vinistock** [comment]
@Raxelgrande I took another look at this issue and I think I now understand the issue. You're not using any version manager, but rather installing Ruby through Homebrew. With no version manager, we don't perform automatic detection of the Ruby version, but on the latest v0.7.0 version of the extension you can manually select your Ruby installation, which should fix your issue.

@vladhadzhiyski your issue seems to be a different one, but if the problem is that `rbenv` is not recognized inside of the integrated terminal, then that is unrelated to the Ruby LSP and likely an issue with your shell configurations.
