### ISSUE TITLE
Support things like Hover and Completion in typed: false files.

### ISSUE THREAD

**Issue by SeanKG** [Shopify/ruby-lsp#1240]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

We have a large rails codebase where we have added sorbet but are still `typed: false` in most places for the time being. In any `typed: false` file you get no support for hover / completion from either LSP/plugin currently.

### Description

I'm suggesting to detect `typed: false` and still return responses for hover and completion in those files instead of only checking the project for Sorbet as a dependency and returning nothing in these requests.

### Implementation

I've looked around in the codebase a bit and I'd be happy to submit a PR when I have some extra time. Looks like we'd just need to pass the document to these requests to add this logic.

**Comment by vinistock** [comment]
This was completed! Thanks for the contribution.
