### ISSUE TITLE
Investigate why `to_spec` is nil for prerelease gems

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#1246]
See https://github.com/Shopify/ruby-lsp/pull/1242

This can be reproduced on the `irb` repo with `gem "reline", "0.5.0.pre.1"`

**Comment by vinistock** [comment]
Amazing, @kimesf! Thank you very much for investigating, fixing the bug and then bringing back the context.

I think we can close this issue then and direct anyone who still has the problem to upgrade `rubygems` and `bundler`. @andyw8 do you agree?

**Comment by kimesf** [comment]
> 👍 We'll keep the fix in #1242, and can remove once we are confident people are on a newer rubygems.

Just to point it out, there were multiple fixes for the issue (#1159, #1242 and #1326).
