### ISSUE TITLE
I have a problem when  I start a proyect of rails 

### ISSUE THREAD

**Issue by Saimon1520** [Shopify/ruby-lsp#1270]
### Ruby version

ruby 3.2.2

### Code snippet

rails s

### Description

When I write the code rails s in a protect it shows an error and I don't know the problem.

this is the error:

PS C:\Users\saimo\Documents\Feed_Back_Me\feedbackme-development> rails s
C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "C:/Users/saimo/Documents/Feed_Back_Me/feedbackme-development":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:259:in `find_file'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:27:in `root'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:246:in `app_config_path'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:273:in `settings'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/feature_flag.rb:21:in `block in settings_method'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:250:in `find_gemfile'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:33:in `default_gemfile'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:39:in `default_lockfile'
        from C:/Users/saimo/.local/share/gem/ruby/3.2.0/gems/bundler-1.17.3/lib/bundler.rb:334:in `default_lockfile'
        from C:/Users/saimo/Documents/Feed_Back_Me/feedbackme-development/bin/spring:10:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>

this is the gemfile lock:

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.7.2)
      actionpack (= 5.0.7.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.7.2)
      actionview (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.7.2)
      activesupport (= 5.0.7.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.7.2)
      activesupport (= 5.0.7.2)
      globalid (>= 0.3.6)
    activemodel (5.0.7.2)
      activesupport (= 5.0.7.2)
    activerecord (5.0.7.2)
      activemodel (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      arel (~> 7.0)
    activesupport (5.0.7.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    arel (7.1.4)
    bcrypt (3.1.16)
    bindex (0.8.1)
    bootstrap-email (0.3.4)
      actionmailer (>= 3)
      nokogiri (~> 1.6)
      premailer-rails (~> 1.9)
      rails (>= 3)
    builder (3.2.4)
    byebug (11.1.3)
    caxlsx (3.0.2)
      htmlentities (~> 4.3, >= 4.3.4)
      mimemagic (~> 0.3)
      nokogiri (~> 1.10, >= 1.10.4)
      rubyzip (>= 1.3.0, < 3)
    caxlsx_rails (0.6.2)
      actionpack (>= 3.1)
      caxlsx (>= 3.0)
    chunky_png (1.3.12)
    climate_control (0.2.0)
    clipboard-rails (1.7.1)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.7)
    crass (1.0.6)
    css_parser (1.10.0)
      addressable
    debase (0.2.4.1)
      debase-ruby_core_source (>= 0.10.2)
    debase-ruby_core_source (0.10.10)
    devise (4.7.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    erubis (2.7.0)
    execjs (2.7.0)
    ffi (1.13.1)
    figaro (1.2.0)
      thor (>= 0.14.0, < 2)
    font-awesome-rails (4.7.0.5)
      railties (>= 3.2, < 6.1)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    htmlentities (4.3.4)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    jbuilder (2.10.0)
      activesupport (>= 5.0.0)
    jquery-datatables (1.10.20)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.7.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    method_source (1.0.0)
    mime-types (3.3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2020.1104)
    mimemagic (0.3.5)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.2)
    nio4r (2.5.3)
    nokogiri (1.10.10)
      mini_portile2 (~> 2.4.0)
    orm_adapter (0.5.0)
    paperclip (6.1.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      mime-types
      mimemagic (~> 0.3.0)
      terrapin (~> 0.6.0)
    pg (0.19.0)
    pivot_table (1.0.0)
    popper_js (1.16.0)
    premailer (1.15.0)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.11.1)
      actionmailer (>= 3)
      premailer (~> 1.7, >= 1.7.9)
    public_suffix (4.0.6)
    puma (3.12.6)
    rack (2.2.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.7.2)
      actioncable (= 5.0.7.2)
      actionmailer (= 5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      activemodel (= 5.0.7.2)
      activerecord (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      bundler (>= 1.3.0)
      railties (= 5.0.7.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.0.7.2)
      actionpack (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (13.0.1)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rqrcode (1.1.2)
      chunky_png (~> 1.0)
      rqrcode_core (~> 0.1)
    rqrcode_core (0.1.2)
    ruby-debug-ide (0.6.1)
      rake (>= 0.8.1)
    rubyzip (2.3.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    terrapin (0.6.0)
      climate_control (>= 0.0.3, < 1.0)
    thor (1.0.1)
    thread_safe (0.3.6)
    tilt (2.0.10)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    uglifier (4.2.0)
      execjs (>= 0.3.0, < 3)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-email
  byebug
  caxlsx
  caxlsx_rails
  clipboard-rails
  coffee-rails (~> 4.2)
  debase (~> 0.2.2)
  devise
  figaro
  font-awesome-rails
  jbuilder (~> 2.5)
  jquery-datatables
  jquery-rails
  listen (~> 3.0.5)
  paperclip
  pg (~> 0.19.0)
  pivot_table
  popper_js (= 1.16.0)
  puma (~> 3.0)
  rails (~> 5.0.0)
  rqrcode
  ruby-debug-ide (~> 0.6.1)
  rubyzip
  sass-rails (~> 5.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console

BUNDLED WITH
   1.17.3

### Expected output

I expected the local IP of for watch the project.

**Comment by Saimon1520** [comment]
I am trying to open a project for the first time and I have tried to install the correct version of ruby several times and in the same way when I try to run the code in visual code it does not work, I hope you understand since I know almost nothing about this.

**Comment by andyw8** [comment]
Yes, as the above suggests, please try update to a newer Bundler version. The one you're using (1.17.3) is over 5 years old.
