### ISSUE TITLE
Exclude gem symbols from appearing in global symbol search

### ISSUE THREAD

**Issue by andyjeffries** [Shopify/ruby-lsp#1277]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

When I use VS Code's "Go to file..." with a symbol prefix, it lists all gems as well as my code. I'd rather not jump to symbols in my gems.  I discussed with @vinistock on Twitter and he asked me to raise an issue https://twitter.com/vinistock/status/1742528125135651264

### Description

A configuration option to disable indexing all gems, leaving just our application code in the index.

**Comment by andyw8** [comment]
I'm not sure if it's possible, but ideally we'd still want index those files (so that features such as Go To Definition are still available), but have the option to exclude them when searching for a symbol.

**Comment by paracycle** [comment]
As @andyw8 said above, indexing is an orthogonal concern to which indexed symbols are made available in the global symbol table. My understanding is that this issue is asking for the global symbol table to not have gem symbols (or at least, make them lower priority), so I updated the title to make the ask explicit.

**Comment by gmcabrita** [comment]
I'm using the Zed editor and in one of my projects the `workspace/symbol` query returns up to 3000 results when querying for something like `person`. The resulting JSON has 800k characters. `workspace/symbol` should probably not return that many results.

I have been pretty much forced to ignore every every single gem my project uses[1][2]. I find go/click to definition to be useful for jumping from a file to the definition of a method defined in a gem, but I don't find much use in having them listed in the `workspace/symbol` results.

[1] [.index.yml](https://gist.github.com/gmcabrita/a10fe03d12a8aa95eef1f5b84cf450ab)
[2] [.index.yml updater](https://gist.github.com/gmcabrita/b0912beaa6a1deee016e9e57fb160402)

**Comment by gmcabrita** [comment]
I'm using the Zed editor and in one of my projects the `workspace/symbol` query returns up to 3000 results when querying for something like `person`. The resulting JSON has 800k characters. `workspace/symbol` should probably not return that many results.

I have been pretty much forced to ignore every every single gem my project uses[1]. I find go/click to definition to be useful for jumping from a file to the definition of a method defined in a gem, but I don't find much use in having them listed in the `workspace/symbol` results.

[1] [.index.yml updater](https://gist.github.com/gmcabrita/b0912beaa6a1deee016e9e57fb160402)
