### ISSUE TITLE
Signature Help handler - context param can be nil

### ISSUE THREAD

**Issue by CKolkey** [Shopify/ruby-lsp#1284]
### Ruby version

3.2.2,3.3.0

### Description

Currently using https://github.com/ray-x/lsp_signature.nvim neovim plugin to show signature help, and it seems that ruby-lsp expects a context param (https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/executor.rb#L176) that lsp_signature isn't passing: https://github.com/ray-x/lsp_signature.nvim/blob/master/lua/lsp_signature/init.lua#L686-L702

All thats being sent is `vim.lsp.util.make_position_params()`, which returns
```
{
  position = {
    character = 9,
    line = 175
  },
  textDocument = {
    uri = "file:///Users/cameron/.local/share/mise/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb"
  }
}
```

According to the lsp spec for `signatureHelpParams` (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelpParams), context is _optional_, and should be opt-in by the client:
```
/**
	 * The signature help context. This is only available if the client
	 * specifies to send this using the client capability
	 * `textDocument.signatureHelp.contextSupport === true`
	 *
	 * @since 3.15.0
	 */
```

However, because ruby-lsp treats this param as non-optional, the following NoMethodError is raised:

```
lsp_signatur handler RPC[Error] code_name = InternalError, message = "#<NoMethodError: undefined method `[]' for nil:NilClass>" data = {
  backtrace = "

~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:254:in `signature_help'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11176/lib/types/private/methods/_methods.rb:274:in `bind_call'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11176/lib/types/private/methods/_methods.rb:274:in `block in _on_method_added'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:176:in `run'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/executor.rb:26:in `execute'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:135:in `block (2 levels) in new_worker'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:123:in `loop'
~/.local/share/mise/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.13.2/lib/ruby_lsp/server.rb:123:in `block in new_worker'

",
  errorClass = "NoMethodError",
  errorMessage = "undefined method `[]' for nil:NilClass"
}
```

(I formatted the backtrace for easier reading)

### Expected output

ruby-lsp should be able to handle when this optional parameter isn't passed.

**Comment by CKolkey** [comment]
Dug into this a bit more: 
- Ruby-lsp expects a context param (https://github.com/ray-x/lsp_signature.nvim/blob/master/lua/lsp_signature/init.lua#L718-L730) that lsp_signature isn't passing: https://github.com/ray-x/lsp_signature.nvim/blob/master/lua/lsp_signature/init.lua#L718-L730


Given that, it seems equally plausible that the neovim plugin is in the wrong here, in which case we can close this. I'm not sure what the LSP spec specifies wrt that part of the params.

**Comment by borisrorsvort** [comment]
😍  so fast! Thanks @vinistock
