### ISSUE TITLE
debugger silently stops just after starting without any log in visual studio code

### ISSUE THREAD

**Issue by prateeksen** [Shopify/ruby-lsp#1289]
### Ruby version

3.0.5

### Code snippet

launch.json

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "ruby_lsp",
      "request": "launch",
      "name": "Debug program",
      "program": "rails server"
    },
    {
      "type": "ruby_lsp",
      "name": "Debug script",
      "request": "launch",
      "program": "bundle exec rails server "
    },
    {
      "type": "ruby_lsp",
      "name": "Debug test",
      "request": "launch",
      "program": "ruby -Itest ${relativeFile}"
    },
    {
      "type": "ruby_lsp",
      "name": "Attach debugger",
      "request": "attach"
    }
  ]
}
```

### Description

I am facing issue in one rails application and in another rails app debugger is running fine. Not sure why this is exiting silently.
Please provide info how can i enable DEBUG logging and know what is wrong with debugger.
I tried to manually run the debugger command, Here is the output for that:
```
psen@X1F37C2FY6 elastic-search-api % bundle exec rdbg --open --command --sock-path=/tmp/ruby-lsp-debug-sockets/ruby-debug-elastic-search-api-10.sock -- rails server
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-lsp-debug-sockets/ruby-debug-elastic-search-api-10.sock)
DEBUGGER: wait for debugger connection...
```

### Expected output

Debugger should run smoothly for rails application

**Comment by vinistock** [comment]
Thank you for the bug report! In the latest version of the extension, we made a change that allows displaying backtraces from the debug server inside the debug console.

Could you please try again and verify if the debug console has more information and what failed?
