### ISSUE TITLE
Correct configuration file from general index.yml in root of project with relocating it to already existing .ruby-lsp folder.

### ISSUE THREAD

**Issue by ShPakvel** [Shopify/ruby-lsp#1295]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

It should eliminate confusion and do not block general file name for specific purposes of projects.

### Description

Currently configuration file `.index.yml` has too general name relative to root of a project and thus do not represent purpose properly. Described in this Readme chapter https://github.com/Shopify/ruby-lsp#configuring-code-indexing.  

There is `.ruby-lsp` folder that is created in root of a project. I think this `.index.yml` file should be stored and read from that folder.

**Comment by andyw8** [comment]
We're discussing if this is the right approach: https://github.com/Shopify/ruby-lsp/pull/1434#issuecomment-2018723331
