### ISSUE TITLE
`Error running diagnostics: undefined method `anything' for module T`

### ISSUE THREAD

**Issue by jherdman** [Shopify/ruby-lsp#1322]
### Operating System

macOS Sonoma 14.3

### Ruby version

3.3.0

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

asdf

### Description

As of late I see the following error when using this extension:

```
Error running diagnostics: undefined method `anything' for module T
```

There are no further details provided.

I've tried:

1. Reinstalling the extension
2. Restarting the extensions
3. Stopping and starting the extension
4. Removing all user and workspace settings pertaining to this extension

Unfortunately nothing seems to work.

**Comment by jherdman** [comment]
Unfortunately I'm using 0.5.8, the latest release as of 5 days ago

**Comment by andyw8** [comment]
The latest version of the gem is 0.13.4: https://rubygems.org/gems/ruby-lsp/versions

**Comment by andyw8** [comment]
No worries, I already moved it.

**Comment by jherdman** [comment]
In case anyone else runs into this I've tracked the problem down to an old version of sorbet-runtime in our Gemfile.lock. We were running 0.5.10626. Upgrading to 0.5.11226 fixes the issue.

**Comment by andyw8** [comment]
In v0.13.4 we [bumped](https://github.com/Shopify/ruby-lsp/commit/b1c070207e0c84c2fb334da844bad197670a5e6f) the minimum sorbet-runtime version so if you're on that version of the gem you shouldn't run into this.
