### ISSUE TITLE
Slack link not valid anymore

### ISSUE THREAD

**Issue by beauraF** [Shopify/ruby-lsp#1360]
### Ruby version

3.3.0

### Description

Hello 👋

Thanks a lot for your work!

Sorry, I created a bug because it seemed the easiest way to report it. The slack link in the README.md is not valid anymore, and will maybe need an update.

### Expected output

Slack link is valid

**Comment by andyw8** [comment]
Here's an update link which doesn't expire:

https://join.slack.com/t/ruby-dx/shared_invite/zt-2c8zjlir6-uUDJl8oIwcen_FS_aA~b6Q

(I'll update the README)

**Comment by beauraF** [comment]
Fixed by https://github.com/Shopify/ruby-lsp/commit/b043380cf1b319add934dc5327246b720a5fcb1a. Thanks @andyw8 🙏
