### ISSUE TITLE
Removed the Listener class but didn't updated ADDON.md

### ISSUE THREAD

**Issue by domingo2000** [Shopify/ruby-lsp#1372]
### Ruby version

3.3.0

### Code snippet

```
module RubyLsp
  module MyAddon
    class CodeLens < ::RubyLsp::Listener
    end
  end
end
```

### Description

I saw that when you bump version 0.14.0 the `Listener` class was removed but the Addons documentation was not updated, now i don't know how to create my own listeners with the new doc, because when I inherit form `::RubyLsp::Listener` the code breaks.

### Expected output

Expected a correct doc for the ADDON file

**Comment by andyw8** [comment]
Hi @domingo2000, the docs are being updated in https://github.com/Shopify/team-ruby-dx/issues/1124 and should be merged soon.
