### ISSUE TITLE
Add Shoulda context addon in addons docs

### ISSUE THREAD

**Issue by domingo2000** [Shopify/ruby-lsp#1373]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Hi!, As you mentioned in [ruby-lsp-rails #244](https://github.com/Shopify/ruby-lsp-rails/issues/244) i wanted to have support for shoulda context in my tests. You said that it should be better to have an addon, so here you have `ruby-lsp-shoulda-context` 👍🏻 .

## :link: [Ruby Lsp Shoulda Context](https://github.com/domingo2000/ruby-lsp-shoulda-context)
The addon permits to run, run in terminal and debug [Shoulda Context](https://github.com/thoughtbot/shoulda-context) like DSL syntax for tests. This improves a lot the development experience when working with this kind of test setups in plain ruby projects or in rails.

It in early stage of development, but it support what i think are a lot of use cases, so it would be nice if you give it a try, and if  you like, you could add it to the ADDONS readme 😄.

### Description

The addon currently parse the contexts blocks and should blocks similarly as Rspec addon does. It reads the workspace to see if its using pure ruby, bundler or rails to run the commands in the correct way. You can see the currently implemented features in the repository.

### Implementation

Just add the addon in your Gemfile :rocket:

Note: The only inconvinience i encounter implementing the addon is that if i need to parse the main class to, i can't access to the previously parsed TestItem from the original `ruby-lsp` so the `CodeLens` got duplicated, but is just a detail.

**Comment by domingo2000** [comment]
yeah, thats what i have created, here is the repo for the new gem https://github.com/domingo2000/ruby-lsp-shoulda-context, the idea was to included in your extensions docs if you find it useful

**Comment by vinistock** [comment]
Sorry, I misunderstood the issue. The team talked and agreed that, at this time, we don't want to keep a list of all available addons as that would create a significant maintenance cost (having to review code, ensure no entries are unmaintained, etc).

We will add a link pointing to `rubygems.org` for entries prefixed with `ruby-lsp` instead.
