### ISSUE TITLE
Show Prism warnings in diagnostics

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1406]
We currently show Prism errors as diagnostics, but we don't do the same for warnings. We should definitely surface warnings as diagnostics too since they provide valuable information about the code.

**Comment by snutij** [comment]
Hello @vinistock 👋 I would be happy to help on this.

[Prism warnings](https://github.com/ruby/prism/blob/0727b5d9ca2a3b0d50a7a9781f8f4e7e939eb824/src/diagnostic.c#L305-L313) should be merged with Rubocop diagnostics, if it's present? They are often duplicate but seems legit to have both 🤔 

WDYT?

**Comment by vinistock** [comment]
I think it should be fine to merge with RuboCop diagnostics. In fact, if RuboCop gets support for Prism as the backend (which I understand is the desired goal), then it doesn't even make sense for RuboCop to have these rules. They should come from the parser.
