### ISSUE TITLE
Support document symbol for Rakefile

### ISSUE THREAD

**Issue by st0012** [Shopify/ruby-lsp#1412]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Document symbol could be very helpful for navigating between tasks inside a large Rakefile.

### Description

Ruby LSP can add task declarations as document symbols so VS Code users can use `Go to Symbol` to quickly search and jump between task definitions.

**Comment by thomasmarshall** [comment]
Hey! I saw the `help-wanted` label and thought I might [give it a go](https://github.com/Shopify/ruby-lsp/pull/1444), hope that's OK 🙂
