### ISSUE TITLE
Formatting sometimes hangs indefinitely

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#146]
We have received reports of RuboCop formatting hanging indefinitely. Notice that it does not seem like the issue is performance on large files, which is a separate issue.

It seems that somehow the LSP either gets stuck or returns something invalid to VS Code (which in turn makes the "Running Ruby LSP formatter" dialogue never disappear).

Both reports we have received mentioned that there's nothing in the output tab, other than the default message of "Starting the Ruby LSP...".

### Suggestion

We should consider making [format on save](https://github.com/Shopify/vscode-shopify-ruby/blob/2fe3903426724bdb351f2e207805fc7af788b417/src/configuration.ts#L27) `false` in the extension pack, while we work on improving the situation.

### Suggestion on how to debug

The difficult part of this is reproducing the issue, given that we do not know what causes it. Some possible steps:
- Make sure `"ruby lsp.trace.server": "messages"` is turned on in `.vscode/settings.json`
- When formatting hangs, check the output tab and see if any other requests are still being made. If you manage to get requests going for any file, then it's unlikely that the server is stuck - which probably means we returned something invalid to VS Code (or didn't return anything when it was expecting something)

### Definition of done

This ticket is considered closed when the root cause of the bug (hanging formatting) is identified and addressed.

**Comment by st0012** [comment]
> Make sure "ruby lsp.trace.server": "messages" is turned on in .vscode/settings.json

Is this 

```
    "ruby.lsp.trace.server": true,
```

or 

```
    "[ruby]": {
        "lsp.trace.server": true,
```

VSCode says the former is unknown and the later is not per-language setting 🤔
