### ISSUE TITLE
Support using the LSP with multiple projects in the same VS Code instance

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1510]
VS Code allows opening multiple projects simultaneously in the same instance. For these scenarios, we can't spawn the Ruby LSP at the top level.

Each project may be using different versions of the LSP or RuboCop and may also have different RuboCop configurations. For these scenarios, it may be necessary to spawn multiple servers, one for each project.

**Comment by dominicgoulet** [comment]
> You need to open `client` and `server` as separate workspaces. Don't open the top level folder, open `client` and then add `server` as a second workspace.

If anyone had missed that comment like I did, this is the answer you are looking for.
