### ISSUE TITLE
Option to not index default gems and locked gems

### ISSUE THREAD

**Issue by cosmicac** [Shopify/ruby-lsp#1530]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

First of all, thank you to all the maintainers for your hard work. I've been using `ruby-lsp` for a little bit now and it's been mostly great.

I was debugging the indexing speed of my `ruby-lsp` setup, and ended up walking through [the code here in the `ruby_indexer`](https://github.com/Shopify/ruby-lsp/blob/8ac98fe27c1a8f351eb070317df2dd03c6bb31c2/lib/ruby_indexer/lib/ruby_indexer/configuration.rb#L61). I noticed that in my case, over 50% (4620/9036) of files indexed were from "default gems" and "locked gems".

Most of these gems I don't use on a regular basis since I work in a big monorepo. There's a smaller set of gems that I do use on a regular basis for which it would be helpful to have LSP analysis on.

It would be nice to have an option to not index the "default gems" and "locked gems" _except_ for a specific list of gems that I specify.

### Description

The feature would be an option to not index default gems/locked gems, except for a user provided list of gems.

### Implementation

There could be flag(s) to toggle on/off default and locked gem indexing in `.index.yml`

```yaml
  - include_default_gems: false
  - include_locked_gems: false
```

And anything specified in `included_gems` would be included no matter what.

**Comment by andyw8** [comment]
@cosmicac I'm curious, how does does indexing currently take for your repo?

**Comment by cosmicac** [comment]
@andyw8 Measured by the [progress output here](https://github.com/Shopify/ruby-lsp/blob/ab2c4faf2d749e1f614f0180e6def843c14f4252/lib/ruby_lsp/executor.rb#L444):

* With all default and locked gems included:
  - 5802ms
* Without default and locked gems:
  - 1978ms
  
 So, there is a difference. However, I do understand the indexing runs in another thread, so it's not a huge developer experience barrier in that regard.

**Comment by vinistock** [comment]
If the concern is indexing speed, then I think it's more important to explore caching gem indices https://github.com/Shopify/ruby-lsp/issues/1009 and directories https://github.com/Shopify/ruby-lsp/issues/1040, which will likely provide significantly higher gains.

Can you also explain your workflow a little bit? What causes you to close and re-open NeoVim? I assume you don't open NeoVim and keep the same one running for long periods of time. Is that accurate?

It's useful for us to understand the workflow since it may not match what we experience normally in VS Code. Typically, unless we're switching branches, pulling from git or doing some other operation that may result in a server restart, the server process runs for a long time and so an indexing time of 6 seconds doesn't really make a difference.

**Comment by cosmicac** [comment]
Oh yeah, caching would be cool, makes sense that that's a higher priority for performance improvements.

> Can you also explain your workflow a little bit? What causes you to close and re-open NeoVim? I assume you don't open NeoVim and keep the same one running for long periods of time. Is that accurate?

Yes - that is the case. I typically close neovim whenever I'm done with a "session" of reading/writing code (can be anywhere from a few seconds/minutes to hours). I also frequently open several neovim instances side by side in different terminal tabs.

**Comment by vinistock** [comment]
The team discussed this and we decided to not add the new configuration options at this time. Improving indexing performance is indeed a goal of ours, but we feel like the configuration option is not the right approach for a few reasons:

1. We want the LSP to require minimal configuration to work and only offer customization options for things that really are necessary. This doesn't quite fit into that and it's already possible to do it if you simply exclude every single default gem
2. Indexing configurations can be tricky for users to understand as not everybody might realize their connection to features. For example, someone could exclude default gems, but then not understand why trying to go to definition on a default gem's declaration isn't working
3. With configuration files, there's always a risk of people just copying examples from other projects and having these options spread could result in sub-optimal experiences for users

Thank you for the suggestion!

**Comment by cosmicac** [comment]
That all makes sense. Thanks for discussing with the team, looking forward to any future improvements.
