### ISSUE TITLE
LSP not working in vs code

### ISSUE THREAD

**Issue by distantforest1** [Shopify/ruby-lsp#1696]
### Operating System

Windows Home 10

### Ruby version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

### Project has a bundle

- [ ] Has bundle

### Ruby version manager being used

no manager

### Description

I just installed with RubyInstaller 3.2.2. It doesn't do anything at all, no error, no autocomplete to jump to anything.

**Comment by nowshad-hossain-rahat** [comment]
It's still not giving any autocompletion, auto suggest, intellisense, hovering over any variable or function does nothing and even no errors on the output

Ruby Version: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
Garuda Linux

**Comment by andyw8** [comment]
@nowshad-hossain-rahat Please create a separate issue.
