### ISSUE TITLE
Failed to activate rbenv environment: command not found: rbenv

### ISSUE THREAD

**Issue by n-studio** [Shopify/ruby-lsp#1720]
### Operating System

macOS 14.0

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

I'm not sure what I'm doing wrong here. I feel that my setup is a very standard one.

Install rbenv via homebrew on zsh
Set the Ruby Lsp Ruby Version Manager to rbenv
Create a new Rails project
Open it with VSCode 1.83.1

```
Failed to activate rbenv environment: Command failed: /bin/zsh -ic 
'rbenv exec ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' 
/Users/n-studio/.zshrc:108: command not found: rbenv zsh:1: command not found: rbenv
```

Line 108 of my `.zshrc` : `eval "$(rbenv init - zsh)"`

Running `/bin/zsh -ic 'rbenv exec ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"'` in VSCode's terminal returns `RUBY_ENV_ACTIVATE{"RBENV_VERSION":"3.2.2",...`

**Comment by ddatdt12** [comment]
I have the same issue. I did what @n-studio said but it doesn't work. Is there anyone to help me fix this.
MacOS M3.

![Image](https://github.com/user-attachments/assets/0bbf36d6-90ca-449d-95b2-a357f6a672a8)
