### ISSUE TITLE
How do you disable rubocop?

### ISSUE THREAD

**Issue by dillonhafer** [Shopify/ruby-lsp#1735]
How do you disable rubocop? VSCode installed this by itself and now it conflicts with the standard gem. I want standard to provide the rubocop rules not this extension.

**Comment by Nakilon** [comment]
Where is this "language status item" thing? The link is rotten.

**Comment by andyw8** [comment]
@Nakilon that is part of the VS Code extension, it would not appear in other editors.

The formatting you are seeing may be from Sublime itself, or some other package.

**Comment by Nakilon** [comment]
> may be from Sublime itself

No, it's a hovering balloon saying something like "... (Rubocop/Style..." all over the place. The only other LSP I could make work for me yesterday was solargraph and the same feature was possible to disable via "diagnostics" (it's not really even enabled by default IIRC), but with ruby-lsp enabled after a second source file is full of these notifications.
