### ISSUE TITLE
Editing a large file can leave old rubocop diagnostic hints

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1756]
### Operating System

Linux

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Quickly editing a file can, depending on your system speed, result in showing outdated rubocop diagnostics. Reproducing this should be pretty easy by creating a file with a bunch of lines. In my example video below there are about 5000 lines which I just copy-pasted from somewhere to make rubocop think a while longer.

[Peek 2024-03-05 16-41.webm](https://github.com/Shopify/vscode-ruby-lsp/assets/14981592/d23e0989-7af2-49f9-b38c-f652c3f65b16)

**Comment by Earlopain** [comment]
Still relevant

**Comment by Earlopain** [comment]
Yeah, offloading it to a different request seems like a nice idea. Though thinking about it again, I don't think a debounce is really the way to go. On my current machine (which is rather more powerful than the mini-pc I occasionally use) the request to rubocop finishes instantly and I feel like any delay would be a downgrade. Especially for what I would consider normal-sized files I never run into this.

----------

Something else comes to mind: push the message to the queue instantly. Would it be possible to then dedupe the queue so that always only the most recent request is present and all others that potentially got added before are discarded?

That would mean that there will be at most two relevant events simultaneously for a file: the one currently running and the one waiting to run after that.

Does that sound like a good idea at all?

**Comment by Earlopain** [comment]
This is still an issue

**Comment by vinistock** [comment]
We're now disabling semantic highlighting and diagnostics for very large files, so I believe this issue ended up going away as a result.
