### ISSUE TITLE
Debugger cannot attach to running process

### ISSUE THREAD

**Issue by gabrielso** [Shopify/ruby-lsp#1759]
### Operating System

Windows 11 - WSL 2 (Ubuntu) / Dev Containers

### Ruby version

3.3.0

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

no manager

### Description

Running VSCode on Windows / WSL 2 with Dev Containers, the extension is unable to find the socket created by the `rdbg` process.

My Dockerfile has the following `CMD` directive:
```docker
CMD [ "bundle", "exec", "rdbg", "-O", "-n", "-c", "--", "bin/rails", "s", "--early-hints", "-b", "0.0.0.0" ]
```

It starts the server correctly and logs the socket creation (see first line of Container log):
![container_server_start](https://github.com/Shopify/vscode-ruby-lsp/assets/15992/4b05541f-0026-444a-be45-edc698f187b9)

But when I start the debugger I see the message:
![no_debuggee](https://github.com/Shopify/vscode-ruby-lsp/assets/15992/473e460d-f304-40ea-8d1c-7dc99feef45d)

The debugger is working in other contexts like for instance debugging a test case:
![attached_test_debug](https://github.com/Shopify/vscode-ruby-lsp/assets/15992/36f04dc9-4d1c-4a59-a7ae-3d8be795127c)

From the error message, it seems like the `attachDebuggee` [function](https://github.com/Shopify/vscode-ruby-lsp/blob/0aa9e977d711a736f117446f40032bac2b4e57f8/src/debugger.ts#L181) is not finding the sock (I checked the file location in the container as well as permissions).

**Comment by snickell** [comment]
@gabrielso I don't know a lot about the debug gem, could you suggest how I might test that?

**Comment by LouisKottmann** [comment]
I can reproduce the issue as well, with a different system

Operating System: `Ubuntu 22.04`

Ruby version `3.2.4`

Project has a bundle: `Yes`

Ruby version manager being used: `rbenv`

I did a clean install of the shopify ruby extension pack

**Comment by LouisKottmann** [comment]
Actually I found a way to make it work, riiight before I was about to give up:

in launch.json specify the port of your rdbg like this:

```json
    {
      "type": "ruby_lsp",
      "name": "Attach debugger",
      "request": "attach",
      "debugServer": 4711
    }
```

and specify the same port when running rails server in the console:

```bash
bundle exec rdbg -O -n --port 4711 -c -- bin/rails server --early-hints
```
