### ISSUE TITLE
Extension is using a different shell then vcode

### ISSUE THREAD

**Issue by Goltergaul** [Shopify/ruby-lsp#1760]
### Operating System

mac os sonoma 14.3 (23D56)

### Ruby version

3.3.0

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

the lsp server can't start and gives this error:

Failed to activate rbenv environment: Command failed: /bin/sh -i -c 'rbenv exec ruby -rjson -e "STDERR.printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump({ env: ENV.to_h, ruby_version: RUBY_VERSION, yjit: defined?(RubyVM::YJIT) }))"' sh: no job control in this shell sh: rbenv: command not found

the issue is that the sh shell is not configured. in vcscode i use zsh as the default shell for the terminal

**Comment by reesericci** [comment]
Running into a similar thing on linux, upgrading to pre-release didn't help:

```
Failed to activate rbenv environment: Command failed: rbenv exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)' /bin/sh: line 1: rbenv: command not found
```

**Comment by vinistock** [comment]
I believe this issue is already fixed by https://github.com/Shopify/ruby-lsp/pull/1811, which decoupled the activation from the shell.
