### ISSUE TITLE
Please document what configuration multi-root workspaces actually expect

### ISSUE THREAD

**Issue by mattbnz** [Shopify/ruby-lsp#1761]
### Operating System

Ubuntu 23.10

### Ruby version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

no manager

### Description

I am attempting to use the LSP on a rails project within a subfolder of a multi-root vscode workspace (configured with a foo.code-workspace file). 

```
# /home/matt/foo/foo.code-workspace
{
	"folders": [
		{
			"path": "../../web/oncall"
		},
		{
			"path": "foo-fe"
		},
		{
			"path": "foo-be"
		},
		{
			"path": "../x"
		}
	],
	"settings": {}
}
```

The rails project is located at `/home/matt/foo/foo-be/front` (e.g. `/home/matt/foo/foo-be/front/Gemfile{,.lock}`. There is no other ruby code within the workspace. 

AFAIK the workspace is correctly configured (VS code works fine, other extensions work fine).

Whenever I start and try to use the LSP I receive an error stating:
```
Activating the Ruby LSP in /home/matt/foo/foo-be, but no lockfile was found. Are you using a monorepo setup?
```

Trying to debug this leads to a maze of documentation which doesn't actually state anywhere what the LSP is expecting.
* The error itself points to https://github.com/Shopify/vscode-ruby-lsp?tab=readme-ov-file#multi-root-workspaces which simply says to follow the VSCode guidelines and links to 
* https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces which documents only that you can add multiple folders and the format for doing so in the .code-workspace file, there is a small link to a more detailed page at
* https://code.visualstudio.com/docs/editor/multi-root-workspaces but still this page does not appear to describe any further requirements that I've missed.

So what's wrong? There's no way to tell because the linked docs only point to generic VSCode docs that don't specify any particular requirements other than the .code-workspace file containing a list of folders.

**Suggestion**
The sentence: "The Ruby LSP supports this use case out of the box as long as my_project contains configuration that follows [VS Code's guidelines](https://code.visualstudio.com/docs/editor/workspaces#_multiroot-workspaces) for multi-root workspaces."

specifically the "guidelines" reference, should be replaced wiht a more specific description of what guideline or expectation the LSP has that the reader will learn from the following the link.

**Comment by ytsmash** [comment]
> I completely remove the parent folder from the workspace configuration so that only the folder directly containing the rails project is within the workspace and none of it's parents are then the LSP starts correctly.

I seem to have run into the same problem.
For ruby-lsp to work properly, does the Gemfile have to be placed in the root of the workspace?

If so, it would be nice to be able to configure it to refer to Gemfiles placed in subdirectories, taking into account the case of usign ruby-lsp in monorepo.
