### ISSUE TITLE
LSP server crash can leave the extension in a stuck state

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1766]
### Operating System

Windows 11

### Ruby version

3.2.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

There are a few issues here I believe:

When using a custom gemfile and that gemfile gets updated the server crashes. The required gems are not installed => it can't start up anymore. This is documented in the readme:
> Note: when using this, gems will not be installed automatically and neither will ruby-lsp upgrades.

That error message isn't nicely surfaced however, you need to look in the extension output instead. Related to/Same as Shopify/ruby-lsp#1769 I would say.

However, through that crash the LSP client gets the internal state `startFailed`, which results in the Restart/Stop/Start commands not working even after the issues has been fixed. You have to perform a Window reload instead:

Restart (logged to output only):
> Error restarting the server: Client is not running and can't be stopped. It's current state is: startFailed

Start/Stop:
![grafik](https://github.com/Shopify/vscode-ruby-lsp/assets/14981592/456020fd-8686-4a96-a30c-79556f682c4d)

This happens because through some codepath they all end up calling `dispose`. This fails because there is no active connection:
https://github.com/microsoft/vscode-languageserver-node/blob/c0982bf544bab9600df223146dd75c93c9004dc3/client/src/common/client.ts#L1374-L1376

I looked through the public API but didn't immediatly find something that would hint to that being the case. The exposed client states are also more limited to than what vscode works with internally (`state` vs `$state` which is private)

**Comment by lpender** [comment]
I have this issue too in Os X. Uninstall / reinstall / restart computer didn't fix it.

**Comment by vinistock** [comment]
Unless I'm missing something, if you run the server in the background with `nohup`, you're basically using it to run `bundle install`.

The extension has no knowledge that the process is running from the terminal nor does it have ownership over the STDIN, STDERR and STDOUT pipes to communicate with it.

That's just running bundle install for the custom bundle with the background process and then the extension spawns a second process (owned by the extension) and boots the server.

If you inspect the processes for `ruby-lsp`, you'll likely have two running, no?
```shell
ps aux | grep ruby-lsp
```

**Comment by vinistock** [comment]
> I'm not sure how that's equivalent to it running bundle install, but the fact is that the extension did not work in VSCode before I did this.

As part of launching the server, we set up a custom bundle under the `.ruby-lsp` directory so that you don't have to include the gem in your application's dependencies and then we run bundle install.

If you run `ruby-lsp` in the terminal, the only thing that happens is you setup the custom bundle, run bundle install and then the server keeps waiting for input forever until its terminated (because the editor is not connected to it, so it never receives any requests).

Anyway, I'm glad it's fixed.

**Comment by vinistock** [comment]
I believe this has been fixed in recent versions of the extension. Please let us know if that's not the case.

**Comment by Earlopain** [comment]
Yes, I think you are right. I can't actually remember the last time I ran into this. I guess there was some critical part where it really shouldn't have crashed and not it doesn't.
