### ISSUE TITLE
Breakpoint exception

### ISSUE THREAD

**Issue by iOSGL** [Shopify/ruby-lsp#1768]
### Operating System

osx 13.0

### Ruby version

3.2.0

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rvm

### Description

When I click execute, the error is reported as shown below
![image](https://github.com/Shopify/vscode-ruby-lsp/assets/8703661/0c7c55d4-29e4-473d-bff1-ce1b22362ab8)

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/8703661/63429fbc-314b-4e0e-954e-d9596474574c)

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/8703661/cffb124a-0ce9-477f-9412-8d48239ad558)

![image](https://github.com/Shopify/vscode-ruby-lsp/assets/8703661/4f804668-af0f-485d-a6a1-f92f2a9ecfb9)

**Comment by vinistock** [comment]
Closing this for now. Please let us know if you're still having issues in the latest versions.
