### ISSUE TITLE
Add a custom error handler for the LSP client

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#1769]
The LSP is highly sensitive to Bundler related issues. If any errors occur, we're currently letting the default LSP error handler do its thing, which is restart 5 times and then fail in a non graceful way.

This is not a great experience. We can certainly do better by defining our own custom error handler.  This can be done by defining an `errorHandler` in the [client options](https://github.com/Shopify/vscode-ruby-lsp/blob/79d53557cd0941d97a93d2a937949850b1f86c39/src/client.ts#L112).

Ideally, we should display the error to the user, give them the chance to fix it and them offer to re-launch.

**Comment by henrahmagix** [comment]
This would be extremely helpful, because `Ruby LSP: Restart` never works when it's crashed 🙏
