### ISSUE TITLE
Doesn't have completion/docs for core Ruby modules/classes

### ISSUE THREAD

**Issue by avdi** [Shopify/ruby-lsp#1772]
### Operating System

Ubuntu

### Ruby version

3.2

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Since I started trying to use it, I've never seen the Ruby-LSP extension have autocomplete or docs (as portrayed in the documentation) for core Ruby modules/classes. I recorded this screencast of setting up a brand new Hello World ruby project in a vanilla VSCode Ruby devcontainer to demonstrate:

https://app.screencast.com/nxu9LQIS0YUWO?conversation=RU4ol9HhxOHuW72wMGEoFh

Steps:

1. Make a new directory
2. open the directory in VSCode
3. Create a new Ubuntu Ruby devcontainer for the project
4. Ensure deprecated Ruby extensions are disabled and uninstalled
5. Ensure Shopify Ruby and Ruby-LSP extensions are installed and enabled
7. Create new Ruby file
8. Attempt to use autocomplete/intellisense for core Ruby classes like `IO`, `Kernel`, `File`...

**Comment by vinistock** [comment]
Indexing classes and modules from the Core library via RBS has been shipped in [v0.17.3](https://github.com/Shopify/ruby-lsp/releases/tag/v0.17.3).

Indexing Core methods and constants is next. You can follow the progress in https://github.com/Shopify/ruby-lsp/issues/1335.
