### ISSUE TITLE
`How to debug the Podfile` that auto generated by cocoapods in iOS project

### ISSUE THREAD

**Issue by LongXiangGuo** [Shopify/ruby-lsp#1779]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

In most cases, we need to modify the Podfile to implement different logic for iOS project, so if we could add some configurations to the vs code IDE debug the Pofile directly, it will be more effective for coding and debugging.

From the document I have tried to add this configurations, but it not work for me

```
    {
      "type": "ruby_lsp",
      "request": "launch",
      "name": "Podifle Debug",
      "program": "cd path/to/ios/project && pod install --verbose",
    },
```

Does some one know how to debug it the profile in custom iOS project? How should I configure the required environment variables?

### Description

Debug the Podfile in custom iOS project.

### Implementation

Can we add some configurations like below demonstrate to debug the Podfile

```
    {
      "type": "ruby_lsp",
      "request": "launch",
      "name": "Podfile Debug",
      "cwd": "${iOS Project Dir that contains the Pofile}"
      "program": "pod install --verbose",
      "args" : [
       ]
    },
```

**Comment by vinistock** [comment]
Sorry, this issue requires some iOS development expertise that our team unfortunately does not have. The debug launch settings themselves look fine.
