### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by alexevanczuk** [Shopify/ruby-lsp#1785]
### Operating System

13.2.1 (22D68)

### Ruby version

3.2.0

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Hi! I'm excited to try to use VSCode's breakpoints to debug my tests and application code instead of `binding.pry`. It will be a game changer when I can get it working!

I followed the instructions in the README to create my `launch.json`, which looks like this:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "ruby_lsp",
      "name": "Debug",
      "request": "launch",
      "program": "ruby ${file}"
    },
    {
      "type": "ruby_lsp",
      "request": "launch",
      "name": "Debug test file",
      "program": "ruby -Itest ${relativeFile}"
    },
    {
      "type": "ruby_lsp",
      "request": "attach",
      "name": "Attach to existing server"
    }
  ]
}

```

Note that I'm working in a rails app that uses rspec.

I then try to enter the debugger in one of two ways:
1. I open a test file and click "debug" or and "debug test file" and click the green triangle. All that happens is that it shows up under "call stack" as running, but otherwise I don't see anything to indicate I'm running a test or have entered a debug session. When I click the red square to stop it, nothing happens and it's not removed from the "call stack" section.

![Screenshot 2023-09-18 at 4 17 49 PM](https://github.com/Shopify/vscode-ruby-lsp/assets/3311200/321c6c62-5655-4597-a927-c91063a1a2a3)
![Screenshot 2023-09-18 at 4 17 55 PM](https://github.com/Shopify/vscode-ruby-lsp/assets/3311200/9e377572-1b23-453a-b164-01c7411e707c)

2. I tried clicking "debug" from https://github.com/st0012/ruby-lsp-rspec (cc @st0012). Similar to before – nothing happens.

Please let me know the recommended approach to move forward here. Also happy to provide any other information that will be helpful for debugging. Note that otherwise, my `ruby-lsp` is working exactly as expected. Thanks for working on and releasing such a great toolchain for the ruby community!

**Comment by gerrywastaken** [comment]
> > DEBUGGER: Debugger can attach via UNIX domain socket (/var/folders/lf/4xqm_gk10ts83_mxrhsz9qf80000gn/T/ruby-debug-sock-501/ruby-debug-hung-wulo-95798)
> > DEBUGGER: wait for debugger connection...
> > ```
> 
> This just hangs for me.

@alexevanczuk I know it has been a very long time but what did you mean by "This just hangs for me."?
Do you mean it pauses at `DEBUGGER: wait for debugger connection...`

Just on the off chance this is what you mean by "hang". You then need to attach from vscode.
In your config that is the one called `Attach to existing server`

```
    {
      "type": "ruby_lsp",
      "request": "attach",
      "name": "Attach to existing server"
    }
```

Sorry if you already knew this, it is just that you never said what was hanging or mentioned the word attach, so these two things stuck out as I read your comments and I personally found the docs a little unclear in the debugging section.

![Image](https://github.com/user-attachments/assets/888490c3-4fb5-4afd-9a6b-743947922269)

![Image](https://github.com/user-attachments/assets/750f8c65-725e-409b-8b3a-262776e88cf8)

![Image](https://github.com/user-attachments/assets/6bc85d4d-b4a0-4bc7-8290-f0f443be9e76)

![Image](https://github.com/user-attachments/assets/0f50fbe6-fbb2-4365-b2b5-05cd613680e5)

Also huge thank you @vinistock and everybody else who worked on ruby-lsp, it is fantastic!
