### ISSUE TITLE
Error: "rbenv: bundle: command not found"

### ISSUE THREAD

**Issue by hovissimo** [Shopify/ruby-lsp#1794]
### Operating System

Windows 11 with WSL 2: Ubuntu

### Ruby version

3.0.5

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

I get the following output when I change branches (every time).

```
>> Running `bundle install`...
ERROR> rbenv: bundle: command not found
ERROR> 
ERROR> The `bundle' command exists in these Ruby versions:
ERROR>   3.0.5
ERROR> 
>> `bundle install` exited with code 127
```

On my shell:
![image](https://github.com/Shopify/vscode-ruby-lsp/assets/6434414/2c02cfca-7669-4b53-99a9-c1f82d827c51)

I followed the troubleshooting steps but they didn't help. I don't actually know how the extension and the LSP integrate so I'm a bit lost on how to troubleshoot this.

**Comment by vinistock** [comment]
@hovissimo is this still happening on the latest v0.7.1 version?

**Comment by vinistock** [comment]
Please let us know if this still happens. We made several fixes to version manager integrations.

**Comment by hovissimo** [comment]
> @hovissimo is this still happening on the latest v0.7.1 version?

I don't know, I gave up on this tool.
