### ISSUE TITLE
Mention minimum required dependent gem versions

### ISSUE THREAD

**Issue by onyxraven** [Shopify/ruby-lsp#1795]
When working with an existing project which has rubocop in its Gemfile, it needs to be a compatible version, or a user gets this error message:

```
Error running diagnostics: Incompatible RuboCop version. Ruby LSP requires >= 1.4.0
```

It looks like this comes from [ruby-lsp](https://github.com/Shopify/ruby-lsp/blob/1ac69c9b4187bcae056b577122f7f8db2ff96346/lib/ruby_lsp/requests/support/rubocop_runner.rb#L13) but it doesn't mention it in readme/docs directly either.

**Comment by vinibispo** [comment]
@vinistock, Where would be a great place to put this info?

**Comment by vinistock** [comment]
I'd say we can put it in a new sub section under [usage](https://shopify.github.io/ruby-lsp/#usage). Maybe call it implicit dependencies.

We only have one (RuboCop), but there's no existing place to put it, so I think it warrants a new section.
