### ISSUE TITLE
How To: Use vscode-ruby-lsp with flake.nix based dev enviroment

### ISSUE THREAD

**Issue by StoryparkNick** [Shopify/ruby-lsp#1851]
### Description

Hello! Thanks for this awesome set of libraries.

This is not a bug report, rather a quick info dump for anyone who uses nix flakes and ruby-lsp and wants to use the custom Ruby activation to make use of the Ruby from their `flake.nix`.

In essence, add a command to your `flake.nix` outputs, hardcoded here to use `aarch64-dawin`.

```
      # used to help vscode-ruby-lsp find the appropriate ruby and gems
      packages.aarch64-darwin.activate-ruby = pkgs.writeScriptBin "activate-ruby-nix" ''
        echo "export GEM_HOME=\"$GEM_HOME\""
        echo "export GEM_PATH=\"$GEM_PATH\""
        echo "export PATH=\"$(command -v ruby | xargs dirname):$GEM_HOME/bin:\$PATH\""
      '';
```

Add the follow lines to your VSCode config:

```
  "rubyLsp.rubyVersionManager": "custom",
  "rubyLsp.customRubyCommand": "eval \"$(nix run .#activate-ruby)\"",
```

Restart code, this will ensure the `GEM_HOME`, `GEM_PATH` and `PATH` env variables are set correctly, and `vscode-ruby-lsp` should now be able to find the appropriate Ruby exposed by your flake.

**Comment by StoryparkNick** [comment]
Closing this issue as it requires no action from the maintainers (although if there's a better label I'd appreciate it!).

Apologies if this feels like clutter but I often search issue trackers as a first point of call so hopefully this info is helpful to someone!

**Comment by vinistock** [comment]
Thank you for the kind words! Would you like to put a PR up to add these instructions to our [version managers documentation](https://github.com/Shopify/ruby-lsp/blob/main/vscode/VERSION_MANAGERS.md)? We can include a section for Nix with the commands and configuration you mentioned.

**Comment by omnibs** [comment]
Thank you for posting this! Your solution helped me make the extension work on a `ruby-nix`-enabled repo!

`ruby-nix` gives us a ruby with a read-only `GEM_HOME`, so I had to:
- Give the extension access to an "unlocked" ruby
- Give the extension a writable `GEM_PATH` and `GEM_HOME`

I made an overlay based on your script:

```nix
self: super: {
  activate-ruby-lsp = (super.writeShellScriptBin "activate-ruby-lsp" ''
    echo "export GEM_PATH=${builtins.toString ./path/to/lsp-gems}"
    echo "export GEM_HOME=${builtins.toString ./path/to/lsp-gems}"
    echo "export PATH=\"${super.ruby}/bin:\$GEM_HOME/bin:\$PATH\""
  '');
}
```

And my extension settings were slightly different too:

```json
  "rubyLsp.rubyVersionManager": {
    "identifier": "custom"
  },
  "rubyLsp.customRubyCommand": "eval \"$(activate-ruby-lsp)\""
```

**Comment by kolpav** [comment]
Neovim users are out of luck since the option `customRubyCommand` is only for vscode right?

**Comment by Jeffrey04** [comment]
Just out of curiosity, why wouldn't this setup work?

    "rubyLsp.rubyVersionManager": {
        "identifier": "custom"
    },
    "rubyLsp.customRubyCommand": "nix develop /Users/jeffrey04/Projects/home-manager/devenvs/ruby-3.3",
    "rubyLsp.bundleGemfile": "/Users/jeffrey04/Projects/ruby-tools/ship_it/Gemfile"

I can't put `ruby-lsp` to the project Gemfile, hence I am using the bundleGemfile feature. On the other hand I use `nix develop` to setup a ruby dev environment, so i suppose calling `nix develop` is good enough, but it doesn't seem to work, even adapting the setup doesn't work either.

```
2025-07-25 15:26:16.780 [info] (ship_it) Running command: `nix develop /Users/jeffrey04/Projects/home-manager/devenvs/ruby-3.3 && ruby -EUTF-8:UTF-8 '/Users/jeffrey04/.vscode-oss/extensions/shopify.ruby-lsp-0.9.31/activation.rb'` in /Users/jeffrey04/Projects/ruby-tools/ship_it using shell: /Users/jeffrey04/.nix-profile/bin/bash
```

this is all i get from the output tag for ruby-lsp

<img width="840" height="372" alt="Image" src="https://github.com/user-attachments/assets/0be7534a-8e6b-4936-bbb5-386a3ccb4d71" />

and this is the screenshot of the ruby file type in status bar

EDIT: submitted a patch https://github.com/Shopify/ruby-lsp/pull/3691

**Comment by Jeffrey04** [comment]
But thanks to the pointer, and I somehow managed to get gemini-cli to generate a patch that somewhat works, will submit a PR to begin some work for `nix-develop` as a version manager
