### ISSUE TITLE
Code snippets as LSP completions instead of snippets.json

### ISSUE THREAD

**Issue by olifink** [Shopify/ruby-lsp#1874]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Including code snippets in the code `completion` responses instead of using vscode-extension specific snippets.json would make `ruby-lsp` feature directly available to other editors.

### Description

I'm currently integrating `ruby-lsp` with Nova editor and initially was surprised to not see snippets in the code completion from my extension while they were available in vscode, until I found that these came from the extension's `snippets.json` and not from `ruby-lsp`

I think it would make sense to have as many features as possible that are supported by LSP already to be available through the lsp server so that all editors benefit from these extended capabilities.

### Implementation

(up to you)

**Comment by vinistock** [comment]
Thank you for the feature suggestion!

When you say serve completions from the server, do you mean method completions?

If yes, we already support completion for [require paths](https://shopify.github.io/ruby-lsp/RubyLsp/Requests/Completion.html) and [constants](https://shopify.github.io/ruby-lsp/RubyLsp/Requests/CompletionResolve.html), but finalizing method support is tracked in https://github.com/Shopify/ruby-lsp/issues/899 (which means we can close this issue as a duplicate to centralize all discussions there).

If that's not what you mean, can you please elaborate?

**Comment by vinistock** [comment]
Oh, I see what you mean now. Yeah, we can definitely move these to the server.
