### ISSUE TITLE
Ruby LSP Formatter changes not matching with `syntax_tree write`  

### ISSUE THREAD

**Issue by Try431** [Shopify/ruby-lsp#1884]
### Description
For some reason, my code is suddenly being formatted not in the way that `syntax_tree` would. 

### Settings info
I have Ruby LSP set as my editor, with `syntax_tree` set as my formatter:
```
  "[ruby]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "Shopify.ruby-lsp"
  },
  "rubyLsp.formatter": "syntax_tree",
```

Extension: `vscode-ruby-lsp-v0.5.17 `.
Ruby: `ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]`
VSCode:
```
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.2.0
```

### Reproduction steps
1. Within a Ruby file (using a spec as an example here), modify code so that lint format issues are highlighted:
	
![image](https://github.com/Shopify/ruby-lsp/assets/25510761/86400c66-81e5-407f-87a6-5af1e311d6df)

2. Save (and thus format)
3. See that code has been autoformatted, but it looks weird:
![image](https://github.com/Shopify/ruby-lsp/assets/25510761/0750b703-4a97-4da5-ac95-142d33cbe849)

4. Run `stree write path/to/file`
5. See that finally the code looks how you'd expect it to:
![image](https://github.com/Shopify/ruby-lsp/assets/25510761/cff7cee1-863b-4b1e-b21e-7fce8d88aedf)

I don't know why it suddenly stopped working, but this behavior is pretty disruptive unfortunately.

**Comment by vinistock** [comment]
Thank you for the report! We broke something in a refactor. The associated PR will fix it and be included in the next release.

**Comment by vinistock** [comment]
We're working on another bugfix, but we're hoping to get a release later today.
