### ISSUE TITLE
LSP signatureHelp result is null

### ISSUE THREAD

**Issue by olifink** [Shopify/ruby-lsp#1888]
### Description

Hi again,

I'm debugging my Nova integration `signatureHelp` request of the `ruby-lsp` and would need your insight. I'm using code from your [test file](https://github.com/Shopify/ruby-lsp/blob/main/test/requests/signature_help_test.rb) locally as my `localtest.rb` file.:

```ruby
class Foo
  def bar(a, b)
  end
	
  def baz
    bar#<-- cursor here, entering '('
  end
end
```

the file seems to be indexed correctly (I get valid `hover` responses) but see the following request/response exchange from Nova with the LSP log for `signatureHelp`:

```
Ruby Language Server[11:16:17.839000] Sending JSON-RPC request: number(178) textDocument/signatureHelp
{
  "params" : {
	"position" : {
	  "line" : 5,
	  "character" : 6
	},
	"textDocument" : {
	  "uri" : "file:\/\/\/Users\/olifink\/Courses\/pickaxe\/localtest.rb"
	},
	"context" : {
	  "isRetrigger" : false,
	  "triggerCharacter" : "(",
	  "triggerKind" : 2
	}
  },
  "jsonrpc" : "2.0",
  "method" : "textDocument\/signatureHelp",
  "id" : 178
}

Ruby Language Server[11:16:17.850000] Received JSON-RPC response: number(178) textDocument/signatureHelp
{
  "jsonrpc" : "2.0",
  "id" : 178,
  "result" : null
}
```

the request doesn't seem incorrect and is not very different from the one in your test case, I'm wondering why I get a `null` result in the response?

**Comment by vinistock** [comment]
Closing this for now as it does not seem to be a bug with the Ruby LSP.
