### ISSUE TITLE
Are there plans to add "useBundler" and "pathToBundler" settings to launch.json for debugging?

### ISSUE THREAD

**Issue by dimonker** [Shopify/ruby-lsp#1907]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

We are planning to migrate from VS Code extension https://github.com/rubyide/vscode-ruby to your extension, but we are missing two settings in launch.json "pathToBundler" and "useBundler".
https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#pathtobundler
https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#usebundler

### Description

Are there plans to add "useBundler" and "pathToBundler" settings to launch.json for debugging?

**Comment by vinistock** [comment]
Thank you for the feature suggestion. Can you give me an example `launch.json`?

I don't believe you need those configurations at all. The Ruby LSP hooks into your version manager to activate the Ruby environment, which means it should be able to find Bundler without you having to specify the path to it.

And if you want to use Bundler when launching a Ruby script, all you have to do is including `bundle exec` as part of the `program` configuration.

**Comment by dimonker** [comment]
Thank you, including `bundle exec` as part of the `program` configuration helped, but as it turned out, we still need the `"args"` and `"cwd"` settings.

Here is an example of current `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [{
      "name": "Debug Danger",
      "type": "Ruby",
      "request": "launch",
      "script": "${workspaceRoot}/bin/danger",
      "args": [
        "--dangerfile=${workspaceRoot}/path_to_dangerfile",
        "dry_run"
      ],
      "env": {
        "DEBUG": true
      },
      "cwd": "${workspaceRoot:project}",
      "bundlePath": "${workspaceRoot}/bin/bundle",
      "useBundler": true
    }
  ]
}
```

I managed to figure out the `"args"` setting, but what to do with the `"cwd"` setting is unclear. And the resulting version of `launch.json` for your extension is like this:

```json
{
  "version": "0.2.0",
  "configurations": [{
      "name": "Debug Danger",
      "type": "ruby_lsp",
      "request": "launch",
      "program": "${workspaceRoot}/bin/bundle exec ${workspaceRoot}/bin/danger --dangerfile=${workspaceRoot}/path_to_dangerfile dry_run",
      "env": {
        "DEBUG": true
      },
      "cwd": "${workspaceRoot:project}"
    }
  ]
}
```

**Comment by vinistock** [comment]
Why do you need to set the `cwd`? Do you have multiple workspaces configured? And if that's the case, does moving the `launch.json` file inside that workspace fix the issue?
