### ISSUE TITLE
Can you use this on windows? Or is this only for VSCode on Linux?

### ISSUE THREAD

**Issue by BerndHme** [Shopify/ruby-lsp#1942]
Can you use this on windows? Or is this only for VSCode on Linux?

I'm trying to get a ruby set up working on windows11, but vscode keeps asking for a version manager.
The vscode documentation refers to rbenv, but this seems to be only for unix?

I installed rbenv for windows 
https://www.ruby-lang.org/en/documentation/installation/#rbenv:~:text=like%20operating%20systems.-,rbenv%20for%20Windows,-rbenv%20for%20Windows

but this doesn't work.

What can I use for support on Windows?

**Comment by vinistock** [comment]
Thank you for the bug report! Yes, this extension can be used with Windows. The majority of version managers do not support Windows unfortunately (I'm not 100% sure what's the situation with `rbenv`, but I was under the impression it doesn't support it).

I'm not a Windows user, but it seems that the common way to install Ruby on Windows is `RubyInstaller`, which we do support activation for.

Do you already have Ruby installed in your machine?

**Comment by vinistock** [comment]
The Ruby LSP can found the Ruby installation automatically, but it needs some way to know which Ruby version should be used for the project. If you don't have/don't want to add a `.ruby-version` file, then this PR https://github.com/Shopify/ruby-lsp/pull/1967 will allow configuring a Ruby installation manually.
