### ISSUE TITLE
Warn/Refuse to install if `ruby-lsp` resolves to old versions

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1945]
### Description

`rubocop` currently has a dev dependency on the latest prism version `>= 0.25` which this gem doesn't advertise support for at the moment.

During resolution, this results in a `ruby-lsp` version without prism as a dependency to be choosen, `0.11.2` from october last year. It seems to mostly work but obviously a bunch of stuff is missing.

**Comment by andyw8** [comment]
Discussed with the team today:

* We will decide on what is considered an 'old' server version, perhaps v0.12 where Prism was introduced. Over time, we may bump this to a more recent version.
* When we detect an old server version, we'll show a warning in the extension. This will link to the troubleshooting guide, in a new section explaining possible causes of the server gem being outdated (e.g. the YARP/Prism issue). There will be an option to snooze/ignore the warning.
* In the EDITORS.md doc we'll also explain the potential problem, for the benefit of those not using VS Code.

**Comment by andyw8** [comment]
We've [updated](https://github.com/Shopify/ruby-lsp/pull/2147) for Prism v0.30.0, and will release shortly.

This _should_ be last time we run into this.

**Comment by andyw8** [comment]
Released: https://rubygems.org/gems/ruby-lsp/versions/0.17.3
