### ISSUE TITLE
Server process fails to exit when sent an `exit` notification

### ISSUE THREAD

**Issue by siegel** [Shopify/ruby-lsp#196]
After configuring BBEdit 14 (any version) to use `ruby-lsp` as the preferred language server, I'm finding during testing that the server does not exit when the editor sends an `exit` protocol notification. This causes the application to hang when quitting in cases where the user has opened a Ruby file (which lazy-starts the language server).

Server version: 0.2.0
Ruby version: 2.7.3
macOS 12.4 (21F79)

The repro on this is fairly straightforward, as follows:

1. Download and install [BBEdit 14.5.1](https://www.barebones.com/products/bbedit/download.html) (macOS 10.15.4 or later required).
2. Start the application.
3. Configure BBEdit to use `ruby-lsp` as the preferred language server (see [documentation](https://www.barebones.com/support/bbedit/lsp-notes.html#config) for how to do this).
4. Open any Ruby file.
5. Quit the application.

Expected:
=> Application quits immediately

Actual:
=> Application hangs waiting for `ruby-lsp` to exit.

The [troubleshooting section](https://www.barebones.com/support/bbedit/lsp-notes.html#trouble) of the LSP documentation contains a workaround for ill-behaved servers (the fact that it's necessary tells you how often the issue comes up, so it isn't just you :-) ); but the server _should_ quit immediately (or at least as rapidly as possible) upon receiving an `exit` notification.

**Comment by vinistock** [comment]
Thank you for reporting the bug. I think this is because we were not handling the `exit` notification. It should be fixed in the attached PR.

**Comment by siegel** [comment]
Thank *you*, I appreciate the fix!
