### ISSUE TITLE
VSCode extension + chruby custom paths via RUBIES = cannot find installation directory for Ruby

### ISSUE THREAD

**Issue by swrobel** [Shopify/ruby-lsp#1969]
### Reproduction steps
1. Start VSCode in a ruby project dir. Error notification pops up.
<img width="456" alt="Screenshot 2024-04-24 at 2 01 32 PM" src="https://github.com/Shopify/ruby-lsp/assets/157270/4e21cf5a-9cfa-413a-8ac2-da3b048b763d">

```
Failed to activate [object Object] environment: Cannot find installation directory for Ruby version 3.3.1 or ruby-3.3.1
```

The only output that I see in the VSCode output tab for Ruby LSP is:
```
2024-04-24 14:10:27.958 [info] (my-app) Discovered Ruby version 3.3.1 from file:///Users/swrobel/Code/my-app/.ruby-version
```

I don't see an activation command that I can attempt to replicate, as suggested in the [troubleshooting steps](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md#try-to-run-the-ruby-activation-manually), but running `chruby 3.3.1` in the VSCode terminal works without error.

### Versions / Environment
* VSCode 1.88.1
* Ruby LSP VSCode version v0.5.19
* Ruby LSP Gem version unknown, but I've run the `Ruby LSP: Update language server gem` command

**VSCode settings.json**
```json
  "rubyLsp.rubyVersionManager": {
    "identifier": "chruby"
  },
```

**.ruby-version file contents:**
```
3.3.1
```

A perhaps unique aspect of my setup is that I install rubies via Homebrew, and make them available in chruby by setting the `RUBIES` env var in my `.zprofile`. This seems to be picked up properly by VSCode, regardless of whether it's launched from the dock icon or a terminal command.
```
$ echo $RUBIES
/opt/homebrew/Cellar/ruby/3.3.1 /opt/homebrew/Cellar/ruby@3.2/3.2.4
```

### Another bug?
As an aside, this extension produces a confusing/inaccurate error message if using a .ruby-version file that doesn't specify a patch version, even though that should be acceptable for `chruby`, ex:
```
3.3
```

The error shown is:
```
Failed to activate [object Object] environment: No .ruby-version file was found
```

**Comment by swrobel** [comment]
@vinistock, I tested the latest, and noticed that the behavior of the new config doesn't exactly match [the description](https://github.com/Shopify/ruby-lsp/pull/1976/files#diff-99d7a3c2c2975fcaf8184c4639922f5ef6c915610b6f8e15ffa8fb8b329828d8R258) provided, since:

```
$ echo $RUBIES
/opt/homebrew/Cellar/ruby/3.3.1 /opt/homebrew/Cellar/ruby@3.2/3.2.4
```
But I needed to set the following in my `settings.json`, omitting the version numbers:

```json
"chrubyRubies": ["/opt/homebrew/Cellar/ruby","/opt/homebrew/Cellar/ruby@3.2"]
```

After adjusting that, it seems like an improvement, but it's now generating a different set of errors:
```
Failed to setup the bundle: Command failed: gem install ruby-lsp
ERROR:  Error installing ruby-lsp:
	ERROR: Failed to build gem native extension.

    current directory: /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0/ext/prism
/opt/homebrew/opt/ruby/bin/ruby extconf.rb
checking for prism.h in /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0/include... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/homebrew/Cellar/ruby/3.3.1/bin/$(RUBY_BASE_NAME)
extconf.rb:94:in `<main>': prism.h is required (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0 for inspection.
Results logged to /Users/swrobel/.gem/ruby/3.3.1/extensions/arm64-darwin-23/3.3.0/prism-0.27.0/gem_make.out
.         See [Troubleshooting](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md) for help
```

```
Failed to setup the bundle: Command failed: gem install ruby-lsp
ERROR:  Error installing ruby-lsp:
	ERROR: Failed to build gem native extension.

    current directory: /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0/ext/prism
/opt/homebrew/opt/ruby/bin/ruby extconf.rb
checking for prism.h in /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0/include... yes
checking for prism/extension.h in /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0/ext... yes
checking for whether -fvisibility=hidden is accepted as CFLAGS... yes
Running make build/libprism.a with {"SOEXT"=>"dylib", "AR"=>"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar", "ARFLAGS"=>"rcu ", "MAKEDIRS"=>"mkdir -p", "RMALL"=>"rm -fr"}
make: getcwd: No such file or directory
make: *** No rule to make target `build/libprism.a'.  Stop.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include=${opt-dir}/include
	--without-opt-include
	--with-opt-lib=${opt-dir}/lib
	--without-opt-lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/homebrew/Cellar/ruby/3.3.1/bin/$(RUBY_BASE_NAME)
	--enable-build-debug
	--disable-build-debug
	--enable-build-minimal
	--disable-build-minimal
extconf.rb:69:in `system': Command failed with exit 2: make (RuntimeError)
	from extconf.rb:69:in `block in make'
	from extconf.rb:68:in `chdir'
	from extconf.rb:68:in `make'
	from extconf.rb:132:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/swrobel/.gem/ruby/3.3.1/extensions/arm64-darwin-23/3.3.0/prism-0.27.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/swrobel/.gem/ruby/3.3.1/gems/prism-0.27.0 for inspection.
Results logged to /Users/swrobel/.gem/ruby/3.3.1/extensions/arm64-darwin-23/3.3.0/prism-0.27.0/gem_make.out
.         See [Troubleshooting](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md) for help
```

**Comment by vinistock** [comment]
Interesting. Maybe the rubies installed via Homebrew have a different gem home than what I expect. Can you share what does `gem env path` print for you for both rubies? Also, if you run `gem install ruby-lsp`, does that successfully compile Prism or does that fail too?

**Comment by swrobel** [comment]
> Can you share what does `gem env path` print for you for both rubies? Also, if you run `gem install ruby-lsp`, does that successfully compile Prism or does that fail too?

**3.3.1**
```
$ gem env path
/Users/swrobel/.gem/ruby/3.3.1:/opt/homebrew/lib/ruby/gems/3.3.0

$ gem install ruby-lsp
Successfully installed ruby-lsp-0.16.6
1 gem installed
```

It seems prism was already installed on 3.3.1. With `ruby-lsp` installed, I no longer get any errors in VSCode when launching my Ruby 3.3.1 project.

**3.2.4**
```
$ gem env path
/Users/swrobel/.gem/ruby/3.2.4:/opt/homebrew/lib/ruby/gems/3.2.0

$ gem install ruby-lsp
Fetching language_server-protocol-3.17.0.3.gem
Fetching ruby-lsp-0.16.6.gem
Fetching prism-0.27.0.gem
Fetching sorbet-runtime-0.5.11367.gem
Successfully installed sorbet-runtime-0.5.11367
Building native extensions. This could take a while...
Successfully installed prism-0.27.0
Successfully installed language_server-protocol-3.17.0.3
Successfully installed ruby-lsp-0.16.6
4 gems installed
```

However, my Ruby 3.2.4 project still throws errors when opening in VSCode. Here's [a gist of the ruby-lsp Output tab](https://gist.github.com/swrobel/e2fd24787e15395bc1d61c363528efd3) from VSCode.

**Comment by vinistock** [comment]
It does actually, unless I explicitly unsubscribe. I'm not sure what's going on for the older Ruby. It's breaking when running `bundle install`, but inside Bundler's own code. And it's the Bundler version that is vendored inside the Ruby installation.

I assume you can successfully run bundle install in your terminal, so I wonder if we're not finding the wrong Bundler executable. If you run `bundle -v` in your terminal for the old Ruby, which version is printed?

**Comment by swrobel** [comment]
> Sorry, which gem home problem?

You previously said:

> Interesting. Maybe the rubies installed via Homebrew have a different gem home than what I expect. Can you share what does gem env path print for you for both rubies?

and I provided those [in the comment above](https://github.com/Shopify/ruby-lsp/issues/1969#issuecomment-2091505976)
