### ISSUE TITLE
vscode: Allow setting bundler path

### ISSUE THREAD

**Issue by g-arjones** [Shopify/ruby-lsp#1986]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Many people like to keep their ruby environments isolated thus install gems in non standard locations (including bundler). This is generally handled by having shims or env files. 

### Description

I would like to be able to set a custom bundler path.

### Implementation

Provide a config option in vscode and use that bundler.

**Comment by st0012** [comment]
I'd like to learn more about the use case in detail so I can better assess this feature:

- What's the main benefit of installing gems in non standard locations?
- Can you provide an example on how that's achieved in your environment, and how do you make other tools work with that setup?

**Comment by g-arjones** [comment]
> What's the main benefit of installing gems in non standard locations?

Isolation. What happens if you have projects that require conflicting versions of bundler? I need a way to tell ruby-lsp which bundler to use.

> Can you provide an example on how that's achieved in your environment, and how do you make other tools work with that setup?

I have `bundler` shims that are basically sh scripts that set a bunch of environment variables and then call bundler. Something like:

```sh
#!/bin/sh
BUNDLE_GEMFILE=/<redacted>/Gemfile
GEM_HOME=/<redacted>/gems/ruby/3.0.0
BUNDLE_BIN_PATH=/<redacted>/3.0.0/gems/bundler-2.4.18/exe/bundle
BUNDLER_VERSION=2.4.18
BUNDLER_SETUP=/<redacted>/gems/ruby/3.0.0/gems/bundler-2.4.18/lib/bundler/setup
RUBYLIB=/<redacted>/gems/ruby/3.0.0/gems/bundler-2.4.18/lib
... removed for brevity ...

exec "${BUNDLE_BIN_PATH}" "$@"
```

Everything works seamlessly as long as this shim is used as the bundler bin.

**Comment by paracycle** [comment]
> Isolation. What happens if you have projects that require conflicting versions of bundler?

This is not a problem, Bundler already handles this properly. Since the version of Bundler used to create a lockfile is encoded inside the lockfile, Bundler knows which version of Bundler it needs to run, and does so appropriately.

Even if this was a problem, you can always run Bundler using `bundler _<version_of_bundler_you_want_to_run>_` and it will do the right thing:
```ruby
$ bundler version
Bundler version 2.5.7 (2024-03-22 commit 199531f621)
$ bundler _2.3.23_ version
Bundler version 2.3.23 (2022-10-05 commit 250d9d485d)
```

**Comment by st0012** [comment]
> Could you please clarify under which situations will the extension install the dependencies automatically and when do I have to add them to my Gemfile? 

You don't need to add `ruby-lsp` to your Gemfile if you use the VS Code extension. 

> I would like to use the custom version manager option and the bundleFile option.

If you follow the steps [here](https://github.com/Shopify/ruby-lsp/blob/main/VERSION_MANAGERS.md#custom-activation) to set up your custom version manager, Ruby LSP will use the Bundler installed for that Ruby automatically.

**Comment by st0012** [comment]
No we don't want users to declare `ruby-lsp` in their Gemfile unless that's necessary (e.g. when they use non-VS Code editors). We explained how the activation work in [this section](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md#how-the-ruby-lsp-activation-works):

>  To avoid having users include the ruby-lsp in their Gemfile, we currently create a custom bundle under the .ruby-lsp directory inside your project. That directory contains another Gemfile, that includes the ruby-lsp gem in addition to your project's dependencies. This approach allows us to automatically detect which formatter your project uses and which gems we need to index for features such as go to definition.

**Comment by g-arjones** [comment]
@st0012 Isn't that what the _server_ is doing? What triggers the installation of the server in the first place? In the vscode extension source code it looks pretty clear to me that the extension will try to install it by running `gem install ruby-lsp` (and not by creating a hidden bundle as what you posted makes it sound like) but only if `bundleGemfile` is not set otherwise the user is expected to add it to their Gemfile. Please, see the snippets below.

https://github.com/Shopify/ruby-lsp/blob/b97e2a0085ca70710eb724963b3c75be8e721f7e/vscode/src/workspace.ts#L175-L183

https://github.com/Shopify/ruby-lsp/blob/b97e2a0085ca70710eb724963b3c75be8e721f7e/vscode/src/workspace.ts#L195-L200

https://github.com/Shopify/ruby-lsp/blob/b97e2a0085ca70710eb724963b3c75be8e721f7e/vscode/src/client.ts#L45-L52


Documentation is a bit confusing, IMHO.

**Comment by paracycle** [comment]
> In the vscode extension source code it looks pretty clear to me that the extension will try to install it by running `gem install ruby-lsp` (and not by creating a hidden bundle as what you posted makes it sound like)

@st0012 is correct. You don't see it in the extension code because the logic for creating the hidden bundle is inside the `ruby-lsp` gem source code. This is so that that logic works across all editors that support the language server protocol, and not just in VSCode.

The server is installed using `gem install`, it is then run using `ruby-lsp` (no `bundle exec` mind you), and that execution creates and installs a new bundle inside the `.ruby-lsp` folder, and once that is in place replaces the running process with `bundle exec ruby-lsp` against that bundle. That's the mechanism.

> Documentation is a bit confusing, IMHO.

Which parts of the documentation is confusing and why?

> I do, actually. I guess I will have to workaround that by using the custom version manager feature.

I still don't think that I was able to fully explain that Bundler is THE isolation tool for Ruby, and that's the whole point of its existence. It feels like you are working against that by creating a more complicated set up, but I can't tell you how to set up your projects at the end of the day.

**Comment by g-arjones** [comment]
> @st0012 is correct. 

I'm sorry to say this but he is not. I think there's a huge misunderstanding here so I will try to explain. My question (this whole thread, actually) was about the extension (I don't understand why he mentioned something that the server is doing). To quote exactly what I asked:

> Could you please clarify under which situations will the extension install the dependencies automatically and when do I have to add them to my Gemfile?

He response was:

> You don't need to add ruby-lsp to your Gemfile if you use the VS Code extension.

As I mentioned before (and pointed to specific bits of the extension's source code that confirm what I was saying) when using the `rubyLsp.bundleGemfile` config option the extension _will not_ install `ruby-lsp`. 

> it is then run using ruby-lsp (no bundle exec mind you)

Again, not correct. I will paste the source code one more time because I think you didn't read it: 

https://github.com/Shopify/ruby-lsp/blob/b97e2a0085ca70710eb724963b3c75be8e721f7e/vscode/src/client.ts#L45-L52

There's actually a very explicit and clear comment that says:

```
 // If there's a user defined custom bundle, we run the LSP with `bundle exec` and just trust the user configured 
 // their bundle. Otherwise, we run the global install of the LSP and use our custom bundle logic in the server 
```

> Which parts of the documentation is confusing and why?

It's confusing because it doesn't say I have to add `ruby-lsp` to my Gemfile if I set `rubyLsp.bundleGemfile` (I had to read the source code to find that out). @st0012 accidentally added to the confusion by pasting documentation that was not about the extension.

**Comment by paracycle** [comment]
> > @st0012 is correct.
> 
> I'm sorry to say this but he is not. I think there's a huge misunderstanding here so I will try to explain. My question (this whole thread, actually) was about the _extension_ (I don't understand why he mentioned something that the _server_ is doing). To quote exactly what I asked:
> 
> > Could you please clarify under which situations will the _extension_ install the dependencies automatically and when do I have to add them to my Gemfile?
> 
> His response was:
> 
> > You don't need to add ruby-lsp to your Gemfile if you use the VS Code extension.
> 
> As I mentioned before (and pointed to specific bits of the extension's source code that confirm what I was saying) when using the `rubyLsp.bundleGemfile` config option the extension _will not_ install `ruby-lsp`.

I will repeat again that @st0012 was correct, given your question. This issue's description says "I would like to be able to set a custom bundler path.". When you asked the question:

> Could you please clarify under which situations will the _extension_ install the dependencies automatically and when do I have to add them to my Gemfile?

there was no indication that you were asking anything about a custom gemfile. The question as posed makes it sound like the question is about adding the gem to your gemfile, which something you shouldn't be doing. So @st0012 was correct in his response and for the reasons what it was so.

It was only later on that you revealed that your issue/question was about the custom gemfile solution, and in that setting, yes, you are right, you need to bring in all of your dependencies, including the `ruby-lsp` gem. Basically, that custom gemfile is what replaces the internal Ruby LSP bundle that the gem would have created for you, so it should be equivalent to it.
