### ISSUE TITLE
VSCode: "Pull diagnostics on save" setting is not working

### ISSUE THREAD

**Issue by mckeed** [Shopify/ruby-lsp#2034]
### Description

When I set `"rubyLsp.pullDiagnosticsOn": "save"`, diagnostics do not show up after saving a file.

### Reproduction steps

1. Open a workspace in VSCode where Ruby LSP works properly
2. Change the `rubyLsp.pullDiagnosticsOn` setting to `"save"`
3. Make a syntax error in an open ruby file and save the file.
4. The error is not highlighted.
5. Closing the tab and re-opening the file highlights the error as expected.

**Comment by andyw8** [comment]
:wave: Thanks for the report, I am able to reproduce.

**Comment by andyw8** [comment]
Observations:

- By default, when we make a change to a file, a `textDocument/diagnostic` is sent.
- With `rubyLsp.pullDiagnosticsOn` set to `save`, and we use "Save Without Formatting", there  there is a notification for `didChangeWatchedFiles`, but nothing for `textDocument/diagnostic`.
- With `rubyLsp.pullDiagnosticsOn` set to `save`, and we save normally, there are notifications for `textDocument/didChange` and `workspace/didChangeWatchedFiles`.
