### ISSUE TITLE
Duplicate test actions

### ISSUE THREAD

**Issue by zrzka** [Shopify/ruby-lsp#2052]
### Reproduction steps

VS Code: 1.89.1
Ruby LSP: v0.5.21
macOS: Sonoma 14.4.1 (23E224)
asdf to manage Ruby (not just) versions

I have a "monorepo" with "three" RoR applications, and I'm using Multi-root workspace. My repo structure is like this:

```
- engines/licensor (RoR engine)
- frontend (RoR app)
  (using the engines/licensor engine)
- backend (RoR app)
  (using the engines/licensor engine)
```

My workspace file contains:

```
{
  "folders": [
    {
      "name": "Root",
      "path": "."
    },
    {
      "name": "Backend",
      "path": "backend"
    },
    {
      "name": "Frontend",
      "path": "frontend"
    },
    {
      "name": "Engine",
      "path": "engines/licensor"
    }
  ],
  "settings": {
    "files.exclude": {
      // Folders from `folders` to remove them from the Root workspace
      "backend/**": true,
      "frontend/**": true,
      "engines/**": true  
    }
  }
}
```

Looking at the list of processes, I have three Ruby LSP servers running. Now, the fun begins.

<details>
<summary>Ignore, will create another issue ...</summary>
Go to Symbol in Editor... shows every symbol three times:

![CleanShot 2024-05-15 at 23 26 41@2x](https://github.com/Shopify/ruby-lsp/assets/1084172/27ebf0a1-aa5d-402f-8235-ceb8762cd2f9)
</details>

Run, Run In Terminal, Debug ... actions are there 3x:

![CleanShot 2024-05-15 at 23 29 30@2x](https://github.com/Shopify/ruby-lsp/assets/1084172/a8a37cd9-03f9-46a3-8f59-47ef88da147b)

It is not relevant which file is opened (e.g. Backend/Frontend/Engine root), everything is there 3x.

I'm wondering whether:

- I'm doing something terribly wrong
- It is a feature request to deduplicate all the things
- Or you have another recommendation how to use Ruby LSP in this kind of setup

**Comment by andyw8** [comment]
:wave: I tried to replicate this by creating a new repo containing two Rails apps, but I'm not seeing the issue you reported:

https://github.com/andyw8/multiroot_monorepo

Is there a way that you can share a minimal repo structure to help diagnose the problem?

**Comment by andyw8** [comment]
Nevermind, I got it:

![Uploading Screenshot 2024-05-16 at 1.38.20 PM.png…]()

We'll look into it.

**Comment by zrzka** [comment]
Apologies for not mentioning it. You have to open at least one Ruby file from each root to get LSPs started.

First file opened, symbols/actions/... just 1x. Another file from another root, 1x -> 2x. Yet another one from the third root, 2x -> 3x.

Unfortunately, I know nothing about VS Code internals, if VS Code should de-duplicate results, so it's hard to judge whether this is Ruby LSP issue or not.

**Comment by zrzka** [comment]
I'm experiencing more weird things right now (re symbols). Will play with it more, and will report in a separate issue. Updated the issue title & initial comment to cut the issue scope to just these Run, Debug, ... actions.
