### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#206]
This roadmap provides a rough idea of the next efforts for the Ruby LSP.

_Items may be changed or reordered and are not guaranteed to be implemented._

### Coming up next

- 🐛 https://github.com/Shopify/ruby-lsp/issues/165
- ✨ https://github.com/Shopify/ruby-lsp/issues/207
- ✨ https://github.com/Shopify/ruby-lsp/issues/60
- ✨ https://github.com/Shopify/ruby-lsp/issues/58
- ✨ https://github.com/Shopify/ruby-lsp/issues/55
- 🛠 https://github.com/Shopify/vscode-ruby-lsp/issues/47
- 🛠 https://github.com/Shopify/vscode-ruby-lsp/issues/157

### Planned

- ✨ https://github.com/Shopify/ruby-lsp/issues/54
- ✨ https://github.com/Shopify/ruby-lsp/issues/110
- ✨ https://github.com/Shopify/ruby-lsp/issues/61
- ✨ https://github.com/Shopify/ruby-lsp/issues/57
- 🛠 https://github.com/Shopify/ruby-lsp/issues/205
- 🛠 https://github.com/Shopify/ruby-lsp/issues/238

### Desired

The following are features that are desired for the Ruby LSP, but are not yet planned - likely because they are already covered by the Sorbet LSP, turning them into nice to haves.

- ✨ https://github.com/Shopify/ruby-lsp/issues/199
- ✨ https://github.com/Shopify/ruby-lsp/issues/59
- ✨ https://github.com/Shopify/ruby-lsp/issues/77
- ✨ https://github.com/Shopify/ruby-lsp/issues/200
- ✨ https://github.com/Shopify/ruby-lsp/issues/201
- ✨ https://github.com/Shopify/ruby-lsp/issues/202
- ✨ https://github.com/Shopify/ruby-lsp/issues/203
- ✨ https://github.com/Shopify/ruby-lsp/issues/204
- ✨ https://github.com/Shopify/ruby-lsp/issues/208

**Comment by sandstrom** [comment]
Awesome project! 🏅 

- A language server protocol feels like something that should (perhaps?) eventually live somewhat independently from a single company/org [Shopify].

- Also, has there been any discussion on merging efforts with Solargraph? Seems somewhat redundant to maintain two separate language servers.

- Perhaps this should be mentioned somewhere on https://www.ruby-lang.org/en/documentation/
