### ISSUE TITLE
`with_server` helper should not use `stubs` for the `stub_no_typechecker` option

### ISSUE THREAD

**Issue by st0012** [Shopify/ruby-lsp#2190]
### Description

`stubs` comes from `Mocha`, which is not a dependency of `ruby-lsp`. So if the addon doesn't use `Mocha` but sets `stub_no_typechecker` to `true`, [this line](https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/test_helper.rb) will cause `NoMethodError`:

```
     NoMethodError:
       undefined method `stubs' for an instance of RubyLsp::GlobalState
```

**Comment by andyw8** [comment]
We could probably refactor so that it's an option passed to `RubyLsp::Server.new`, then no stubbing would be needed.
