### ISSUE TITLE
Visual Studio Code 0.7.4 appears to be unable to initialize rbenv

### ISSUE THREAD

**Issue by justinbburris** [Shopify/ruby-lsp#2202]
### Description

When I attempt to load a codebase with ruby LSP and the Visual Studio Code integration (at version `0.7.4`), the extension fails to load. 

**It works when using the extension at `0.7.2`**

> Some initial investigation turned up this [change](
https://github.com/Shopify/ruby-lsp/commit/53cf57aa5129a4fad42cafb7932c648c2c3a3442) to the rbenv (and other manager) initialization. Seems like it could be related?

### VS Code error popup
```shell
Automatic Ruby environment activation with rbenv failed: 
Command failed: rbenv exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)' 
zsh:1: command not found: rbenv
```

### Output error
```shell
2024-06-17 21:25:52.034 [info] (smallwins) Running command: `rbenv exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)'` in /Users/justinburris/dev/saishori/smallwins using shell: /bin/zsh
```

## Debugging

Here's the output from running the intialization command from the shell directly

```shell
$ /bin/zsh -ic 'rbenv exec ruby -rjson -e "puts JSON.dump(ENV.to_h)"'

{"RBENV_VERSION":"3.3.0",...}
```

### Configuration

Processor: Apple M2 Max
ruby version: 3.3.0 & 3.0.3
rbenv version: 1.2.0 (installed via brew and configured per usual method)
shell: zsh
editor: VS Code 1.90.1
No vs code configuration

### Project setup
Any ruby project with a Gemfile that has the ruby-lsp gem

If it helps, here's a snippet of my `.zshrc`

```shell
eval "$(/opt/homebrew/bin/brew shellenv)"

# rbenv
# To enable shims and autocompletion add to your profile:
eval "$(rbenv init - zsh)"
FPATH=~/.rbenv/completions:"$FPATH"
```

**Comment by justinbburris** [comment]
I appreciate y'alls work here. It's tough dealing with all of the different configurations out there.

It looks like moving it to the `~/.zshenv` file did the trick!

Per [these docs](https://zsh.sourceforge.io/Doc/Release/Options.html#Options:~:text=After%20/etc/zshenv%20is%20sourced%20on%20startup%2C%20source%20the%20.zshenv), that file is sourced very early in the initialization, and appears to work!

Would y'all be open to updating the [troubleshooting guide](https://github.com/Shopify/ruby-lsp/blob/main/TROUBLESHOOTING.md) to indicate this solution?

**Comment by xeron** [comment]
I see similar issues activating `asdf` if vscode was not started from the shell.

**Comment by andyw8** [comment]
It seems @justinbburris's issue is solved, and there is a seperate issue by @xeron, so I will close this.
