### ISSUE TITLE
Implement skipFiles

### ISSUE THREAD

**Issue by optikalefx** [Shopify/ruby-lsp#2211]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

The debugger often goes into ruby internals and gems. But we often just want to debug our own code. skipFiles is the default vscode way of handling thins

### Description

skipFiles specified as an array inside of the launch.json configurations

```js
{
      "type": "ruby_lsp",
      "request": "attach",
      "name": "Attach to existing server",
      "skipFiles": ["/Users/me/.rbenv/**/*.rb",],
    }
```

**Comment by vinistock** [comment]
Thank you for the feature suggestion! And thank you for the precise response, @marknuzz.

> skipFiles is the default vscode way of handling thins

Do you have a reference for this in the docs? I can't seem to find anything in the VS Code API documentation saying that this is the recommended way of handling it.

Extension that provide debug adapters are the ones that contribute those configurations to the launch tasks, so maybe `skipFiles` is just a configuration that is provided by some other debug adapter?

If we can confirm that this is the recommendation by VS Code in some piece of documentation, than I agree we should add it. But if this is just a configuration field contributed by debug adapters, then we should match what the `debug` gem expects and just document what @marknuzz replied somewhere.
