### ISSUE TITLE
Switching between 'none' and 'rbenv' for rubyLsp.rubyVersionManager.identifier in devcontainer and local environment

### ISSUE THREAD

**Issue by hangingman** [Shopify/ruby-lsp#2226]
I am currently exploring the use of the ruby-lsp in both a devcontainer and a local environment setup. 

I have encountered an issue where I am unable to switch the `rubyLsp.rubyVersionManager.identifier` between 'none' and 'rbenv'. Following is my usecase;
- On my environment, devcontainer (docker container) not using rbenv, so it should be configured as 'none'.
- However, my local environment is using rbenv, so it should be configured as 'rbenv'.

I tried `.vscode/settings.json` having `rubyLsp.rubyVersionManager.identifier=rbenv`
And  `.devcontainer/devcontainer.json` having `customizations.vscode.settings.rubyLsp.rubyVersionManager=none`

However it won't work, I got the error `Failed to activate rbenv environment: command not found: rbenv` like #1720
Because devcontainer doesn't have rbenv.

This functionality is needed for my workflow, and I would like to know if there is a possible workaround or a fix that can be implemented. Could you please provide guidance on how this can be achieved, or if there are plans to support this feature in the near future? Thank you for your assistance.

**Comment by hangingman** [comment]
@Earlopain Thank you, it works ...
I will close this issue.

**Comment by Earlopain** [comment]
That's nice, I wasn't sure if you had a good reason to manually specify it.

I know you can set settings specifically for devcontainers but never thought about how that works when it is already set in `.vscode`. I guess I would expect it to take precedence like you thought as well but perhaps it just doesn't work that way.
