### ISSUE TITLE
vscode fails to activate Ruby environment with asdf when not started from the shell

### ISSUE THREAD

**Issue by xeron** [Shopify/ruby-lsp#2247]
### Description

`asdf` is activated successfully when editor started from the shell using `code .`, but not when started from macOS Dock.

Error output:

```
2024-07-02 13:25:49.506 [info] (myproject) Discovered version manager asdf
2024-07-02 13:25:49.508 [info] (myproject) Running command: `. /opt/homebrew/opt/asdf/libexec/asdf.sh && asdf exec ruby -W0 -rjson -e 'STDERR.print({env: ENV.to_h,yjit:!!defined?(RubyVM::YJIT),version:RUBY_VERSION}.to_json)'` in /Users/ilarionov/workspace/devel/myproject using shell: /opt/homebrew/bin/bash
2024-07-02 13:25:49.984 [error] (myproject) Tried parsing invalid JSON environment: completion-ruby not loaded; requires bash-completion
For more information, type: completion-ruby-help
```

Seems like it has something to do with my extra bash-completion:

```
$ cat ~/.bashrc | grep completion-ruby
. ~/.bash_completion.d/completion-ruby/completion-ruby-all
```

**Comment by vinistock** [comment]
Thank you for the bug report. It does indeed seem like your bash completions are dependent on something that doesn't exist in VS Code's NodeJS process.

Do you know exactly under which conditions `completion-ruby not loaded; requires bash-completion` is printed? Is it dependent on some environment variable?

**Comment by xeron** [comment]
> Do you know exactly under which conditions `completion-ruby not loaded; requires bash-completion` is printed? Is it dependent on some environment variable?

`bash` and `bash-completion` are both installed using brew and loaded like this:

```
# Bash-completion
export BASH_COMPLETION_COMPAT_DIR="/opt/homebrew/etc/bash_completion.d"
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
. ~/.bash_completion.d/completion-ruby/completion-ruby-all
. ~/.bash_completion.d/docker.bash-completion
```

**Comment by vinistock** [comment]
Then you'll need to load this conditionally only if bash is not being launched from VS Code. 

There's no way to prevent the bash completion errors from the extension side because `asdf` requires the shell to be set in order to work properly - and simply loading the shell will load bash completions which then triggers the error.

VS Code injects many environment variables which are going to be available when we launch the shell. For example, `VSCODE_CWD` or `VSCODE_PID`. You will need to change the script that is loading bash completions to not load it if those variables are set.

**Comment by xeron** [comment]
@vinistock this doesn't make any sense to me due to the following reasons:

1. everything works when I start code from the shell using `code .` command
2. there are tons of different `.bashrc` configs people have and you can't ask everyone who's `.bashrc` is incompatible with `ruby-lsp` to change it to check VSCODE env var

There should be a better way to handle it on extension side. Maybe start the shell with `--noprofile --norc` parameters.
