### ISSUE TITLE
Create test framework for grammar rules

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2249]
Currently, there are no tests for our grammar files. Not having tests is always bad, but it's especially worse for this case since the Ruby grammar file is immense and filled with complex regexes that try to understand Ruby's ambiguous syntax.

Let's try to design a little test framework that allows us to assert the token types for a string of Ruby code. The framework should apply the grammar rules on the given source string and then somehow allow us to assert the tokens based on positions.

Something like this:

```typescript
test("Class declaration tokens", () => {
  const tokenTypes = applyGrammar("class Foo < Bar; end");
  assert.strictEqual(tokenTypes[0].type, "keyword");
  assert.strictEqual(tokenTypes[1].type, "class.declaration");
});
```

**Comment by andyw8** [comment]
I hadn't realised the extension already has something for testing grammar rules:

https://github.com/Shopify/ruby-lsp/pull/2493
