### ISSUE TITLE
Improve `CONTRIBUTING.md` for the vscode extension

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#2258]
### Description

Currently it is very detailed about `ruby-lsp` but I am not sure how I am supposed to run the vscode extension tests.

`yarn test` is obviously a command but I'm pretty sure I would have to install shadowenv and put a ruby in /opt which I don't really want to do. It would be nicer if tests with such prerequisites could skip instead.

What I really want to do is run just a subset of tests. I feel like there must be an extension for this but I'm not getting any recommended.

**Comment by vinistock** [comment]
Indeed we can improve the contributing file to have better instructions. However, we haven't found anything that allows running a sub-set of the suite.

You can run it with `yarn test`, but that downloads a test version of VS Code and takes a little longer. The easiest way is to select the `Extension tests` task in `Run and debug` and then execute that.
