### ISSUE TITLE
Indexing error in `existing_or_new_singleton_class`

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#2287]
As reported in https://github.com/Shopify/ruby-lsp/issues/1897#issuecomment-2222048806, indexing the httplog gem is failing.

**Comment by andyw8** [comment]
@zachahn-gusto are you on the latest server gem? This does not error for me.

**Comment by zachahn-gusto** [comment]
Yes I am! 0.17.14. To be honest, I wasn't really able to reproduce this issue consistently. I'll see if I can find a better test case.

**Comment by zachahn-gusto** [comment]
Quick update, I wasn't able to make it crash, but here's a test case that demonstrates what I'm seeing

```ruby
    def test_indexing_singleton
      index(<<~RUBY)
        module ::Foo
          class Bar
            class << self
            end
          end
        end
      RUBY

      # We want to explicitly verify that we didn't introduce the leading `::` by accident, but `Index#[]` deletes the
      # prefix when we use `refute_entry`
      entries = @index.instance_variable_get(:@entries)
      assert_empty(entries.keys.select { _1.start_with?("::") })
    end
```

That fails with this error:

```
Failure:
RubyIndexer::ClassesAndModulesTest#test_indexing_singleton [~/ruby-lsp/lib/ruby_indexer/test/classes_and_modules_test.rb:601]
Minitest::Assertion: Expected ["::Foo::Bar::<Class:Bar>"]
 to be empty.
```

**Comment by vinistock** [comment]
Ah, that's another part of the bug we missed indeed. I'm cutting a PR for that.

**Comment by vinistock** [comment]
https://github.com/Shopify/ruby-lsp/pull/2471
