### ISSUE TITLE
Ruby LSP: indexing files: 0% completed hangs forever

### ISSUE THREAD

**Issue by argent-smith** [Shopify/ruby-lsp#2288]
### Description

Hi. On my project, I see "Ruby LSP: indexing files: 0% completed" notification and progress spinner — they stay forever

Configuration:
VScode  1.91.0
Ruby LSP plugin v0.7.11
ruby-lsp in the project's bundle 0.17.6

**Comment by andyw8** [comment]
Hi @argent-smith, can you try running `ruby-lsp-doctor` in your repo, and see if hangs.

**Comment by argent-smith** [comment]
> can you try running `ruby-lsp-doctor` in your repo, and see if it hangs

Hi @andyw8, ruby-lsp-doctor doesn't hang

> And also check for any errors in the Ruby LSP output panel.

It looks like this:
![image](https://github.com/Shopify/ruby-lsp/assets/448040/dffa3e1f-6512-4e0d-be78-7d5a1e93b96f)

**Comment by argent-smith** [comment]
@andyw8 also, this works fine:

```
⟩ bundle exec ruby-lsp --time-index
Ruby LSP v0.17.6: Indexing took 9.86661 seconds and generated:
- Module: 14269
- Class: 9314
- Method: 72038
- InstanceVariable: 23228
- Accessor: 9433
- UnresolvedMethodAlias: 3000
- Constant: 7616
- SingletonClass: 3208
- UnresolvedAlias: 434
```

**Comment by andyw8** [comment]
Thanks, please also check here for errors (choose Output, then select Ruby LSP):

<img width="970" alt="Screenshot 2024-07-11 at 12 38 09 PM" src="https://github.com/Shopify/ruby-lsp/assets/13400/7332910a-e4f7-40ac-b321-a600ce45db42">

**Comment by andyw8** [comment]
Note: The `ruby-lsp-doctor` command is now `ruby-lsp --doctor` (https://github.com/Shopify/ruby-lsp/pull/2310)

**Comment by thewatts** [comment]
I was having the same

- `Ruby 3.3.4`
- `ruby-lsp 0.17.15`

I run `ruby-lsp --doctor` and get no errors, and my editor `nvim` just hangs saying that it's at 0%.

**Our issue: we needed to upgrade `standard`.**

---

Note: I attempted to upload screenshots, but for some reason it's not working at the moment.

**Comment by baelter** [comment]
I'm getting a similar issue. Ruby LSP fail to start because it can load a gem required by a rubocop config in a parent folder which shouldn't even be in use since to project has its own. Either way, the gem is installed for the ruby version in use. 

They are not installed in the current bundle though.

```
2024-10-23 11:03:21.224 [info] (rubocop-eightyfourcodes) Finished initializing Ruby LSP!
2024-10-23 11:03:21.473 [info] (rubocop-eightyfourcodes) Error processing initialized: /home/anders/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rubocop-1.67.0/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load': cannot load such file -- rubocop-gitlab-security (LoadError)
...
	from /home/anders/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-0.20.1/lib/ruby_lsp/requests/support/rubocop_runner.rb:86:in `initialize'
```

**Comment by mrbongiolo** [comment]
I had a similar issue running ` ruby-lsp`  with ` neovim` . It always hang in "indexing files: 0%".

The harder part was that `--doctor`, logs, and debug didn't show any error; it only hung when the `lsp` was started within Neovim (installed via Mason).

In the end, the problem was that ` .rubocop.yml` file referenced `rubocop-rails-omakase`  in `inherited_gem` section, but we changed `rubocop-rails-omakase` for `standardrb` in the project Gemfile.

Removing that line solved the issue, or even removing the `.rubocop.yml` file solves the issue.

**Comment by vinistock** [comment]
@mrbongiolo that's interesting, did you notice if you had anything printed to the output tab? I can understand the linting/formatting not working under those conditions, but if indexing broke too there's a chance that we're not handling errors gracefully somewhere.

Is having a `.rubocop.yml` file with the omakase thing, but using Standard enough to reproduce?

**Comment by kristian-nst** [comment]
> I had a similar issue running ` ruby-lsp` with ` neovim` . It always hang in "indexing files: 0%".
> 
> The harder part was that `--doctor`, logs, and debug didn't show any error; it only hung when the `lsp` was started within Neovim (installed via Mason).
> 
> In the end, the problem was that ` .rubocop.yml` file referenced `rubocop-rails-omakase` in `inherited_gem` section, but we changed `rubocop-rails-omakase` for `standardrb` in the project Gemfile.
> 
> Removing that line solved the issue, or even removing the `.rubocop.yml` file solves the issue.

omg thank you!!

**Comment by dbarron** [comment]
> In the end, the problem was that  .rubocop.yml file referenced rubocop-rails-omakase in inherited_gem section, but we changed rubocop-rails-omakase for standardrb in the project Gemfile.
> 
> Removing that line solved the issue, or even removing the .rubocop.yml file solves the issue.

> I don't have vscode currently installed on my Windows setup to try to replicate there.

Fixed it for me in a VSCode devcontainer. Thanks!!
