### ISSUE TITLE
Error while indexing: undefined method `file_path' for nil:NilClass

### ISSUE THREAD

**Issue by mjohansenwork** [Shopify/ruby-lsp#2295]
### Description

I keep randomly seeing this error message pop up:
<img width="577" alt="image" src="https://github.com/user-attachments/assets/09f5bb0d-6a6f-43bc-877f-91973fa1eb0c">

```
Error while indexing: undefined method `file_path' for nil:NilClass
```

I don't see anything listed in the Ruby LSP VSCode extension output related to the error message.

VSCode `Version: 1.91.1 (Universal)`
Ruby LSP extension `v0.7.11`

**Comment by andyw8** [comment]
Hi, can you please run `ruby-lsp-doctor` on the command line. That should indicate which file is to blame, and then we can try narrow done the problematic code.

**Comment by vinistock** [comment]
This is the same issue as #2287. Let's please centralize the discussions in one place.

**Comment by andyw8** [comment]
Note: The `ruby-lsp-doctor` command is now `ruby-lsp --doctor` (https://github.com/Shopify/ruby-lsp/pull/2310)

**Comment by rdsngit** [comment]
> Thank @rdsngit, could you tell me what the old version of database_cleaner was, so that we can verify that #2287 fixes it?

Yes, it was Ruby 3.3.1 and `database_cleaner` v1.7.0` that resulted in the error using `bundle exec ruby-lsp-doctor`, then after upgrading to `v2.0.2` and opening VS Code the `ruby-lsp` VS Code extension showed the indexing completed without any errors.

**Comment by andyw8** [comment]
Thanks, I verified that `database_cleaner` v1.7.0 can be successfully indexed now.
