### ISSUE TITLE
On type formatting incorrectly adds `end` after hitting Enter key at the end of method's arguments when it has a trailing comma

### ISSUE THREAD

**Issue by davidalejandroaguilar** [Shopify/ruby-lsp#2301]
### Environment

* Ruby LSP VS Code extension version: v0.7.12
* VS Code version: Version: 1.91.1 (Universal)
* Ruby version: ruby 3.1.6p260 (2024-05-29 revision a777087be6) [arm64-darwin24]
* Ruby version manager version: asdf v0.12.0
* Project setup: workspace

### Reproduction steps

1. Open VSCode with the Ruby LSP extension enabled.
2. Open a blank Ruby file.
3. Write the following:

```rb
link_to "Something",
  some_path,
  class: "some_class",
```

4. Hit enter after the last comma:

Expected:

```rb
link_to "Something",
  some_path,
  class: "some_class",
  # cursor here
```

Actual:

```rb
link_to "Something",
  some_path,
  class: "some_class",
    # cursor here
  end
```

This also happens when doing it on a single line:

1. Write the following:

```rb
link_to "Something", some_path, class: "some_class",
```

2. Hit enter after the last comma.

Expected:

```rb
link_to "Something", some_path, class: "some_class",
# cursor here
``` 

Actual:

```rb
link_to "Something", some_path, class: "some_class",
  # cursor here
end
```

**Comment by vinistock** [comment]
Thank you for the bug report! The attached PR should fix this.
