### ISSUE TITLE
Disable method highlighting

### ISSUE THREAD

**Issue by ksweetie** [Shopify/ruby-lsp#2332]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

(I think this is relevant to ruby-lsp, but if not let me know where I can post an issue to. Also wanted to say thanks for the awesome project—I switched to it several months ago and have been very happy with the experience!)

When the cursor is on a method invocation, it highlights that entire method call (and block), as well as every other invocation of the same method. Often times, I'm working in files that repeatedly call the same method. For example, test files where each test is in a method call block. The result is that my entire file is essentially highlighted when the cursor is on the method name. It makes the contrast worse, so the code is harder to read, and it's really distracting to have the entire file flip back and forth from unhighlighted to highlighted, etc.

Video in vscode:

https://github.com/user-attachments/assets/29b904d4-d931-4fac-8f27-17dacbf8af8d

The same problem exists in Zed:
<img width="778" alt="Screen Shot 2024-07-18 at 11 41 06 AM" src="https://github.com/user-attachments/assets/ffd1d9dc-c4cb-462b-b957-ca21ba804e38">

### Description

I'm not sure what makes the most sense. I don't find this type of method highlighting useful, but I imagine there are others who do. Could it be an option to disable it?

For vscode, you can prevent this by setting `"editor.occurrencesHighlight": "off"`, but that disables all occurrences highlighting, like variables, which I do find useful.

I haven't found a way to disable method highlighting in Zed.

**Comment by andyw8** [comment]
@ksweetie thanks for reporting, https://github.com/Shopify/ruby-lsp/pull/2357 will resolve this.

**Comment by ksweetie** [comment]
@andyw8 I really appreciate the quick turnaround, thank you!
