### ISSUE TITLE
Support for requiring non-official addons in custom Gemfile

### ISSUE THREAD

**Issue by r-sierra** [Shopify/ruby-lsp#2339]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

Using non-official addons like `ruby-lsp-rspec` or `ruby-lsp-shoulda` requires  modifications to the project's Gemfile. In cases were we can't modify the project's Gemfile, having an option in `ruby-lsp` to require those addons in the custom `.ruby-lsp/Gemfile` would greatly facilitate the usage of these addons.

### Description

When trying to use a non-official addon one could simply run `ruby-lsp --require ruby-lsp-rspec` and that would add the gem to the custom `.ruby-lsp/Gemfile`. If the gem already existed in the Gemfile then it would be left as is, so as to allow setting custom options like version constraints

**Comment by andyw8** [comment]
Hi @r-sierra 

This is an area where we are planning improvments, but are still deciding on the specifics of the mechanism.

We'll add a note to the roadmap:
https://github.com/Shopify/ruby-lsp/pull/2351
