### ISSUE TITLE
Gemfile.lock needs to be present so VSCode extension Ruby LSP will work

### ISSUE THREAD

**Issue by TlonUqbar** [Shopify/ruby-lsp#2376]
### Description

I'm not sure how to classify this, but this should be mentioned somewhere in the installation docs. 

# The VSCode extension "Ruby LSP" requires the presence of a Gemfile.lock file at the root level in order for it to run. 

 I have a bad habit of making sure that my tools are working before I start creating stuff.  And I usually test things out with a bare bones project.  In this case, I use just a test source file "test.rb" at the root level.

This is the project Structure:
```
Project Root:
|-- test.rb
```

I tried to use Ruby LSP debugger on that project and it wouldn't run. I got this error: "Couldn't find a workspace for `URI: file:///.../source-file or editor: [object Object]`" and the language status center "{}" showed "Ruby LSP: Starting".

 I did not see any documentation saying that it is a requirement.  I had to wade through all the related issues to find a comment that said "You're missing `.ruby-lsp` directory in your projects root.  Add a dummy Gemfile.lock and restart VSCode."  That was indeed the solution, but this was not mentioned anywhere in the documentation. 

I suppose it is sort of expected that at some point any modern Ruby/Rails app will include a Gemfile and a Gemfile.lock, but regardless this should be mentioned in the installation directions or at least on a Known Installation Issues section.

Here is required info:

Ruby LSP VS Code extension:                  0.17.4
Ruby LSP server gem:                               0.17.9
VS Code:                                                      1.91.1
OS:                                                                Linux PoP! OS
Ruby:                                                            3.1.2p20

### How to reproduce
Create a bare bones project with just one source file "test.rb".  Open it with VSCode.  Try to debug using Ruby LSP.  If you don't have a debug config add the launch config and use that to debug.
The error message/notification is : "Couldn't find a workspace for `URI: file:///.../source-file or editor: [object Object]`"  "The language status center shows "Ruby LSP: Starting".

Modified project structure:
```
Project Root:
|-- test.rb
|-- Gemfile.lock   # completely empty, the extension just checks that file exists
```

I simply ran `touch Gemfile.lock` and I restarted VSCode.  I was in complete disbelief that this was the solution.  Tried debugging and it just worked.  The language status center now showed "Ruby LSP v0.17.9: Running"

So please be kind, start a section to document installation issues and solutions.  No one wants to spend any time on something like this that has a super simple solution.  It is a colossal waste of time.

# VSCode Extension "RUBY LSP" only works with projects that have a Gemfile.lock at the root level, if you don't need one make create a dummy one.  

At least this is now going to get indexed be a result on a search engine and hopefully save someone out there some time.

**Comment by vinistock** [comment]
Thank you for the bug report.

There's no requirement that a lockfile be present, but we indeed don't support usage without any workspace folder opened in VS Code #1780.

The reason this is not documented is because we want to fix it, we just haven't prioritized it yet over other things since usage with a workspace folder opened is significantly more common than usage with some individual scripts and no folder.

I'll close this issue to centralize all discussions in the same place (#1780).
