### ISSUE TITLE
No type hints on projects with sorbet when the sorbet extension is not installed

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#2383]
### Description

I noticed that while things seem to be getting indexed I'm not getting any completions for this repo at all and eventually found out that that is because I was missing the sorbet extension. I'd guess this is because of this? https://github.com/Shopify/ruby-lsp/pull/2322

After installation I got hints back. Does it make sense to check for extension presence (this maybe https://code.visualstudio.com/api/references/vscode-api#extensions.getExtension) and provide better behavior for users without it installed?

**Comment by vinistock** [comment]
Thank you for the suggestion! We plan to have more in depth integrations with Sorbet, so hopefully this issue will be solved as a consequence of that.

That said, at the current moment, the Ruby LSP doesn't interact with Sorbet in any way, so we found it a bit odd to have a check verifying if the extension is there. What I mean is, Sorbet is not required for the Ruby LSP to work and yet we'd essentially be adding Sorbet specific functionality.
