### ISSUE TITLE
Node CI action failing on macos

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#2386]
It passed in the PR https://github.com/Shopify/ruby-lsp/pull/2378

but is failing on main:

```
- Resolving version...
Failed to run tests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
(failed again on retry)

I suspect it's related to GH infrastructure, so let's wait a day and see if it resolves itself.

**Comment by vinistock** [comment]
That PR is only updating the `@types/node` package, which only contains type annotations for NodeJS. In the Ruby world, it's like a PR that only updates RBIs. It shouldn't have any impact on the runtime.
