### ISSUE TITLE
ERB support seems to have disabled HTML folding

### ISSUE THREAD

**Issue by Intrepidd** [Shopify/ruby-lsp#2394]
Before erb support was added, it was possible to fold HTML tags in erb files

Since erb support, only ruby expressions are foldable.
Disabling erb support reverts the behaviour as expected.

It would be amazing to be able to fold both ruby expressions and HTML tags with Ruby LSP

**Comment by DanudeSandstorm** [comment]
I reverted back to 0.7.10 to stop seeing errors in my erb

**Comment by andyw8** [comment]
Thanks, I expect this relates to something in https://github.com/Shopify/ruby-lsp/pull/2235 but we'll need to investigate further.

cc @st0012

**Comment by st0012** [comment]
I can reproduce this and am investigating it 👍

**Comment by Intrepidd** [comment]
> So the only way to solve this issue is to tell VS Code to NOT use Ruby LSP's folding range when the file is erb or rhtml.

Is there a way to do that through config?

**Comment by st0012** [comment]
> Is there a way to do that through config?

Do you mean switching between Ruby folding and HTML folding?

**Comment by Intrepidd** [comment]
yes, I guess that could be useful, although in my case I would take the HTML folding over erb folding almost every time
