### ISSUE TITLE
Saving is taking forever

### ISSUE THREAD

**Issue by xikylan** [Shopify/ruby-lsp#2412]
Type: <b>Bug</b>

I disabled formatOnSave, but pressing Cmd+s will take the editor many seconds to finish saving. To the point where I cannot run unit tests effectively because the editor didn't pick up my changes in between test runs.

Extension version: 0.7.14
VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|9, 7, 6|
|Memory (System)|32.00GB (1.51GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether --crash-reporter-id 486600b9-f238-4827-8b3a-e03c5701b4d8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-ranged-c:31107834

```

</details>

**Comment by andyw8** [comment]
Hi @xikylan,

How big is the file you're working on (number of lines)?

**Comment by xikylan** [comment]
> Can you also provide the `ruby-lsp` server version? Or just screenshot this panel:
> 
> <img alt="Screenshot 2024-08-06 at 15 50 42" width="50%" src="https://private-user-images.githubusercontent.com/5079556/355497053-111b50ed-8a89-4509-a9e9-cb1928efafcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTg3MTEsIm5iZiI6MTcyMjk1ODQxMSwicGF0aCI6Ii81MDc5NTU2LzM1NTQ5NzA1My0xMTFiNTBlZC04YTg5LTQ1MDktYTllOS1jYjE5MjhlZmFmY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTUzMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg3OGQxZWI4YTQxYTZjODg3YzQ1MzUyNGNiY2JiZDc2MWM3Mjc1ZGYzOWVlYzc4YWM1MjdiNjNkODJkMTMxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AriwzBjKIGuUJ7Yiwjkj9IM_Gcd1Rl0CWrXa7_0KhUw">

<img width="310" alt="image" src="https://github.com/user-attachments/assets/cc8c104a-3d4e-4924-b1ff-8cd33ddbd377">

**Comment by andyw8** [comment]
Thank you. It looks like like something is erroring:

`Error processing textDocument/documentLink: /Users/lan.nguyen/.asdf/installs/ruby/3.2.3/lib/ruby/gems/3.2.0/gems/ruby-lsp-rails-0.3.11/lib/ruby_lsp/ruby_lsp_rails/code_lens.rb:88:in `initialize': wrong number of arguments (given 3, expected 5) (ArgumentError)
`

We'll look into it.

**Comment by andyw8** [comment]
I'm a little confused by what's showing in path here:

```
/Users/lan.nguyen/Desktop/apm_bundle/apps/property/gems/ruby_lsp-property_app/lib/ruby_lsp/property_app/addon.rb:83
```
Is this is a custom addon you're using?

**Comment by xikylan** [comment]
Ok, after doing some digging, looks like my issue is caused by the `ruby-rubocop` extension and not ruby-lsp. The errors in the output above are from a custom addon my org has recently started using for test code lens for minitest, and is unrelated. I resolved my issue by simply disabling `ruby-rubocop` for now
