### ISSUE TITLE
"Invalid yield" diagnostic in erb

### ISSUE THREAD

**Issue by mbriggs** [Shopify/ruby-lsp#2442]
### Description

On Neovim v0.10.1 going through lspconfig/mason with ruby-lsp v0.17.13

### Reproduction steps

given

```html
<!DOCTYPE>
<html>
  <head>
    <%= yield :head %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```
I am seeing "Invalid yield" on both variants

<img width="728" alt="image" src="https://github.com/user-attachments/assets/efdcd1d0-1a03-470e-a185-da907a61db59">

Love the work you are doing, and appreciate how well things work at this point in erb :)

**Comment by Earlopain** [comment]
Should be fixed in the next release, thanks for the report!
