### ISSUE TITLE
`uninitialized constant Parser (NameError)`

### ISSUE THREAD

**Issue by MrJoy** [Shopify/ruby-lsp#2447]
### Reproduction steps

I have one project where ruby-lsp consistently fails to start, unless I comment the Rubocop dependency out in my Gemfile.

Output from  running `ruby-lsp` (which is identical to the output when VSC runs it):

```
Ruby LSP> Skipping custom bundle setup since /Users/jonathonfrisby/mrjoy/ExtractorComics/.ruby-lsp/Gemfile.lock already exists and is up to date
Ruby LSP> Running bundle install for the custom bundle. This may take a while...
Ruby LSP> Command: (bundle check || bundle install) 1>&2
The Gemfile's dependencies are satisfied
/Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-ast-1.32.0/lib/rubocop/ast/ext/range.rb:28:in `<top (required)>': uninitialized constant Parser (NameError)

Parser::Source::Range.include RuboCop::AST::Ext::Range
^^^^^^
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-ast-1.32.0/lib/rubocop/ast.rb:7:in `require_relative'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-ast-1.32.0/lib/rubocop/ast.rb:7:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-ast-1.32.0/lib/rubocop-ast.rb:3:in `require_relative'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-ast-1.32.0/lib/rubocop-ast.rb:3:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/rubocop-1.65.1/lib/rubocop.rb:19:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/ruby-lsp-0.17.13/lib/ruby_lsp/requests/support/rubocop_runner.rb:5:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/gems/ruby-lsp-0.17.13/lib/ruby_lsp/internal.rb:41:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/gemsets/extractor/bin/ruby-lsp:82:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/bin/bundle:25:in `load'
	from /Users/jonathonfrisby/.rbenv/versions/3.3.3/bin/bundle:25:in `<main>'
```

It seems like the rubocop-ast gem isn't seeing the parser gem as loaded and I have no idea _why_ that is. 

In Pry, I can make `Parser::Source::Range` available with `require "parser"`, but adding that to `range.rb` doesn't change anything.  Adding the more specific `require "parser/source/range"` _does_ fix it -- but a similar error pops up in another source file, for a different class from the parser gem.

Looking at the entrypoint for the parser gem, it looks like it does all its relevant requires unconditionally, so I don't see anything where it might not be loading code because of some environmental condition.

And just to be clear:  I can run `rubocop` just fine.  Everything works.  And it's _only_ Rubocop that blows up ruby-lsp.  If I remove Rubocop from my Gemfile, ruby-lsp has no issues starting.

Attached is my `Gemfile`, `Gemfile.lock`, `.ruby-version`, and `.ruby-gemset`.  I'm using Ruby 3.3.3, latest ruby-lsp, rbenv, rbenv-gemset, and rbenv-binstubs.

[project_config.zip](https://github.com/user-attachments/files/16622989/project_config.zip)

**Comment by Earlopain** [comment]
Hi, thanks for the report but I don't think this is related to ruby-lsp. If I run `bundle exec rubocop` I am getting the same error.

Commenting out gems leads to `plainwiki` as the culprit. This looks very suspicious and probably clashses with the parser gem in some way: https://github.com/Phitherek/plainwiki/blob/6465f7e2ffc4ffbb0d8823ddd19b270d8847c18c/lib/plainwiki.rb

**Comment by vinistock** [comment]
Thank you for the bug report and thank you @Earlopain for investigating it. I agree that this does not seem like an issue with the Ruby LSP.

> I can run rubocop just fine

Running `rubocop` from a global installation without `bundle exec` will not setup your dependencies and that might be where the difference is coming from.

Try Earlopain's suggestion and see if removing `plainwiki` will change anything. Also, try to ensure RuboCop is up to date. The `rubocop-ast` gem is a runtime dependency of RuboCop, so there's no reason why it wouldn't be available unless something is wrong with the bundle.

**Comment by MrJoy** [comment]
The plainwiki gem _does_ seem to be the problem.  I didn't see that the issue wasn't ruby-lsp-specific because I'm using rbenv-gemset to avoid the need for `bundle exec` and... `rubocop` works fine -- `bundle exec rubocop`, however, does not.  Presumably because that's loading `plainwiki` when rubocop is executed.

Sorry to have wasted your time, and thank you for the help!
