### ISSUE TITLE
Ruby LSP Overrides Token Color Settings

### ISSUE THREAD

**Issue by LarryF1sherman** [Shopify/ruby-lsp#2451]
### Description

Environment:

VS Code Version: 1.92.2
Device: MacBook Pro M3 14"
Operating System: macOS Sonoma 14.6.1

Issue Description:
The Ruby LSP extension overrides token color settings in VS Code. When using the GitHub Theme extension, the token colors are changed every time Ruby LSP loads, even if I try to define custom rules in the User Settings JSON. Disabling the Ruby LSP extension restores the colors to the desired default, as set by the GitHub Theme extension or the User Settings.
Just to clarify the colors: GitHub variable is by default some kind of white, Ruby LSP changes it to orange.

**Comment by vinistock** [comment]
Thank for the report, but this is not a bug. The Ruby LSP provides semantic highlighting, which provides the editor with the correct tokens for ambiguous pieces of syntax in Ruby.

Consider the following code

```ruby
# Regular highlighting is based on text mate grammars, which are simply regexes
# that can only look at one line at a time.
#
# The following `foo` identifier is ambiguous if you can only look at one line at
# a time. Is it a method call or a local variable? There's no way to know with
# text mate grammars only.
#
# Semantic highlighting uses the information from the parsed Ruby document to properly
# inform the editor about the correct token in these ambiguous scenarios
foo
```

That said, if themes do not define colours for the semantic information provided by the Ruby LSP, it may end up looking worse indeed. But that is a limitation of the theme, which is not considering the semantic tokens provided. You can read more in https://github.com/Shopify/ruby-lsp/blob/main/SEMANTIC_HIGHLIGHTING.md.

Alternatively, you can disable semantic highlighting in several ways:

```jsonc
{
  // Your JSON settings

  // Disable semantic highlighting altogether
  "editor.semanticHighlighting.enabled": false,

  // Tell VS Code to let the themes inform the editor about whether they
  // are ready for semantic highlighting or not
  "editor.semanticHighlighting.enabled": "configuredByTheme",

  // Disable the Ruby LSP semantic highlighting feature. This is less optimal
  // than the previous options
  "rubyLsp.enabledFeatures": {
    "semanticHighlighting": false
  }
}
```
