### ISSUE TITLE
Breadcrumb Navigation and Code Folding Disabled When Ruby LSP Is Enabled

### ISSUE THREAD

**Issue by LarryF1sherman** [Shopify/ruby-lsp#2452]
### Description

Environment:

VS Code Version: 1.92.2
OS: macOS Sonoma 14.6.1
Device: MacBook Pro M3 14"

Issue Description:

When the Ruby LSP extension is enabled, the breadcrumb navigation and code folding features in VS Code do not function as expected. The top navigation that shows the parent context of the code block (breadcrumbs) and the ability to fold/unfold code blocks both stop working. These features return to normal when the Ruby LSP extension is disabled.

**Comment by vinistock** [comment]
Thank you for the bug report! Can you provide more context? What version of the Ruby LSP server are you on? What are you opening in the editor (a single Ruby file or an entire project)?

The feature behind breadcrumbs is document symbol. Both document symbol and folding range are working normally for me, so I'm not sure how to reproduce this.
