### ISSUE TITLE
Go To Definition is Mapped to CMD + B

### ISSUE THREAD

**Issue by dlinch** [Shopify/ruby-lsp#2475]
### Description

Basically, ruby-lsp seems to have overwritten the VS Code keybinding for closing the sidebar, which is CMD + B on a Mac. Even after deactivating the extension CMD + B continues to be broken. I have nothing in my settings.json around the ruby-lsp, the sidebar, or go to definition. There is no setting to change the sidebar visibility toggle, it doesn't seem like something that should be overwritten, and CMD + B doesn't even semantically make sense as the hotkey for go to definition anyway. The VSCode documentation states it should only really happen on a CMD + Click action.

My OS is Mac Sonoma, VS Code latest version as well as the ruby-lsp latest version as I downloaded it yesterday. Using rbenv on ruby 3.3.0, but that seems largely irrelevant to this issue.

### Reproduction steps

1. Start the Ruby LSP using VSCode
2. Open a Ruby file
3. Place Cursor on Code
4. Hit CMD + B
5. Expect Sidebar to open/close, see it triggers Go To Definition instead. This might look like a small UI prompt at the cursor stating "No definition found"

**Code snippet or error message**
N/A

**Comment by andyw8** [comment]
I can't reproduce this, and I doubt it has anything to do with Ruby LSP.

Perhaps this will help: https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts

**Comment by dlinch** [comment]
@vinistock @andyw8 So sorry, thank you so much, the link to detecting keybinding conflicts helped me solve it. Turns out it was IntelliJ IDEA keybindings.
