### ISSUE TITLE
Add block highlights to the usual highlights

### ISSUE THREAD

**Issue by frandegrandis** [Shopify/ruby-lsp#2494]
### I have checked that this feature is not already implemented

- [x] This feature does not exist

### Use case

It would be great to be able to see where some particular block starts and ends, this would be useful to understand with some messy files what are we looking into or when defining some test with describes to understand where some particular describe ends, can be also done with folding ranges but i feel is useful to have this one. Left some images with examples, i think this can be an improvement on the document highlighting 

![Image](https://github.com/user-attachments/assets/7795a475-320b-4fa5-994e-bbf94e898442)

![Image](https://github.com/user-attachments/assets/58b80bba-ac4a-43d6-b5c3-264b3642f7e2)

![Image](https://github.com/user-attachments/assets/b8880f69-ea26-46de-a13a-0b50891fa227)

![Image](https://github.com/user-attachments/assets/f45f9df8-6b97-44a1-9199-d38d4baeb822)

![Image](https://github.com/user-attachments/assets/b45367ac-bafe-4f0d-873a-503aa9080151)

### Description

Something similar to document highlighting but for the blocks.
When the cursor is over this "block starters" to highlight the corresponding end.

**Comment by rogancodes** [comment]
Hi Team, Im looking at this issue.
