### ISSUE TITLE
`SystemStackError` during document completion with alias "loop"

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#2497]
### Reproduction steps

I have this rather interesting code from `ruby/ruby` spec suite which to the eyes of ruby-lsp creates an alias loop:

```rb
begin
  class Integer
    alias old_spaceship <=>
    def <=>(other)
      raise
    end
  end
ensure
  class Integer
    alias <=> old_spaceship
  end
end
```

Typing `1.` in the document raises `SystemStackError` because it keeps going back and forth.

https://github.com/user-attachments/assets/f930b610-e005-449e-aac1-26de12b35e54

Altogether not that impactful I believe, for one reason or another I have a copy of `ruby/ruby` in my project folder. The solution for me is just to tell ruby-lsp not to index it but I thought I'd raise this here anyways.

-----

Separatly, ruby-lsp does not recover from this crash, leaves old diagnostics in view, and doesn't notify the user. Took me a while to understand why that syntax error didn't go away.

### Ruby LSP Information

<details><summary>Details</summary>
<p>

#### VS Code Version

1.92.0

#### Ruby LSP Extension Version

0.7.17

#### Ruby LSP Server Version

0.17.16

#### Ruby Version

3.3.4

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- gitlens (15.3.1)
- go (0.42.0)
- vscode-rdbg (0.2.2)
- remote-containers (0.380.0)
- material-icon-theme (5.9.0)
- vscode-yaml (1.15.0)
- ruby-lsp (0.7.17)
- sorbet-vscode-extension (0.3.36)
- vscode-wakatime (24.6.0)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "none",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true
}
```

</details>

</p>
</details>

**Comment by vinistock** [comment]
Thank you for the bug report! https://github.com/Shopify/ruby-lsp/pull/2499 will fix this.
