### ISSUE TITLE
Inform users of failing cops

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#250]
When running RuboCop on files for both diagnostics and formatting, a bug may cause a cop to fail. The default behaviour is for RuboCop to print to `stderr` that a specific check failed and continue running without that particular cop.

While both diagnostics and formatting will still work (just ignoring the failing cop), we may want to display a message to users to let them know that the cop is failing to process the file they're currently working on.

**Comment by vinistock** [comment]
Let's put this on pause and see if they're open to raising a new custom error for this. The current options are brittle or hacky and if we can get first class support for it, it'll be better. Thanks for looking into it!

**Comment by wildmaples** [comment]
With the hopes of moving this issue forward, I've put up a PR on Rubocop for the proposed option: https://github.com/rubocop/rubocop/issues/10977

**Comment by wildmaples** [comment]
Update: The [latest release of Rubocop v1.38](https://github.com/rubocop/rubocop/releases/tag/v1.38.0) contains the fix we need to resolve this issue: https://github.com/rubocop/rubocop/pull/11001

**Comment by andyw8** [comment]
I can take a look at this now that the RuboCop fix is in (since v1.38.0).
