### ISSUE TITLE
Implement request delegation for ERB

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2529]
Currently, we provide features only for the embedded Ruby part of ERB, but not for the host language. It's possible, although not super trivial, to add request delegation support so that features for the host languages will work in VS Code if there's a language service registered for them.

There's an example on how to do this for `<style>` tags embedded inside HTML in the samples repository https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-request-forwarding.

The main idea behind this is that the extension has to implement a [document provider](https://github.com/microsoft/vscode-extension-samples/blob/7749ad8b24005e611047832b2e55bc2661055080/lsp-embedded-request-forwarding/client/src/extension.ts#L32) for virtual documents, where the virtual document includes only the content of the host language.

Using a middleware, the client then checks if a request is [inside or outside the embedded portion](https://github.com/microsoft/vscode-extension-samples/blob/7749ad8b24005e611047832b2e55bc2661055080/lsp-embedded-request-forwarding/client/src/extension.ts#L45) and then either does nothing (invoking `next` to move on to the next layer of middleware) or performs the delegation to VS Code using the virtual document's URI, which will makes VS Code look for the right language service and fulfill the features.

If you check their [embedded support](https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-embedded-request-forwarding/client/src/embeddedSupport.ts) in the sample, they use a pretty similar approach as the one we're using in the server right now. A scanner separates the host language parts from the embedded language parts.

Since our scanner lives in the server, our middleware may have to be a little bit different. We may need to use a special response to tell VS Code that the request needs to be fulfilled by another language service, but we also need a way to get the host language's into the virtual document storage - this is likely the most challenging part.

Finally, one last detail that we shouldn't overlook is that ERB can be used with pretty much any host language, so we can't limit this to HTML, but instead should get the URI for the virtual document based on the original URI.

**Comment by ehutzelman** [comment]
I'm assuming this would allow VS Code to correctly handle .html.erb files as HTML outside of the ERB blocks and give us back those standard HTML editing features like tag completion, formatting, etc. I've had to remap my ERB files as HTML in VS Code go get those features back since I would rather have the HTML features over the ERB features. Would be great to get them both.
