### ISSUE TITLE
Extension is changing the behaviour of special character selection

### ISSUE THREAD

**Issue by shankar15498** [Shopify/ruby-lsp#2544]
### Reproduction steps

1. Start the Ruby LSP using a certain editor
2. Open a Ruby file
3. Write the following text `hi_there?`
4. Double-click on the text `hi_there`
5. Expected behaviour: the word "hi_there" is selected
6. Actual behaviour: the word "hi_there?" is selected

### Expected behaviour:
![Image](https://github.com/user-attachments/assets/6329cac8-ea83-463d-894d-feb1649d06a8)

### Actual behaviour:
![Image](https://github.com/user-attachments/assets/1a8f2965-6d8c-4eaf-a4aa-5d6d5c8df6c9)

If you disable the "Ruby LSP" extension, the expected behaviour will happen.

**Comment by andyw8** [comment]
This is intentional: https://github.com/Shopify/vscode-shopify-ruby/issues/422

**Comment by shankar15498** [comment]
Oh okay. Is there a way to turn off this behaviour @andyw8? I would like to preserve the old behaviour. 😄
