### ISSUE TITLE
Use the document link request to link to Rails documentation

### ISSUE THREAD

**Issue by egiurleo** [Shopify/ruby-lsp#258]
We implemented the DocumentLink request in #58 and used it to go to method definition from gem RBIs.

As a next step, let's use this request to link to the correct Rails documentation for methods that come from the rails gem.

When a user hovers over a method that's defined in rails, there should be a link that says "go to documentation." We can use information about the method, such as the class that defines it and its ancestor chain, as well as information about the rails gem (version number) to link to the correct documentation page for that method.

**Comment by st0012** [comment]
I'm not sure if the implementation in my head is the best solution, so I want to discuss it here:

### Link format

**Class (or module)**
- Example: https://api.rubyonrails.org/v6.1.4/classes/ActiveSupport/Callbacks.html
- `"https://api.rubyonrails.org/#{version}/classes/#{namespaces.join("/")}.html"`

**Method**
- Example: https://api.rubyonrails.org/v6.1.4/classes/ActiveSupport/Callbacks.html#method-i-run_callbacks
- `"https://api.rubyonrails.org/#{version}/classes/#{namespaces.join("/")}.html#method-#{instance_or_class}-#{method_name}"`

### Information required for making the link

- Gem name (e.g. `activesupport`): file name (e.g. `activesupport@7.0.3.1.rbi`)
    - Need it to check if it's a Rails component
- Gem version (e.g. `7.0.3.1`): file name (e.g. `activesupport@7.0.3.1.rbi`)
    - Need it to form the link
- Class/Module name
    - Need it to form the link
- (For methods) method name
    - Need it to form the link's anchor
- (For methods) if it's a class or instance method
    - Need it to form the link's anchor

### Implementation

1. When the request comes in, extract the gem's name and version from it.
2. Check if it's a Rails gem. Return if it's not.
3. Create a namespace stack
4. Parse the document and
    1. When we enter a class/module definition, create a link and push it to the stack
    2. When we visit a method definition, create a link with the class/module name on the stack + the method name

**Comment by paracycle** [comment]
Rails API guides have a search mechanism which relies on the data stored in the `search_index.js` [file](https://api.rubyonrails.org/v6.1.4/js/search_index.js). The data is basically JSON, which we can use to match method names to discover the full doc URL.

For example, the `info` hash contains the following for `run_callbacks`:
```json5
  // ...
  [
    "run_callbacks",
    "ActiveSupport::Callbacks",
    "classes/ActiveSupport/Callbacks.html#method-i-run_callbacks",
    "(kind)",
    "<p>Runs the callbacks for the given event.\n<p>Calls the before and around callbacks in the order they were set, …\n"
  ],
  // ...
```
```

**Comment by Morriar** [comment]
> We can use information about the method, **such as the class that defines it and its ancestor chain**, as well as information about the rails gem (version number) to link to the correct documentation page for that method.

Consider this:

```rb
# file1.rb
class CustomJob < ApplicationJob
  # ...
end
```

```rb
# file2.rb
class SomeJob < CustomJob
  # ...
end
```

Only considering `file2.rb` won't give you much information about what you could document inside `SomeJob`, you would need to resolve `CustomJob` and then find out that it  inherits `ApplicationJob`.

If we want to rely on the model we will have to know about the whole code base and I fear that anything not based on Sorbet will be too slow.

In the meantime we can prototype with the whitelist approach but we may link things that are unrelated by accident.

**Comment by joosnaak27** [comment]
Ok is cool
