### ISSUE TITLE
Add definition, hover and completion support for global variables

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2644]
We should provide features for global variables.

**Note: this issue includes instructions on how to add indexing capabilities for globals, definition support, hover support and completion support. If you wish to contribute this, please create 4 separate pull requests for each step.**

## Implementation

I think the most natural implementation is to add global variables as a new entry type in the index. Hopefully, RBS should have global declarations with documentation that we can simply index like we do core declarations.

If RBS does not have global declarations, please raise it in this issue and we can reach out to Soutaro and the team to ask for guidance.

### Changes to the indexer

1. Create a new [entry](https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_indexer/lib/ruby_indexer/entry.rb) for global variables
2. Start handling `RBS::AST::Declarations::Global` in [process_declaration](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb#L38), so that we can insert the global entries into the index

### Changes to definition

1. We need to allow global variables (`Prism::GlobalVariableReadNode`) as a possible target [here](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/requests/definition.rb#L58)
2. Then the listener has to [register](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/listeners/definition.rb#L51) for the `on_global_variable_read_enter` event and
3. define a [handler](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/listeners/definition.rb#L159) for `on_global_variable_read_enter`
4. Since we're talking about global variables, there's no need to perform any type checking. We just need to access the index and get the declarations based on the name

```ruby
@index[name_of_global_variable]
```
5. Then loop through the entries and push to the response as we do [here](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/listeners/definition.rb#L192)

### Changes to hover

Essentially, the same exact steps as definition. Simply look for the `hover` request and listener and apply analogous changes.

### Changes to completion

1. Allow global variables as a target [here](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/requests/completion.rb#L58)
2. Register for the [event](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/listeners/completion.rb#L93) and create the associated handler
3. Use the following to get suggestions for global variables

```ruby
# Get all declarations that start with `$`, which can only be used by globals
@index.prefix_search("$")
```

4. Use candidates to build the completion list. Similar to what we do [here](https://github.com/Shopify/ruby-lsp/blob/c00f2bce3aaebd9c0d7427e6acadccdac581cd13/lib/ruby_lsp/listeners/completion.rb#L393)

**Comment by vinistock** [comment]
Amazing! Please post here or on the DX Slack if you need any assistance.

**Comment by snutij** [comment]
Just a quick question about the completion request: can we consider adding `$` as a trigger character? Prism isn't dispatching the node event because [it's not considered valid](https://github.com/ruby/prism/blob/5bf1903a0deae231e521ed4212eafd8375fb1d50/templates/src/diagnostic.c.erb#L211). As a result, users have to type a second character to clear the error, which then dispatches the event and triggers the completion. This isn't ideal, especially considering that the majority of global variables are two characters long.

**Comment by andyw8** [comment]
Makes sense to me.

**Comment by vinistock** [comment]
Yeah, we'll definitely need to add `$` as a trigger character.

**Comment by vinistock** [comment]
No need to apologize at all! Thank you for contributing this 🙏.
