### ISSUE TITLE
GitHub Pull Requests extension causes unwanted `textDocument/didOpen` events

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#2649]
I noticed that `textDocument/didOpen` events were being fired for files that I didn't have open in the editor. By disabled extensions one-by-one, I found that the cause was the [GitHub Pull Requests extension](https://github.com/microsoft/vscode-pull-request-github).

This is a problem because:
* Processing those other files has a performance impact
* If the file opened in the background is large, it may trigger the "This file is too long" error.

Further investigation is needed to understand why this happening.

**Comment by vinistock** [comment]
Is there anything we can do on our side though? Maybe we can report the issue to the extension and ask if it's intended behaviour.
