### ISSUE TITLE
Rename and references fail if there's a directory using the `rb` extension

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2687]
This is a bit of a silly bug, but one that has bitten us before in indexing. If you name a directory with the `.rb` extension, like `dir.rb`, then it will match the glob pattern we use to find Ruby files. Both rename and references will fail if a directory exists with that extension.

To fix this, we should do the same thing we did in indexing. Instead of making everyone pay the performance penalty of checking every single path if it's a directory or not, we just [rescue](https://github.com/Shopify/ruby-lsp/blob/844c0c357710dbb2eeeedb80ce1fa489f12a7e43/lib/ruby_indexer/lib/ruby_indexer/index.rb#L403) if the path is a directory and continue.

**Comment by rogancodes** [comment]
If we are going to rescue, do we need to check if the path is a directory?
