### ISSUE TITLE
Client doesn't register dependency paths for version managers based on shims

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2709]
Reported in https://github.com/Shopify/ruby-lsp/discussions/2701

When we configure the client, we use the environment's `GEM_PATH` to [register the language server](https://github.com/Shopify/ruby-lsp/blob/aab9990249616d11c3ef8cbba8e462a92294e265/vscode/src/client.ts#L151) for handling dependency files, which allows users to enjoy all of our features even inside gems.

However, that approach will not work properly for version managers based on shims, because those will not export a `GEM_PATH` when running the [activation script](https://github.com/Shopify/ruby-lsp/blob/aab9990249616d11c3ef8cbba8e462a92294e265/vscode/src/ruby/versionManager.ts#L21).

I believe that the solution is to return another field from the activation script for the gem paths (which can be printed with `Gem.path`). That value will exist even for version managers based on shims, so we can rely on that to register the client paths instead of using the environment variable.

**Comment by edzhelyov** [comment]
The ruby-lsp server runs in the container.

```
vscode ➜ /workspaces/abc $ ps aux | grep ruby-lsp
vscode       569  0.0  0.0   2324  1280 ?        S    14:55   0:00 /bin/sh -c ruby-lsp
vscode       570 50.2  1.7 999800 144624 ?       Sl   14:55   0:03 /home/vscode/.rbenv/versions/3.3.5/bin/ruby-lsp
vscode       681 35.7  0.5 508324 48452 ?        Rl   14:55   0:00 /home/vscode/.rbenv/versions/3.3.5/bin/ruby bin/rails runner /home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/ruby-lsp-rails-0.3.20/lib/ruby_lsp/ruby_lsp_rails/server.rb start
```

```
ruby -e 'puts Gem.path'
/home/vscode/.local/share/gem/ruby/3.3.0
/home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0
```

```
bundle show rails
/home/vscode/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rails-7.2.1.1
```

Are you able to reproduce it on your machine? Because it runs in a devcontainer I would expect that it will won't work on your machine as well.
