### ISSUE TITLE
Block parameters prefixed with underscore are incorrectly highlighted

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#2837]
Our [grammar file](https://github.com/Shopify/ruby-lsp/blob/main/vscode/grammars/ruby.cson.json) is not properly handling block parameters that are prefixed with underscore. For example:

```ruby
# `a` looks ok
# `b` doesn't
[].each do |a, _b|
end
```

We might be missing `_` as a valid character in the regex.

**Comment by pepetorres1998** [comment]
Can I work on this issue?

**Comment by pepetorres1998** [comment]
I'm sorry I did not send a message before, life happened and couldn't work on this 🙏

**Comment by andyw8** [comment]
Completed in https://github.com/Shopify/ruby-lsp/pull/2972
