### ISSUE TITLE
Method information shown on hover/click of the receiver

### ISSUE THREAD

**Issue by bananastalktome** [Shopify/ruby-lsp#2846]
#### VS Code Version

1.95.2

#### Ruby LSP Extension Version

0.8.13

#### Ruby LSP Server Version

0.21.3

#### Ruby Version

3.2.2

#### Ruby Version Manager

rbenv

#### Installed Extensions

<details>
<summary>Click to expand</summary>

- alphabetical-sorter (2.0.1)
- azure-repos (0.40.0)
- black-formatter (2024.4.0)
- copilot (1.245.0)
- copilot-chat (0.22.2)
- debugpy (2024.12.0)
- endwise (1.5.1)
- gitlens (15.6.3)
- isort (2023.10.1)
- jupyter (2024.10.0)
- jupyter-keymap (1.1.2)
- jupyter-renderers (1.0.21)
- markdown-all-in-one (3.6.2)
- material-icon-theme (5.13.0)
- material-theme (3.17.6)
- php-debug (1.35.0)
- php-docblocker (2.7.0)
- python (2024.18.1)
- remote-containers (0.388.0)
- remote-explorer (0.4.3)
- remote-repositories (0.42.0)
- remote-ssh (0.115.0)
- remote-ssh-edit (0.87.0)
- remotehub (0.64.0)
- ruby-lsp (0.8.13)
- vscode-apache (1.2.0)
- vscode-better-align (1.4.2)
- vscode-bnf (0.0.1)
- vscode-cfn-lint (0.26.0)
- vscode-commons (0.0.6)
- vscode-docker (1.29.3)
- vscode-intelephense-client (1.12.6)
- vscode-php-getters-setters-cv (1.6.1)
- vscode-pylance (2024.11.1)
- vscode-tailwindcss (0.12.12)
- vscode-wordpress-hooks (1.4.0)
- vscode-yaml (1.15.0)
</details>

#### Ruby LSP Settings

<details>
<summary>Click to expand</summary>

##### Workspace

```json
{}
```

##### User

```json
{
  "enableExperimentalFeatures": false,
  "enabledFeatures": {
    "codeActions": true,
    "diagnostics": true,
    "documentHighlights": true,
    "documentLink": true,
    "documentSymbols": true,
    "foldingRanges": true,
    "formatting": true,
    "hover": true,
    "inlayHint": true,
    "onTypeFormatting": true,
    "selectionRanges": true,
    "semanticHighlighting": true,
    "completion": true,
    "codeLens": true,
    "definition": true,
    "workspaceSymbol": true,
    "signatureHelp": true,
    "typeHierarchy": true
  },
  "featuresConfiguration": {},
  "addonSettings": {},
  "rubyVersionManager": {
    "identifier": "auto"
  },
  "customRubyCommand": "",
  "formatter": "rubocop",
  "linters": null,
  "bundleGemfile": "",
  "testTimeout": 30,
  "branch": "",
  "pullDiagnosticsOn": "both",
  "useBundlerCompose": false,
  "bypassTypechecker": false,
  "rubyExecutablePath": "",
  "indexing": {},
  "erbSupport": true,
  "useLauncher": false,
  "featureFlags": {}
}
```

</details>

### Reproduction steps

1. Create a new project with the minimum requirements for `ruby-lsp` to run (gemfile, and rbenv .ruby-version for me)
2. Create a `test.rb` with the following:
```rb
class Foo
  def message
    'hello!'
  end
end

class Bar
  def with_foo(foo)
    @foo_message = foo.message
  end
end
```

3. Hover or CMD+hover over `foo` on line 9, and see the popup is info for the `message` method. CMD+Click on `foo` takes you to `def message` (line 2).
![Image](https://github.com/user-attachments/assets/65f26971-55d9-4c44-885d-2bff42d388dd)
4. The behavior works as expected when Hovering or CMD+hover and CMD+Click on `message` on line 9 (shows `message` info in popup takes you to `def message` on line 2 when clicked).

I would expect for `foo` to either not have a clickable behavior (or ideally, but probably out of scope for this request to go to `foo` in the `with_foo` method definition)

**Comment by vinistock** [comment]
Thanks for reporting the issue! The associated PR will fix it.
