### ISSUE TITLE
Wiki homepage has broken link for Official Documentation on configuring editors

### ISSUE THREAD

**Issue by adam12** [Shopify/ruby-lsp#2884]
The Wiki homepage has a broken link to the _Official Documentation_ on configuring editors.I believe the correct link should be this one: https://shopify.github.io/ruby-lsp/editors.html

(Also, it does not appear that the Wiki is publicly editable so perhaps the next paragraph should be adjusted as well)

**Comment by andyw8** [comment]
Thanks, I've disabled the Wiki, we were considering using it at one point but decided against it.
