### ISSUE TITLE
Protect LSP requests from `LoadError`

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#291]
While using the LSP, I noticed it was crashing when trying to get started on files, which should never happen given that we rescue errors and send it over telemetry instead of allowing them to stop execution.

The issue was some bad require coming from inside RuboCop during our first attempt to run diagnostics and load the runner class. Because it threw a `LoadError`, we didn't catch it [here](https://github.com/Shopify/ruby-lsp/blob/9c080e9709f5865775ebfbb9ae421a908a6feecc/lib/ruby_lsp/queue.rb#L97) (a `LoadError` is not a `StandardError`).

This error ended up killing the worker thread, but not the main process, which lead to all sorts of weirdness - including infinite formatting prompts.

We should rescue `LoadError` as well and prevent the worker from crashing silently.

**Comment by Morriar** [comment]
Good point, I wonder if something like this would work:

```rb
begin
  # ...
rescue SystemExit => e
  raise e
rescue Exception => e
  log(e)
end
```
