### ISSUE TITLE
Is it possible to move `.ruby-lsp` from the repo into a tmp directory?

### ISSUE THREAD

**Issue by KonnorRogers** [Shopify/ruby-lsp#2918]
### I have checked that this feature is not already implemented

- [x] This feature does not exist

### Use case

It would be useful to not have to include .ruby-lsp in every .gitignore file and not have to be careful not to commit it, especially in cases you don't own the `.gitignore` and don't want to modify it in your PR.

### Description

I've noticed the Ruby LSP adding the `.ruby-lsp` directory into my repositories.

I personally do not care for this as I don't always own the `.gitignore` so I either need to be careful not to commit it on accident, or if I do make sure to delete it before pushing.

Would it be possible to not have the `.ruby-lsp` directory not write directly into the repository?

### Implementation

I understand the reasoning around caching and indexing for saving these files to disk to speed up future lookups, but *think* you could key the `.ruby-lsp` off the current working directory and save it into `/tmp` but I'm not overly familiar with the implementation details of the Ruby lsp directory.

**Comment by andyw8** [comment]
As @adam12 says, this shouldn't be happening. Check any `.gitignore` files in any parent directory, or your home directory, as there might be some entry that's causing.

**Comment by KonnorRogers** [comment]
Hmmm....thanks. Just confirmed on a fresh repo it's not happening. Thanks all, may have some investigation to do. If it pops up again ill work on a reproduction. In the meantime, I think this is safe to close.

**Comment by KonnorRogers** [comment]
Also thank you @adam12 for the tip about the `.gitignore`, I now have a different PR to make on a different LSP that doesnt scope to a directory and ignore itself 🙈
