### ISSUE TITLE
Use vscode/grammars/ruby.cson.json as default Ruby grammar in VS Code

### ISSUE THREAD

**Issue by alexr00** [Shopify/ruby-lsp#2969]
👋 Hello

I work on VS Code, and I maintain the grammars that we use in our built in extensions. We pull these grammars from other OSS projects. The grammar that we use for Ruby is no longer being maintained, so I'm looking for other options. The grammar you have at https://github.com/Shopify/ruby-lsp/blob/main/vscode/grammars/ruby.cson.json looks to be well maintained, and better than our old grammar. We're thinking of incorporating it into VS Code as the default Ruby grammar. 

PR in VS Code where we make the change over: https://github.com/microsoft/vscode/pull/235732

Do you have any concerns about VS Code making this change? I checked a tested of the Ruby syntax highlighting bugs that have been reported against VS Code, and your grammar does indeed fix them!

**Comment by vinistock** [comment]
@alexr00 this is great. Are we ready to close this issue?

**Comment by andyw8** [comment]
https://code.visualstudio.com/updates/v1_97#_new-ruby-syntax-highlighting-grammar
