### ISSUE TITLE
Add a project check executable

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#330]
As we add more features and make changes to existing ones, we'll need to make it easier to test that all of our features are working and that we didn't create easy to catch bugs.

We could have another executable exported from the Ruby LSP gem that simply runs every request on every file of a codebase, accumulated the errors and then displayed them if something broke at the end.

I believe this would be a good addition to help us verify releases before shipping them.

**Comment by Morriar** [comment]
I like the idea of the another executable. I wonder if we could integrate a kind of manual step to run each PR through this tool before merging them rather than waiting for the release.

**Comment by vinistock** [comment]
That would be ideal. As an addition, when errors are caught, I would love if the tool could make it easy to write a new test fixture for us, so that we can grow our example base.

I'm doing this manually right now to verify a recent change and found many syntax examples we aren't testing yet.

**Comment by vinistock** [comment]
We're now adding more and more fixtures and including YARP's own fixtures to our test suites. I think adding this project check executable will not deliver any value, since from now on the majority of problems we hit are never with valid syntax, but when the file is in a transient state with syntax errors.

Closing this for now.
