### ISSUE TITLE
Change how rubocop issues are reported. 

### ISSUE THREAD

**Issue by ccarse** [Shopify/ruby-lsp#355]
Today if rubocop detects certain issues like Metrics/AbcSize it will underline the entire method. This adds a lot of noise and can hide other issues. Solargraph took the approach that if a rubocop issue is more than one line only ever underline the first line. In practice I find this to be MUCH nicer. I've looked into making this change and have it working locally. Is this a contribution that would be considered? If so I'll get a PR together. See images for examples:
![Screen Shot 2022-11-09 at 1 48 36 PM](https://user-images.githubusercontent.com/1965943/200915498-431f9266-7f28-4e30-971d-d603739c9ba7.png)
![Screen Shot 2022-11-09 at 1 45 18 PM](https://user-images.githubusercontent.com/1965943/200915514-3012ef91-449a-48ea-a3ec-b6161f6752d4.png)

**Comment by vinistock** [comment]
While I agree about the visual pollution of having everything underlined, it doesn't feel like it's the correct level of responsibility to have the language server adjust violation locations reported by a linter.

Have you tried proposing changing the locations where violations are added to in RuboCop? Maybe the rules are adding violations to the entire method definition node for simplicity, but they'd be open to adjusting it.

**Comment by ccarse** [comment]
Okay, I can see where you're coming from. I guess the way I think about it is that rubocop reports the location of the entire disgnostic and it's up to the consumer how to display that diagnostic to the user.

**Comment by vinistock** [comment]
I wasn't aware it had support for a highlight range. Is that the intended part of the code to be highlighted for a violation? If so, we can definitely change to use that range instead.

My objection is just against manipulating the locations from the LSP side, but if RuboCop already includes the information then we can certainly make use of it.
