### ISSUE TITLE
Question: What do folks think of adding rubyfmt as a formatter option?

### ISSUE THREAD

**Issue by jscharf** [Shopify/ruby-lsp#409]
I have been experimenting with the rubyfmt project recently https://github.com/fables-tales/rubyfmt and wanted to ask here what folks think of adding it as a formatter for this project?

I'm not sure if it even fits with this project's goals or architecture, but I want to ask anyway just in case. It's my understand that it already supports a built-in formatter, and Rubocop if the user has Rubocop configured. So the idea would be to add rubyfmt as another formatting option.

**Comment by vinistock** [comment]
Hey! Please take a look at this comment https://github.com/Shopify/ruby-lsp/issues/432#issuecomment-1376019129. We're definitely open to having different formatting options, but we'd like to be able to do that through plugins and not have tool-specific features be all implemented inside of the Ruby LSP codebase.

**Comment by vinistock** [comment]
Closing as https://github.com/Shopify/ruby-lsp/pull/739 allows for other formatters to be registered now.

**Comment by jscharf** [comment]
Posting here for future readers, since I opened this over a year ago... I have created the https://github.com/jscharf/ruby-lsp-rubyfmt project to bridge the technologies together: `rubyfmt`, `ruby-lsp`, and `vscode-ruby-lsp`. It's a VS code addon that can be used to hook into the formatting feature of the ruby LSP.
