### ISSUE TITLE
Improve handling of syntax errors from SyntaxTree

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#426]
Given some invalid Ruby such as:

```ruby
module Foo < Object
end
```

RuboCop will emit a useful message such as:
```
lib/ruby_lsp/requests/support/source_uri.rb:6:12: E: Lint/Syntax: unexpected token tLT
module Foo < Object
           ^
```
But ruby-lsp emits a generic syntax tree error (repeated several times):

<img width="291" alt="Screenshot 2023-01-03 at 4 28 33 PM" src="https://user-images.githubusercontent.com/13400/210574762-26680048-4353-4782-a56b-7ab31e9726ed.png">

**Comment by bitwise-aiden** [comment]
Closed with the above PR
