### ISSUE TITLE
Adding a Standard runner alongside Rubocop?

### ISSUE THREAD

**Issue by searls** [Shopify/ruby-lsp#432]
I'm new to this project but newly interested in LSPs and editor extensions since seeing how fast @will's [LSP implementation](https://github.com/testdouble/standard#language-server-protocol-support) for Standard Ruby is.

Are you open to a Standard Ruby runner alongside this [RuboCop one]?(https://github.com/Shopify/ruby-lsp/commits/07b8cdbc5ba0fa32c9a15dd65aed3d646bc854d8/lib/ruby_lsp/requests/support/rubocop_runner.rb)? Beyond that, I imagine there'd be a little more work to connect it to editor plugins like [vscode-ruby-lsp](https://github.com/Shopify/vscode-ruby-lsp)?

cc/@vinistock @camilopayan

**Comment by vinistock** [comment]
We definitely want to support other formatters and have tool or framework specific functionality coming from the Ruby LSP. There's also a proposal to support rubyfmt #409.

We should first figure out how to introduce Ruby LSP plugins in #443 to be able to scale tool or framework specific features being provided from the server. Ideally, each tool that wants to provide editor features could export their own plugin and have the Ruby LSP surface that functionality - removing the need for the Ruby LSP to have tool specific implementations.

**Comment by searls** [comment]
@j-manu - I appreciate this, but running Standard's configuration via a RuboCop config and the RuboCop CLI or Rake task directly isn't quite the same thing, since any other configuration or ruleset could override the intended-to-not-be-overridable rules in Standard. I [touched on this](https://blog.testdouble.com/posts/2023-01-19-super-standard-adding-gem-extensions-and-custom-rules/#how-it-works) briefly in a blog post last week when announcing Standard's new support for _importing RuboCop configurations_ in such a way as to prevent them the risk that any of them override Standard's (I realize this is a bit of an ouroboros at this point)

**Comment by j-manu** [comment]
@searls I understand. The above config is meant as a stopgap solution. I didn't want to give up on ruby-lsp or standard and this helped me use both.

**Comment by iamajvillalobos** [comment]
With the vs code extension, can we use them both now at the same time?

**Comment by searls** [comment]
Thank you for clarifying!

**Comment by drnic** [comment]
I was setting up a new vscode, and so I have a tiny [sample] `settings.json` that I can share that I think summarises @searls + @vinistock above (plus my own preference for rvm)

```json
{
    "workbench.colorTheme": "Spinel",
    "editor.inlineSuggest.enabled": true,
    "window.zoomLevel": -1,
    "[ruby]": {
        "editor.defaultFormatter": "testdouble.vscode-standard-ruby",
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.semanticHighlighting.enabled": true
    },
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "editor.rulers": [
        120
    ],
    "rubyLsp.rubyVersionManager": "rvm",
    "rdbg.rubyVersionManager": "rvm",
    "rubyLsp.enabledFeatures": {

        "codeActions": false,
        "diagnostics": false,
        "documentHighlights": true,
        "documentLink": true,
        "documentSymbols": true,
        "foldingRanges": true,
        "formatting": false,
        "hover": true,
        "inlayHint": true,
        "onTypeFormatting": true,
        "selectionRanges": true,
        "semanticHighlighting": true,
        "completion": true,
        "codeLens": false
    }
}
```

**Comment by searls** [comment]
@vinistock hey Vini, looks like that document is [you linked to](https://shopify.github.io/ruby-lsp/SERVER_EXTENSIONS_md.html) is a 404. Can you point me to the right guide?

**Comment by vinistock** [comment]
Yes, we renamed Ruby LSP extensions to Ruby LSP addons to try to avoid confusion with the VS Code extension.

Here's the [doc](https://github.com/Shopify/ruby-lsp/blob/main/ADDONS.md).

**Comment by searls** [comment]
Thanks @vinistock, I'll raise questions in the [Ruby DX Slack](https://join.slack.com/t/ruby-dx/shared_invite/zt-1zjp7lmgk-zL7bGvze8gj5hFaYS~r5vg)'s `#ruby-lsp-extension` room
