### ISSUE TITLE
Inlay hint repeated multiple times

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#459]
Create a file:

```ruby
begin
rescue
end
```

The inlay hint is repeated many times:

<img width="1044" alt="Screenshot 2023-01-16 at 2 45 37 PM" src="https://user-images.githubusercontent.com/13400/212755397-28e047ec-1ad2-4ef3-8d7b-25a3d34a04f4.png">

**Comment by adisonlampert** [comment]
Hi Andy!
When I tried to recreate this by making a Ruby file in the `ruby-lsp` repository to test, I only saw one inlay hint:


![Image](https://user-images.githubusercontent.com/38566184/212929329-f51f2c77-8a81-4e22-8942-52f50605da0c.png)

What project/file did you have open when you noticed this bug? How can I recreate it? Thanks!

**Comment by dirceu** [comment]
I've also tried to reproduce using that exact same `test.rb` file in the root of `ruby-lsp` (latest `main`, with Ruby 3.2.0, using VS Code on the stable release channel), with no success 🤔

**Comment by andyw8** [comment]
I'll close this for now then until we see at least one other report, maybe it's something specific to my machine.
