### ISSUE TITLE
Fix behaviour of DocumentLink for when a gem has been removed

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#464]
_Originally posted by @vinistock in https://github.com/Shopify/ruby-lsp/pull/463#discussion_r1083056874_
            

 > I think the mistake was actually the other way around. If the source comment is for a gem that is no longer a part of the bundle, then `GEM_TO_VERSION_MAP[uri.gem_name]` will return `nil`.

> Instead of doing the `T.must`, we need to return early in that case.

**Comment by andyw8** [comment]
@haroon26 done!

**Comment by vinistock** [comment]
@haroon26 are you looking into this? Let us know if you need any help. Otherwise, we can remove the assignment to let somebody else pick it up.

**Comment by haroon26** [comment]
Hello @vinistock, I got busy with my work so completely forgot about it. I will resolve it on priority this week. Thank you.
