### ISSUE TITLE
How to install ruby-lsp if application runs in VM/Docker and VSCode runs on host?

### ISSUE THREAD

**Issue by tisba** [Shopify/ruby-lsp#480]
In my setup, for many projects, I run VSCode on macOS and my application runs either in Docker or another VM (using some file sharing mechanism).

Unless I'm overlooking something, I don't quite know how am I supposed to install `ruby-lsp` in this case. In case that's not supported, that might be worth a note in the README.

**Comment by tisba** [comment]
Sorry, I should have said that from the beginning 🙈 Yes, I can add it to the `Gemfile` and it works.

The `Gemfile` is massive and optimized/configured for a Linux environment (b/c it runs in Docker or a VM). I would have to install a lot of other dependencies to be able to build all the native extensions. Also, not everybody on the team uses VSCode (or ruby-lsp) for that matter.

Anyway, is there an option to specify a different `Gemfile` maybe?

I'd be also interested in the reasoning for having ruby-lsp managed by bundler.


PS: no offense btw, I'm well aware that ruby-lsp is an opinionated LSP and purpose build for Shopify's use :)

**Comment by CKolkey** [comment]
You can specify a different gemfile for bundler. Here's what I use for work: https://gist.github.com/CKolkey/bf0bef4fa931e75d635e91b12d0c188a

If you need to update the _real_ gemfile for any reason, remember to prefix `BUNDLE_GEMFILE=Gemfile`

**Comment by tisba** [comment]
wow, thank @CKolkey! I totally forgot about that bundler feature! Any idea how to make VSCode/`ruby-lsp` pickup custom environment variables? 🤔  By setting `BUNDLE_GEMFILE=Gemfile.dev` and just have `ruby-lsp` in there, I could sidestep the problem of having to install a truckload of stuff, that I don't even need.

**Comment by CKolkey** [comment]
Not sure about the vs-code stuff (neovim user). Maybe something like https://direnv.net/ will work? And/or if you launch vs-code from the shell via `code`? Just guessing there.
