### ISSUE TITLE
Intermittent failing test on Ruby 2.7

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#499]
After merging https://github.com/Shopify/ruby-lsp/pull/498 we saw a failing test on main. It passed on the re-run, but it seems order dependent, I was able to reproduce it locally with:

```
git checkout 5733d790f251db87e9960a7e5d81d2b09dc425c9
TESTOPTS="--seed=4107" bin/test
```

**Comment by vinistock** [comment]
If you run that specific example and put a breakpoint in the exact point where it fails, are you able to see the exception?
