### ISSUE TITLE
Add custom cop for language server constant aliases

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#503]
Anything inside the `RubyLsp` module has direct access to the `Interface`, `Transport` and `Constant` modules, which saves us from typing `LanguageServer::Protocol` in front of them every time.

Let's add a custom cop inside this repo to autocorrect usages if they happen inside the `RubyLsp` module.

**Comment by caalberts** [comment]
Hi @vinistock, I'm interested to take this one up.

Is the intent to replace lines such as the following:

```rb
      sig { override.returns(T.all(T::Array[LanguageServer::Protocol::Interface::FoldingRange], Object)) }
```

into this?

```rb
      sig { override.returns(T.all(T::Array[Interface::FoldingRange], Object)) }
```

I'm thinking of creating the cop first, then depending on how many violations it finds, decide whether to fix them or create todos.
