### ISSUE TITLE
Spec blocks in RSpec files are not foldable

### ISSUE THREAD

**Issue by amiratak88** [Shopify/ruby-lsp#515]
```
RSpec.describe SomeObject do
	describe "#some_method" do
		...
    end

	describe "#some_other_method" do
		...
    end
end
```

In the above code, only the main `RSpec.describe` block is foldable. The two nested `describe` blocks are not.

**Comment by andyw8** [comment]
Ah, I see the issue now - it happens only if you omit the parenthesis for `SomeObject`.

**Comment by andyw8** [comment]
The upgrade of syntax_tree in https://github.com/Shopify/ruby-lsp/pull/538 by @vinistock will unblock this.
