### ISSUE TITLE
Duplicate results in Folding Ranges response

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#525]
While looking into https://github.com/Shopify/ruby-lsp/pull/517 I noticed that the response may contain duplicates, e.g.:

```ruby
RSpec.describe(SomeObject) do
  describe "#some_method" do
    # 1
  end
end
```
results in:
```
{
  "result": [
    {
      "startLine": 0,
      "endLine": 3,
      "kind": "region"
    },
    {
      "startLine": 1,
      "endLine": 2,
      "kind": "region"
    },
    {
      "startLine": 1,
      "endLine": 2,
      "kind": "region"
    }
  ],
  "params": []
}`
```

Although this doesn't seem to impact the behaviour, it likely indicates something isn't quite right with the parsing.

It would be helpful to have something in the tests to catch this.

**Comment by vinistock** [comment]
In that case, the solution is likely to remove `SyntaxTree::Command` from the list of simple nodes, but we may need to do something to make sure commands with multiline arguments are still folding properly. E.g.:
```ruby
command 1,
  2,
  3 do
  # both the block and the arguments should be foldable
end
```
