### ISSUE TITLE
Only fallback to Syntax Tree if part of the project's `Gemfile` or `gemspec`

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#546]
Currently, if RuboCop isn't present, we [fall back](https://github.com/Shopify/ruby-lsp/blob/e145cfb74928ab43e2da37ed13a2ae787633f463/lib/ruby_lsp/requests/formatting.rb#L62-L67) to using Syntax Tree for formatting.

With the [recent change](https://github.com/Shopify/vscode-ruby-lsp/pull/419) of allowing Ruby LSP to be used even if not included in the Gemfile, this may result in undesired formatting on projects which use neither RuboCop nor Syntax Tree.

We will change this so that we only fall back to Syntax Tree if it is listed in the `Gemfile` or `gemspec`, since that can be taken as a strong signal that formatting should be applied.

**Comment by vinistock** [comment]
Sorry, I must disagree. I think this needs to be configured on the server or else it won't work for other editors.

To work with our long term plans of having server extensions, I think the right way to go is to
- Solve https://github.com/Shopify/vscode-ruby-lsp/issues/430 and https://github.com/Shopify/vscode-ruby-lsp/issues/399#issuecomment-1460465843. We need to receive another [initialization option](https://github.com/Shopify/ruby-lsp/blob/ac7d7132ee0337d5be9aff2646107d7d172644f3/lib/ruby_lsp/executor.rb#L312) to know which formatter was selected (and the default can be `nil`).
- Then the server will only broadcast the [formatting capability](https://github.com/Shopify/ruby-lsp/blob/ac7d7132ee0337d5be9aff2646107d7d172644f3/lib/ruby_lsp/executor.rb#L388) if:
    - Formatting is enabled
    - RuboCop or Syntax Tree are present in the original bundle if no formatter was selected in the initialization options
    - If a formatter was selected, then we use that one

**Comment by st0012** [comment]
How can the server know about the original bundler 🤔 

BTW, I seriously think this should be resolved before we make an official `0.2.0` release on the extension because I have to disable `formatOnSave` for all projects now (can't do that just for irb or debug without committing).

**Comment by andyw8** [comment]
Completed in https://github.com/Shopify/ruby-lsp/pull/654
