### ISSUE TITLE
Add inlay hints support to the `ruby-lsp`

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#55]
Inlay hints display "invisible" information to the user to assist with the understanding of the code. For example:

```ruby
class User < ApplicationRecord
  (self.)has_many :posts
#^ inlay hint displaying the receiver (doesn't actually exist in the real code)
end
```

We can also display the name of positional arguments as inlay hints.

Documentation: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint

**Comment by st0012** [comment]
@vinistock I want to give this a try. I'll start by listing common cases that can use the hint.

**Comment by vinistock** [comment]
There's no built-in way by checking the method definition straight. We'd need to keep track of which section we're currently inside. Something like this in pseudo code

```ruby
class InlayHint < BaseRequest
  def initialize(...)
    @current_visibility = :public # Maybe use a Sorbet enum?
  end

  def visit_call(node) # not sure if it's call, command, fcall...
    if this_thing_is_private_public_or_protected
      @current_visibility = the_new_visibility
    end
  end

  def visit_def(node)
    add_hint_using_current_visibility
  end
end
```
Two thoughts:
- I think we shouldn't add anything for public methods, since that's the default
- If it's possible, I think this inlay hint would look better on top of the method name (not on the left or right)

**Comment by RyanBrushett** [comment]
Ooo neat, thanks for the pointers!

> I think we shouldn't add anything for public methods, since that's the default

Completely agree. That would be really messy.

> If it's possible, I think this inlay hint would look better on top of the method name (not on the left or right)

Should be entirely possible. This hint in particular really runs the risk of looking messy, I agree that above is a good place to start. If I get a chance to hack on it, I'll be sure to propose a few options with screenshots for easy evaluation.
