### ISSUE TITLE
Support SyntaxTree options from .streerc file

### ISSUE THREAD

**Issue by molawson** [Shopify/ruby-lsp#570]
👋🏼 First off, this project is really exciting, especially it's SyntaxTree integration!

Starting with [`v3.3.0`](https://github.com/ruby-syntax-tree/syntax_tree/blob/main/CHANGELOG.md#330---2022-08-02), SyntaxTree has supported storing CLI options in an `.streerc` file.  Right now, running the format command with this LSP only uses the SyntaxTree defaults.

Are there any plans to support that `.streerc` file?  

If there's an appetite for this from the maintainers' end, I'd be happy to take a swing at a PR.

**Comment by vinistock** [comment]
Thank you for the interest in the project!

I think it makes perfect sense to read configurations from the `.streerc` file, feel free to take a stab at the PR.

Keep in mind that we most certainly only want to read and parse configurations once, similar to what we do in RuboCop.
