### ISSUE TITLE
Add support for document link to the `ruby-lsp`

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#58]
The document link request allows us to attach a link to a piece of code. This is very useful to directing people to documentation. Some examples of what we can do:
- When looking at Sorbet things, link to the Sorbet documentation
- When looking at Rails things, link to the Rails documentation
- When looking at GraphQL things, link to the GraphQL documentation
- When hovering gems on the Gemfile, link to the official repo

**Note**: remember that if we want to add any internal resources, we'll have to allow this to be configurable somehow.

Idea: since we don't do type checking, we can't be absolutely sure that a method comes from Rails/Sorbet/GraphQL. As a best effort, we can check the parent class and other method invocations within the file to make a best guess before linking to the documentation.

Documentation: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

**Comment by egiurleo** [comment]
Support for the DocumentLink request was added in https://github.com/Shopify/ruby-lsp/pull/195.
