### ISSUE TITLE
Add code lens for running tests

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#584]
Discover test examples using the code lens request and return `Run` entries for each one plus one for running the entire file at the class level.

We should
- Support only Minitest / test-unit for now
- Allow running specific examples or the entire test class
- Use the `data` attribute (which allows for any information we want) to
    - Specify that the code lens is a test (e.g.: `type: "test"`). This will make it easier to create a test controller on VS Code
    - Specify the command that the client should use to execute that test. It'll most likely be `TESTOPTS="-n='/NAME_OF_THE_TEST/'" ruby -Itest PATH_TO_TEST_FILE`. Do not use `rake` since we want to be able to run tests even in projects that may not be using it

**Note**: this also involves creating a VS Code command that is used to execute the test. The first version of this should only grab whatever command was received in the `data` attribute and run that in the terminal.

Documentation: https://microsoft.github.io/language-server-protocol/specification#textDocument_codeLens

**Comment by adisonlampert** [comment]
@matteeyah 
> The main things that I think are missing as of right is starting a debugging session for a test

This is one of our goals. We've been working on setting up `ruby/debug` (for example, #431). Adding test running capability is just the first step 😃
