### ISSUE TITLE
Document how to create server extensions and guidelines

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#588]
We need to document creating server extensions in detail to help authors make the most out of the functionality without degrading the experience accidentally.

Write a new `SERVER_EXTENSIONS.md` file documenting
- How to structure a new server extension
- What to do in the extension activation point
- How to use the new hover extension point #586 
- How to test that the extension is working properly using our helpers

In addition to that, the first section of the file should include a set of guidelines that we use to develop the Ruby LSP and should also be followed by extensions. For example
- Performance over features. We do not sacrifice performance for niche features or minor changes in the experience
- Doing heavy lifting ahead of time if possible. If we can load and cache something, we do that and avoid blocking requests
- Requests do not mutate state directly. A request (or an extension) should never mutate a document instance. It should instead use text edits and delegate the decision of when to do it to the client

**Comment by st0012** [comment]
Just as a reminder: we should include [rails_ruby_lsp](https://github.com/Shopify/rails_ruby_lsp) when writing this.
