### ISSUE TITLE
syntax_tree gem uses triple dots Ruby >= 2.7 syntax for method parameters

### ISSUE THREAD

**Issue by vittorius** [Shopify/ruby-lsp#599]
Hey all. I'm getting the following error when running the `ruby-lsp` extension in VS Code:

```
bundler: failed to load command: ruby-lsp (/Users/vittorius/.rbenv/versions/2.6.9/bin/ruby-lsp)
/Users/vittorius/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/syntax_tree-2.3.1/lib/syntax_tree.rb:9:in `require_relative': /Users/vittorius/.rbenv/versions/2.6.9/lib/ruby/gems/2.6.0/gems/syntax_tree-2.3.1/lib/syntax_tree/formatter.rb:12: syntax error, unexpected ... (SyntaxError)
    def initialize(source, ...)
                           ^~~
```

My project is Ruby 2.6.9.

This means that although `ruby-lsp` is able of choosing the right Ruby version via the version manager it is not able to support different Ruby versions by itself

**Comment by vinistock** [comment]
This is similar to https://github.com/Shopify/vscode-ruby-lsp/issues/508. The gem has a [requirement on Ruby 2.7](https://github.com/Shopify/ruby-lsp/blob/045f7d6206d98bb3633db6a2548aea076d7a148b/ruby-lsp.gemspec#L24) or higher indeed.

This is not well surfaced in the VS Code extension, we'll need to add a message to warn people that the server won't run on old rubies.

On jruby, you may hit other issues. We were trying to [add it to our CI](https://github.com/Shopify/ruby-lsp/pull/549), but it seems that are a few inconsistencies in its `Ripper` implementation when compared to MRI, so you may get weird results.
