### ISSUE TITLE
`Extract Variable` refactor won't prompt for variable name and misindents

### ISSUE THREAD

**Issue by hakanensari** [Shopify/ruby-lsp#602]
On the heels of #594, I thought I should post this.

![recording](https://user-images.githubusercontent.com/31693/229160160-ff9d8958-af02-4a0b-b8dd-8c8f72fe4216.gif)

You can see above that the refactored line did not indent correctly, and we were not prompted for a variable name.

For reference, [a good implementation](https://code.visualstudio.com/docs/editor/refactoring#_extract-variable).

**Comment by vinistock** [comment]
The indent thing is a bug indeed.

Regarding selecting the name of the variable, that's a separate request. If you pay attention to the video on that page, it first extracts the variable with a generic name and then prompts for changing it. The second part is a rename request, which the Ruby LSP doesn't support yet #57.
