### ISSUE TITLE
On type formatting's `end` insertion bug

### ISSUE THREAD

**Issue by sambostock** [Shopify/ruby-lsp#608]
## TL;DR

![vscode-shopify-ruby end bug](https://user-images.githubusercontent.com/8219340/229647556-3db39f45-2b54-426d-9309-4983fb188381.gif)

## Details

Consider the following code:

```ruby
def m
  "abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz"
end
```

The line is too long, so one might opt to turn it into

```ruby
def m
  "abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz " \
    "abcdefghijklmnopqrstuvwxyz"
end
```

However, attempting to do so by inserting `" \` and then hitting enter corrupts the code by inserting a rogue `end`:

### Expected

```ruby
def m
  "abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz " \
  abcdefghijklmnopqrstuvwxyz" # or maybe with some more indentation
end
```

### Actual

```ruby
def m
  "abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz " \
  abcdefghijklmnopqrstuvwxyz"
en  endd
```

**Comment by andyw8** [comment]
@sambostock For this particular example, it seems to be due the string containing `def`, which is being treated specially. I'm seeing similar behaviour for any of these tokens:

https://github.com/Shopify/ruby-lsp/blob/158a735def31ba23e6d83a62466a15a128bab4bb/lib/ruby_lsp/requests/on_type_formatting.rb#L23

I'm looking into a fix, but have you observed this behaviour for any strings _not_ containing one of those tokens?
