### ISSUE TITLE
Execute all nonpositional requests in one round of visits

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#611]
Depends on #610 

Now that all requests are listeners, we can execute all the nonpositional requests in one round of visits to avoid having to go through the AST more than once.

For all of the different features involved, we will execute the same thing, always checking if there's a cached result already. For example, the executor implementation would look something like this
```ruby
case request[:method]
when "textDocument/foldingRange", "textDocument/documentSymbol", ...
  document = @store.get(uri)
  
  # If a cached result exists for the requested method and current document version, just return that straight away
  cached = document.cache_fetch(request[:method])
  return cached if cached

  # Otherwise, build the cache for all requests
  listeners = [
    Requests::FoldingRange.new,
    Requests::DocumentSymbol.new,
    Requests::SemanticHighlighting.new,
  ]
  EventEmitter(*listeners).visit(document.tree)
  document.save_cache(listeners)
  # Return the result for the right listener according to the requested method
end
```

**Comment by andyw8** [comment]
Already being done step by step as we migrate to the new Emitter pattern.
