### ISSUE TITLE
Evaluate if we should add Sorbet

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#62]
Evaluated the advantages and disadvantages to add Sorbet to the `ruby-lsp`, so that we can decide on whether we want to do it or not.

If the decision is to add Sorbet, add it using our default tooling.

**Comment by egiurleo** [comment]
Awesome, thank you!

**Comment by Morriar** [comment]
Let's close this since we already decided to add it: https://github.com/Shopify/ruby-lsp/pull/119.
