### ISSUE TITLE
Create VS Code profile for recording our GIFs

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#683]
It would be good to have a VS Code profile that we can use as the standard for recording all of our documentation GIFs.

I'm not super familiar with the profiles feature yet, but I assume you can export it and put it in the `.vscode` folder to make it accessible to others.

The profile should use
- A large font size so that it's easy to see in the GIFs (16?)
- The Spinel theme
- The default font bundled in VS Code
- Only the extensions that are part of [vscode-shopify-ruby](https://github.com/Shopify/vscode-shopify-ruby)

**Comment by D-Forz** [comment]
Hi, I would like to help with this!

**Comment by andyw8** [comment]
@D-Forz Thank you, feel free to open a PR.
