### ISSUE TITLE
Reek/Goto definition support

### ISSUE THREAD

**Issue by andreacasarin** [Shopify/ruby-lsp#697]
### I have checked that this feature is not already implemented

- [X] This feature does not exist

### Use case

I'm currently using a bunch of VSCode extensions to support ruby coding, including Solargraph. I'd love to switch to only have ruby-lsp and it's extension which are great, however I'm missing a couple of key features:

- goto definition
- reek support (https://github.com/troessner/reek)

### Description

I'd love to have reek reporting code smells, in a clean way so that it's more like a suggestion than an error. I'd also love to be able to CMD/Control click a class name/method name to go to it's definition.

### Implementation

.

**Comment by vinistock** [comment]
Go to definition is tracked by #199.

Regarding adding Reek support, that would need to be done using the Ruby LSP server extensions systems that we're currently working on. Once we finish putting the mechanism in place, Reek can export a Ruby LSP extension to add extra diagnostics (or a separate `ruby-lsp-reek` gem can be created).

**Comment by igray** [comment]
For anyone following this issue RE: reek support, this add-on now exists: https://github.com/igray/ruby-lsp-reek

**Comment by st0012** [comment]
@valerii-pohrebniak-rg please move the discussion to `ruby-lsp-reek`'s issue, thanks 🙂
