### ISSUE TITLE
Smoke test against a minimal Ruby project

### ISSUE THREAD

**Issue by andyw8** [Shopify/ruby-lsp#741]
## Background

https://github.com/Shopify/ruby-lsp/pull/698 wasn't caught because we were testing against a codebase which had already required `uri`.

## Approach

To help prevent bugs such as https://github.com/Shopify/ruby-lsp/pull/698, we want to create a basic smoke test against a very minimal project. As a starting point this could just ensure that Ruby LSP boots successfully.

**Comment by giovannism20** [comment]
Hey @andyw8, do we have a list of basic functionalities that should be tested ?

**Comment by giovannism20** [comment]
Would it be interesting to put this in another test file @andyw8 ?

**Comment by andyw8** [comment]
Yes, e.g. `test/full_integration_test.rb`

**Comment by giovannism20** [comment]
Ok, I'll create it! ;)
