### ISSUE TITLE
Incorrect Folding for `else`

### ISSUE THREAD

**Issue by abhiroopdutta** [Shopify/ruby-lsp#754]
### Ruby version

3.1.2

### Description

Ruby LSP incorrectly folds if-else conditional block. The "else" condition is completely hidden. 
This can be reproduced by simply writing an if-else block and folding the if statement in VS Code. 
<img width="765" alt="Screenshot 2023-06-13 at 2 51 09 PM" src="https://github.com/Shopify/ruby-lsp/assets/19819930/976b685b-6e09-471a-90dc-daf6130283c9">

### Expected output

The else block should not be hidden when folding the if statement - 
<img width="765" alt="Screenshot 2023-06-13 at 2 53 18 PM" src="https://github.com/Shopify/ruby-lsp/assets/19819930/4f9ce466-f965-418d-a1f9-5d4963d5a97a">

**Comment by andyw8** [comment]
Note: The 'expected' output matches how VS Code folds JavaScript.

**Comment by abhiroopdutta** [comment]
I would like to work on this. I have no prior experience developing VS Code Extensions though, it would be helpful if you could point me to the right resources to get started.

**Comment by andyw8** [comment]
Great! The implementation is in https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/requests/folding_ranges.rb

You will need to update the expectation files to match the new behaviour, https://github.com/Shopify/ruby-lsp/blob/main/CONTRIBUTING.md explains how those are used.

Feel free to ask other questions here.

**Comment by andyw8** [comment]
I've added some details here: https://github.com/Shopify/ruby-lsp/pull/756
