### ISSUE TITLE
Error in Neovim LSP: `params` could be an array?

### ISSUE THREAD

**Issue by okuramasafumi** [Shopify/ruby-lsp#804]
### Ruby version

3.2.2

### Code snippet

My neovim configuration is like below:

```lua
lspconfig.ruby_ls.setup {}
```

When I open a Ruby file, it outputs an error log like below:

```
[ERROR][2023-07-10 18:13:22] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/okuramasafumi/.rbenv/shims/ruby-lsp"	"stderr"	"/Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/lib/ruby_lsp/server.rb:105:in `dig': no implicit conversion of Symbol into Integer (TypeError)\n\n            uri = request.dig(:params, :textDocument, :uri)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/lib/ruby_lsp/server.rb:105:in `block (2 levels) in start'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/lib/ruby_lsp/server.rb:98:in `synchronize'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/lib/ruby_lsp/server.rb:98:in `block in start'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/language_server-protocol-3.17.0.3/lib/language_server/protocol/transport/io/reader.rb:20:in `read'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/lib/ruby_lsp/server.rb:65:in `start'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10908/lib/types/private/methods/_methods.rb:277:in `bind_call'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10908/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ruby-lsp-0.6.2/exe/ruby-lsp:75:in `<top (required)>'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/bin/ruby-lsp:25:in `load'\n\tfrom /Users/okuramasafumi/.rbenv/versions/3.2.2/bin/ruby-lsp:25:in `<main>'\n"
```

### Description

The error is occurring in this line.
https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/server.rb#L107

I noticed that in LSP spec, `params` could be an array.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#requestMessage

The error message above can be interpreted that params is an array. And since the spec allows it, `ruby-lsp` should be able to handle it.

### Expected output

No error.

**Comment by vinistock** [comment]
Thank you for the bug report!

What specific request sends `params` as an array? This doesn't happen in VS Code, so I'm trying to understand why this would happen.

**Comment by vinistock** [comment]
I'm still not sure about when `params` can be an array and what to expect. This `window/progress` method is not listed in the specification as far as I can see it.

Folks discussing in #188 managed to get the LSP to work in neovim, so I'm wondering if this is specific to some plugin.

**Comment by okuramasafumi** [comment]
I found it's related to https://github.com/neovim/neovim/issues/23511
It seems `server_ready()` function is broken and I call it in my config [here](https://github.com/okuramasafumi/dotfiles/blob/7f965867620b8b5259022d1b8f2e2f08776d57b6/nvim/init.lua#L557).

After removing it, the error is resolved but it seems there's still a problem for it to work correctly. I'll check the discussion #188.
