### ISSUE TITLE
Allow more requests to be extended

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#808]
In #782, we encapsulated the logic to execute multiple listeners in the base implementations. Let's generalize this even more to be implemented in the parent `Listener` class and let's expose a configuration to allow requests to be extended.

Something like this
```ruby
class Hover < Listener
  extensible!
end
```

Then let's allow the following requests to be enhanced by extensions:
- semantic highlighting
- document symbols - https://github.com/Shopify/ruby-lsp/pull/949
- definition - https://github.com/Shopify/ruby-lsp/pull/989

**Comment by st0012** [comment]
Today at the DX stream meeting we talked about that on some requests, we may need to expose more info or even make certain data mutable to our extensions. I think semantic highlight may be one of them.

Consider this:

```rb
class Foo < ApplicationRecord
  before_save :bar
end
```

Currently `before_save` is marked as a `method` with no modifiers by `ruby-lsp`. If `ruby-lsp-rails` wants to enhance it by assigning modifiers (e.g. declaration), the current way of merging response won't be able to achieve it.

@vinistock can you check if my understanding on this case is correct. And if it is, should we still make it extensible before we discuss further about the data flow between ruby-lsp/extensions?

**Comment by vinistock** [comment]
Yes, your understanding is correct. We'll indeed need to think of a better strategy if two extensions want to modify the same semantic token. Let's put this on pause while we plan of a better abstraction for merging responses from extensions.

**Comment by st0012** [comment]
Waiting for https://github.com/Shopify/ruby-dev-exp-issues/issues/1050
