### ISSUE TITLE
An error occurred executing `ruby-lsp`

### ISSUE THREAD

**Issue by mihyaeru21** [Shopify/ruby-lsp#823]
### Ruby version

3.1.4

### Description

When I run the `ruby-lsp` command in version 0.7.3, I get the following error after the output as if the `bundle install` was successful. In my environment, this happens with private gems that are obtained via git.

```
[GEM NAME] is not yet checked out. Run `bundle install` first.
```

`BUNDLE_PATH` is specified [at `bundle install`](https://github.com/Shopify/ruby-lsp/blob/v0.7.3/lib/ruby_lsp/setup_bundler.rb#L125) but not [at runtime](https://github.com/Shopify/ruby-lsp/blob/v0.7.3/exe/ruby-lsp#L15). I think this is most likely the cause of the error, since I ran `BUNDLE_GEMFILE=.ruby-lsp/Gemfile bundle install` manually to install gems globally and then ran `ruby-lsp` and the error did not occur.

### Expected output

No error should occur.

**Comment by vinistock** [comment]
Thanks for the bug report. I think you're correct in your assessment.

Can you please try this to confirm that this fixes it?

```shell
# You probably have a relative path configured for BUNDLE_PATH. Something like vendor/bundle
# Try to execute the LSP bypassing the custom bundle logic
# and using the absolute path just to see if it boots properly

BUNDLE_PATH=/absolute/path/to/project/vendor/bundle bundle exec ruby-lsp
```

If that prints that the LSP started properly, then this is indeed the issue. Please let us know if it works.

**Comment by mihyaeru21** [comment]
As you guessed, I had specified `vendor/bundle` in `BUNDLE_PATH`. The following was performed with the original error reproduced.

```
$ BUNDLE_PATH=$PWD/vendor/bundle bundle exec ruby-lsp
bundler: failed to load command: ruby-lsp (/absolute/path/to/my_project/vendor/bundle/ruby/3.1.0/bin/ruby-lsp)
...
```

There was no `BUNDLE_GEMFILE` so I got a different error.

```
$ BUNDLE_PATH=$PWD/vendor/bundle BUNDLE_GEMFILE=$PWD/.ruby-lsp/Gemfile bundle exec ruby-lsp
Starting Ruby LSP...
```

When I added `BUNDLE_GEMFILE`, it worked.
