### ISSUE TITLE
Handle constant aliases in the indexer

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#908]
Currently, the indexer does not properly take aliases into account. I think the best way of storing this is to create an `Alias` entry type that basically just proxies to the real entry. That way we know it's an alias, but also know what it resolves to.

One concern is how to properly handle if we discover the alias before we discover the aliased constant. For example

```ruby
# file 1. Gets indexed first
Alias = SomeClass

# file 2. Gets indexed after
class SomeClass
end
```

For this case, we will not know which constant is proxied by the alias when we discover it. We may need to make the `Alias` entry just keep the name for which it aliases to and then resolve it once someone tries to access it, when the index is fully built.

**Comment by vinistock** [comment]
Yes, you should, but that's not enough to fully handle aliases.

For example, in the Ruby LSP's own code, we alias `RubyLsp::Interface` to `LanguageServer::Protocol::Interface`. This means that when we do this

```ruby
module RubyLsp
  Interface::Hover
end
```
We need to be able to resolve `Interface::Hover` to the correct class, which is `LanguageServer::Protocol::Interface::Hover`. For simpler cases, where you're just referencing the alias constant directly, there's no need to know what it proxies to. But these more complex cases are currently unhandled.

**Comment by Morriar** [comment]
Ah, makes sense.

Note that constant definitions can be conditional, for example when depending on architecture or or dependencies:

```rb
if rand(0..1) # could be for a specific arch or if a dependency is loaded
   X = String
else
   X = Integer
end
```

**Comment by vinistock** [comment]
Yeah, I'm not sure how well we can handle condition declarations like those. Without a proper typechecker, we'll probably not be able to understand cases that aren't trivial. We might be better off ignoring those if they are inside conditionals.
