### ISSUE TITLE
Extension not active

### ISSUE THREAD

**Issue by JohnAnon9771** [Shopify/ruby-lsp#918]
### Ruby version

3.0.6

### Description

<img width="1332" alt="image" src="https://github.com/Shopify/ruby-lsp/assets/42195321/1df8bd62-9fa8-4cdf-a377-36d87267af32">

### Expected output

It is expected to fetch rubygems.org normally

**Comment by vinistock** [comment]
The message is coming from bundler and saying that installing gems is timing out. This _doesn't seem_ like a problem in the Ruby LSP.

Are you able to install gems normally in your terminal? If you retry does it continue timing out?

**Comment by JohnAnon9771** [comment]
Yes, I'm managing to install/update my gems through the terminal. I really don't understand what's going on...

Even reinstalling the extension, it keeps giving timeouts.

**Comment by andyw8** [comment]
Are you by chance on a corporate network connection through a proxy, or something like that?

**Comment by JohnAnon9771** [comment]
> Yes, I'm managing to install/update my gems through the terminal. I really don't understand what's going on...
> 
> Even reinstalling the extension, it keeps giving timeouts.

It really looks like it's a problem on my machine... with that, I'll close the issue. Thank you for your attention.
