### ISSUE TITLE
Allow configuring diagnostics only on save

### ISSUE THREAD

**Issue by vinistock** [Shopify/ruby-lsp#963]
Collecting RuboCop diagnostics is really expensive. The fact that diagnostic requests happen every time the user types, slows down the LSP in general to compute them.

Let's allow the user to configure if they want to receive diagnostics only after saving. That way, formatting runs first and you only see diagnostics about violations that can't be autocorrected. It's a tradeoff between immediate feedback and performance, but it'll help with cases like #932.

To do this, we need a new configuration on the extension side, choosing whether to receive diagnostics on save or on change.
- If the user configures on change, then we do what we're currently doing
- If the user selects on save, we don't run RuboCop during the diagnostic request. We instead do it on `textDocument/didSave`

**Comment by naveg** [comment]
This will be a big help, especially for very large files where rubocop can take multiple seconds to run each time.

**Comment by vinistock** [comment]
I just realized this is significantly easier to implement than I thought, since clients have the option to decide when they want to pull diagnostics. 

https://github.com/Shopify/vscode-ruby-lsp/pull/786 will add support for this.
